// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module pynq_filters_convertToUnsigned (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        img_in0_data_stream_0_V_V_dout,
        img_in0_data_stream_0_V_V_empty_n,
        img_in0_data_stream_0_V_V_read,
        img_in0_data_stream_1_V_V_dout,
        img_in0_data_stream_1_V_V_empty_n,
        img_in0_data_stream_1_V_V_read,
        img_in0_data_stream_2_V_V_dout,
        img_in0_data_stream_2_V_V_empty_n,
        img_in0_data_stream_2_V_V_read,
        img_out_data_stream_0_V_din,
        img_out_data_stream_0_V_full_n,
        img_out_data_stream_0_V_write,
        img_out_data_stream_1_V_din,
        img_out_data_stream_1_V_full_n,
        img_out_data_stream_1_V_write,
        img_out_data_stream_2_V_din,
        img_out_data_stream_2_V_full_n,
        img_out_data_stream_2_V_write
);

parameter    ap_ST_st1_fsm_0 = 4'b1;
parameter    ap_ST_st2_fsm_1 = 4'b10;
parameter    ap_ST_pp0_stg0_fsm_2 = 4'b100;
parameter    ap_ST_st6_fsm_3 = 4'b1000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv9_0 = 9'b000000000;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv10_0 = 10'b0000000000;
parameter    ap_const_lv9_1E0 = 9'b111100000;
parameter    ap_const_lv9_1 = 9'b1;
parameter    ap_const_lv10_280 = 10'b1010000000;
parameter    ap_const_lv10_1 = 10'b1;
parameter    ap_const_lv10_FE = 10'b11111110;
parameter    ap_const_lv32_9 = 32'b1001;
parameter    ap_const_lv8_FF = 8'b11111111;
parameter    ap_const_lv8_0 = 8'b00000000;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [9:0] img_in0_data_stream_0_V_V_dout;
input   img_in0_data_stream_0_V_V_empty_n;
output   img_in0_data_stream_0_V_V_read;
input  [9:0] img_in0_data_stream_1_V_V_dout;
input   img_in0_data_stream_1_V_V_empty_n;
output   img_in0_data_stream_1_V_V_read;
input  [9:0] img_in0_data_stream_2_V_V_dout;
input   img_in0_data_stream_2_V_V_empty_n;
output   img_in0_data_stream_2_V_V_read;
output  [7:0] img_out_data_stream_0_V_din;
input   img_out_data_stream_0_V_full_n;
output   img_out_data_stream_0_V_write;
output  [7:0] img_out_data_stream_1_V_din;
input   img_out_data_stream_1_V_full_n;
output   img_out_data_stream_1_V_write;
output  [7:0] img_out_data_stream_2_V_din;
input   img_out_data_stream_2_V_full_n;
output   img_out_data_stream_2_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg img_in0_data_stream_0_V_V_read;
reg img_in0_data_stream_1_V_V_read;
reg img_in0_data_stream_2_V_V_read;
reg img_out_data_stream_0_V_write;
reg img_out_data_stream_1_V_write;
reg img_out_data_stream_2_V_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_22;
reg    img_in0_data_stream_0_V_V_blk_n;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_2;
reg    ap_sig_59;
reg    ap_reg_ppiten_pp0_it1;
reg    ap_reg_ppiten_pp0_it0;
reg    ap_reg_ppiten_pp0_it2;
reg   [0:0] exitcond_reg_292;
reg    img_in0_data_stream_1_V_V_blk_n;
reg    img_in0_data_stream_2_V_V_blk_n;
reg    img_out_data_stream_0_V_blk_n;
reg   [0:0] ap_reg_ppstg_exitcond_reg_292_pp0_iter1;
reg    img_out_data_stream_1_V_blk_n;
reg    img_out_data_stream_2_V_blk_n;
reg   [9:0] col_reg_128;
wire   [0:0] exitcond2_fu_139_p2;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_89;
wire   [8:0] row_1_fu_145_p2;
reg   [8:0] row_1_reg_287;
wire   [0:0] exitcond_fu_151_p2;
reg    ap_sig_102;
reg    ap_sig_112;
wire   [9:0] col_1_fu_157_p2;
wire   [7:0] tmp_21_fu_195_p3;
reg   [7:0] tmp_21_reg_301;
wire   [7:0] tmp_22_fu_235_p3;
reg   [7:0] tmp_22_reg_306;
wire   [7:0] tmp_23_fu_275_p3;
reg   [7:0] tmp_23_reg_311;
reg   [8:0] row_reg_117;
reg    ap_sig_142;
reg    ap_sig_cseq_ST_st6_fsm_3;
reg    ap_sig_150;
wire   [0:0] tmp_s_fu_163_p2;
wire   [0:0] tmp_42_fu_169_p3;
wire   [0:0] tmp_45_fu_189_p2;
wire   [7:0] tmp_417_s_fu_181_p3;
wire   [7:0] tmp_43_fu_177_p1;
wire   [0:0] tmp_36_fu_203_p2;
wire   [0:0] tmp_46_fu_209_p3;
wire   [0:0] tmp_48_fu_229_p2;
wire   [7:0] tmp_421_s_fu_221_p3;
wire   [7:0] tmp_47_fu_217_p1;
wire   [0:0] tmp_37_fu_243_p2;
wire   [0:0] tmp_49_fu_249_p3;
wire   [0:0] tmp_51_fu_269_p2;
wire   [7:0] tmp_425_s_fu_261_p3;
wire   [7:0] tmp_50_fu_257_p1;
reg   [3:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'b1;
#0 ap_reg_ppiten_pp0_it1 = 1'b0;
#0 ap_reg_ppiten_pp0_it0 = 1'b0;
#0 ap_reg_ppiten_pp0_it2 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_continue)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(1'b0 == exitcond2_fu_139_p2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~(((1'b1 == ap_reg_ppiten_pp0_it1) & ap_sig_102) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_112)) & ~(1'b0 == exitcond_fu_151_p2))) begin
            ap_reg_ppiten_pp0_it0 <= 1'b0;
        end else if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (1'b0 == exitcond2_fu_139_p2))) begin
            ap_reg_ppiten_pp0_it0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~(((1'b1 == ap_reg_ppiten_pp0_it1) & ap_sig_102) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_112)) & (1'b0 == exitcond_fu_151_p2))) begin
            ap_reg_ppiten_pp0_it1 <= 1'b1;
        end else if ((((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (1'b0 == exitcond2_fu_139_p2)) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~(((1'b1 == ap_reg_ppiten_pp0_it1) & ap_sig_102) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_112)) & ~(1'b0 == exitcond_fu_151_p2)))) begin
            ap_reg_ppiten_pp0_it1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_reg_ppiten_pp0_it1) & ap_sig_102) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_112))) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end else if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (1'b0 == exitcond2_fu_139_p2))) begin
            ap_reg_ppiten_pp0_it2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it0) & ~(((1'b1 == ap_reg_ppiten_pp0_it1) & ap_sig_102) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_112)) & (1'b0 == exitcond_fu_151_p2))) begin
        col_reg_128 <= col_1_fu_157_p2;
    end else if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (1'b0 == exitcond2_fu_139_p2))) begin
        col_reg_128 <= ap_const_lv10_0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st6_fsm_3)) begin
        row_reg_117 <= row_1_reg_287;
    end else if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_142)) begin
        row_reg_117 <= ap_const_lv9_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~(((1'b1 == ap_reg_ppiten_pp0_it1) & ap_sig_102) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_112)))) begin
        ap_reg_ppstg_exitcond_reg_292_pp0_iter1 <= exitcond_reg_292;
        exitcond_reg_292 <= exitcond_fu_151_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        row_1_reg_287 <= row_1_fu_145_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (exitcond_reg_292 == 1'b0) & ~(((1'b1 == ap_reg_ppiten_pp0_it1) & ap_sig_102) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_112)))) begin
        tmp_21_reg_301 <= tmp_21_fu_195_p3;
        tmp_22_reg_306 <= tmp_22_fu_235_p3;
        tmp_23_reg_311 <= tmp_23_fu_275_p3;
    end
end

always @ (*) begin
    if (((1'b1 == ap_done_reg) | ((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(1'b0 == exitcond2_fu_139_p2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(1'b0 == exitcond2_fu_139_p2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_59) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_22) begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_89) begin
        ap_sig_cseq_ST_st2_fsm_1 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_150) begin
        ap_sig_cseq_ST_st6_fsm_3 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st6_fsm_3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_reg_292 == 1'b0))) begin
        img_in0_data_stream_0_V_V_blk_n = img_in0_data_stream_0_V_V_empty_n;
    end else begin
        img_in0_data_stream_0_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_reg_292 == 1'b0) & ~(((1'b1 == ap_reg_ppiten_pp0_it1) & ap_sig_102) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_112)))) begin
        img_in0_data_stream_0_V_V_read = 1'b1;
    end else begin
        img_in0_data_stream_0_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_reg_292 == 1'b0))) begin
        img_in0_data_stream_1_V_V_blk_n = img_in0_data_stream_1_V_V_empty_n;
    end else begin
        img_in0_data_stream_1_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_reg_292 == 1'b0) & ~(((1'b1 == ap_reg_ppiten_pp0_it1) & ap_sig_102) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_112)))) begin
        img_in0_data_stream_1_V_V_read = 1'b1;
    end else begin
        img_in0_data_stream_1_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_reg_292 == 1'b0))) begin
        img_in0_data_stream_2_V_V_blk_n = img_in0_data_stream_2_V_V_empty_n;
    end else begin
        img_in0_data_stream_2_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_reg_292 == 1'b0) & ~(((1'b1 == ap_reg_ppiten_pp0_it1) & ap_sig_102) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_112)))) begin
        img_in0_data_stream_2_V_V_read = 1'b1;
    end else begin
        img_in0_data_stream_2_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b0 == ap_reg_ppstg_exitcond_reg_292_pp0_iter1))) begin
        img_out_data_stream_0_V_blk_n = img_out_data_stream_0_V_full_n;
    end else begin
        img_out_data_stream_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b0 == ap_reg_ppstg_exitcond_reg_292_pp0_iter1) & ~(((1'b1 == ap_reg_ppiten_pp0_it1) & ap_sig_102) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_112)))) begin
        img_out_data_stream_0_V_write = 1'b1;
    end else begin
        img_out_data_stream_0_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b0 == ap_reg_ppstg_exitcond_reg_292_pp0_iter1))) begin
        img_out_data_stream_1_V_blk_n = img_out_data_stream_1_V_full_n;
    end else begin
        img_out_data_stream_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b0 == ap_reg_ppstg_exitcond_reg_292_pp0_iter1) & ~(((1'b1 == ap_reg_ppiten_pp0_it1) & ap_sig_102) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_112)))) begin
        img_out_data_stream_1_V_write = 1'b1;
    end else begin
        img_out_data_stream_1_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b0 == ap_reg_ppstg_exitcond_reg_292_pp0_iter1))) begin
        img_out_data_stream_2_V_blk_n = img_out_data_stream_2_V_full_n;
    end else begin
        img_out_data_stream_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b0 == ap_reg_ppstg_exitcond_reg_292_pp0_iter1) & ~(((1'b1 == ap_reg_ppiten_pp0_it1) & ap_sig_102) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_112)))) begin
        img_out_data_stream_2_V_write = 1'b1;
    end else begin
        img_out_data_stream_2_V_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : begin
            if (~ap_sig_142) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : begin
            if (~(1'b0 == exitcond2_fu_139_p2)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end
        end
        ap_ST_pp0_stg0_fsm_2 : begin
            if ((~((1'b1 == ap_reg_ppiten_pp0_it2) & ~(((1'b1 == ap_reg_ppiten_pp0_it1) & ap_sig_102) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_112)) & ~(1'b1 == ap_reg_ppiten_pp0_it1)) & ~((1'b1 == ap_reg_ppiten_pp0_it0) & ~(((1'b1 == ap_reg_ppiten_pp0_it1) & ap_sig_102) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_112)) & ~(1'b0 == exitcond_fu_151_p2) & ~(1'b1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end else if ((((1'b1 == ap_reg_ppiten_pp0_it2) & ~(((1'b1 == ap_reg_ppiten_pp0_it1) & ap_sig_102) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_112)) & ~(1'b1 == ap_reg_ppiten_pp0_it1)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & ~(((1'b1 == ap_reg_ppiten_pp0_it1) & ap_sig_102) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_112)) & ~(1'b0 == exitcond_fu_151_p2) & ~(1'b1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_st6_fsm_3;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end
        end
        ap_ST_st6_fsm_3 : begin
            ap_NS_fsm = ap_ST_st2_fsm_1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    ap_sig_102 = (((exitcond_reg_292 == 1'b0) & (img_in0_data_stream_0_V_V_empty_n == 1'b0)) | ((exitcond_reg_292 == 1'b0) & (img_in0_data_stream_1_V_V_empty_n == 1'b0)) | ((exitcond_reg_292 == 1'b0) & (img_in0_data_stream_2_V_V_empty_n == 1'b0)));
end

always @ (*) begin
    ap_sig_112 = (((1'b0 == ap_reg_ppstg_exitcond_reg_292_pp0_iter1) & (img_out_data_stream_0_V_full_n == 1'b0)) | ((1'b0 == ap_reg_ppstg_exitcond_reg_292_pp0_iter1) & (img_out_data_stream_1_V_full_n == 1'b0)) | ((1'b0 == ap_reg_ppstg_exitcond_reg_292_pp0_iter1) & (img_out_data_stream_2_V_full_n == 1'b0)));
end

always @ (*) begin
    ap_sig_142 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_sig_150 = (1'b1 == ap_CS_fsm[ap_const_lv32_3]);
end

always @ (*) begin
    ap_sig_22 = (ap_CS_fsm[ap_const_lv32_0] == 1'b1);
end

always @ (*) begin
    ap_sig_59 = (1'b1 == ap_CS_fsm[ap_const_lv32_2]);
end

always @ (*) begin
    ap_sig_89 = (1'b1 == ap_CS_fsm[ap_const_lv32_1]);
end

assign col_1_fu_157_p2 = (col_reg_128 + ap_const_lv10_1);

assign exitcond2_fu_139_p2 = ((row_reg_117 == ap_const_lv9_1E0) ? 1'b1 : 1'b0);

assign exitcond_fu_151_p2 = ((col_reg_128 == ap_const_lv10_280) ? 1'b1 : 1'b0);

assign img_out_data_stream_0_V_din = tmp_21_reg_301;

assign img_out_data_stream_1_V_din = tmp_22_reg_306;

assign img_out_data_stream_2_V_din = tmp_23_reg_311;

assign row_1_fu_145_p2 = (row_reg_117 + ap_const_lv9_1);

assign tmp_21_fu_195_p3 = ((tmp_45_fu_189_p2[0:0] === 1'b1) ? tmp_417_s_fu_181_p3 : tmp_43_fu_177_p1);

assign tmp_22_fu_235_p3 = ((tmp_48_fu_229_p2[0:0] === 1'b1) ? tmp_421_s_fu_221_p3 : tmp_47_fu_217_p1);

assign tmp_23_fu_275_p3 = ((tmp_51_fu_269_p2[0:0] === 1'b1) ? tmp_425_s_fu_261_p3 : tmp_50_fu_257_p1);

assign tmp_36_fu_203_p2 = (($signed(img_in0_data_stream_1_V_V_dout) > $signed(10'b11111110)) ? 1'b1 : 1'b0);

assign tmp_37_fu_243_p2 = (($signed(img_in0_data_stream_2_V_V_dout) > $signed(10'b11111110)) ? 1'b1 : 1'b0);

assign tmp_417_s_fu_181_p3 = ((tmp_s_fu_163_p2[0:0] === 1'b1) ? ap_const_lv8_FF : ap_const_lv8_0);

assign tmp_421_s_fu_221_p3 = ((tmp_36_fu_203_p2[0:0] === 1'b1) ? ap_const_lv8_FF : ap_const_lv8_0);

assign tmp_425_s_fu_261_p3 = ((tmp_37_fu_243_p2[0:0] === 1'b1) ? ap_const_lv8_FF : ap_const_lv8_0);

assign tmp_42_fu_169_p3 = img_in0_data_stream_0_V_V_dout[ap_const_lv32_9];

assign tmp_43_fu_177_p1 = img_in0_data_stream_0_V_V_dout[7:0];

assign tmp_45_fu_189_p2 = (tmp_s_fu_163_p2 | tmp_42_fu_169_p3);

assign tmp_46_fu_209_p3 = img_in0_data_stream_1_V_V_dout[ap_const_lv32_9];

assign tmp_47_fu_217_p1 = img_in0_data_stream_1_V_V_dout[7:0];

assign tmp_48_fu_229_p2 = (tmp_36_fu_203_p2 | tmp_46_fu_209_p3);

assign tmp_49_fu_249_p3 = img_in0_data_stream_2_V_V_dout[ap_const_lv32_9];

assign tmp_50_fu_257_p1 = img_in0_data_stream_2_V_V_dout[7:0];

assign tmp_51_fu_269_p2 = (tmp_37_fu_243_p2 | tmp_49_fu_249_p3);

assign tmp_s_fu_163_p2 = (($signed(img_in0_data_stream_0_V_V_dout) > $signed(10'b11111110)) ? 1'b1 : 1'b0);

endmodule //pynq_filters_convertToUnsigned
