// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module split_ip_Filter2D (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_src_data_stream_0_V_dout,
        p_src_data_stream_0_V_empty_n,
        p_src_data_stream_0_V_read,
        p_src_data_stream_1_V_dout,
        p_src_data_stream_1_V_empty_n,
        p_src_data_stream_1_V_read,
        p_src_data_stream_2_V_dout,
        p_src_data_stream_2_V_empty_n,
        p_src_data_stream_2_V_read,
        p_dst_data_stream_0_V_din,
        p_dst_data_stream_0_V_full_n,
        p_dst_data_stream_0_V_write,
        p_dst_data_stream_1_V_din,
        p_dst_data_stream_1_V_full_n,
        p_dst_data_stream_1_V_write,
        p_dst_data_stream_2_V_din,
        p_dst_data_stream_2_V_full_n,
        p_dst_data_stream_2_V_write,
        p_kernel_val_0_V_1_read,
        p_kernel_val_0_V_2_read,
        p_kernel_val_1_V_0_read,
        p_kernel_val_1_V_2_read,
        p_kernel_val_2_V_0_read,
        p_kernel_val_2_V_1_read
);

parameter    ap_ST_st1_fsm_0 = 5'b1;
parameter    ap_ST_st2_fsm_1 = 5'b10;
parameter    ap_ST_st3_fsm_2 = 5'b100;
parameter    ap_ST_pp0_stg0_fsm_3 = 5'b1000;
parameter    ap_ST_st10_fsm_4 = 5'b10000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv11_0 = 11'b00000000000;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv2_1 = 2'b1;
parameter    ap_const_lv2_2 = 2'b10;
parameter    ap_const_lv11_43A = 11'b10000111010;
parameter    ap_const_lv11_1 = 11'b1;
parameter    ap_const_lv11_438 = 11'b10000111000;
parameter    ap_const_lv11_437 = 11'b10000110111;
parameter    ap_const_lv32_A = 32'b1010;
parameter    ap_const_lv10_0 = 10'b0000000000;
parameter    ap_const_lv12_FFF = 12'b111111111111;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv12_438 = 12'b10000111000;
parameter    ap_const_lv12_1 = 12'b1;
parameter    ap_const_lv12_86E = 12'b100001101110;
parameter    ap_const_lv12_FFE = 12'b111111111110;
parameter    ap_const_lv12_FFD = 12'b111111111101;
parameter    ap_const_lv2_3 = 2'b11;
parameter    ap_const_lv11_782 = 11'b11110000010;
parameter    ap_const_lv12_780 = 12'b11110000000;
parameter    ap_const_lv13_EFE = 13'b111011111110;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv9_0 = 9'b000000000;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv4_0 = 4'b0000;
parameter    ap_const_lv8_FF = 8'b11111111;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] p_src_data_stream_0_V_dout;
input   p_src_data_stream_0_V_empty_n;
output   p_src_data_stream_0_V_read;
input  [7:0] p_src_data_stream_1_V_dout;
input   p_src_data_stream_1_V_empty_n;
output   p_src_data_stream_1_V_read;
input  [7:0] p_src_data_stream_2_V_dout;
input   p_src_data_stream_2_V_empty_n;
output   p_src_data_stream_2_V_read;
output  [7:0] p_dst_data_stream_0_V_din;
input   p_dst_data_stream_0_V_full_n;
output   p_dst_data_stream_0_V_write;
output  [7:0] p_dst_data_stream_1_V_din;
input   p_dst_data_stream_1_V_full_n;
output   p_dst_data_stream_1_V_write;
output  [7:0] p_dst_data_stream_2_V_din;
input   p_dst_data_stream_2_V_full_n;
output   p_dst_data_stream_2_V_write;
input  [2:0] p_kernel_val_0_V_1_read;
input  [1:0] p_kernel_val_0_V_2_read;
input  [1:0] p_kernel_val_1_V_0_read;
input  [2:0] p_kernel_val_1_V_2_read;
input  [1:0] p_kernel_val_2_V_0_read;
input  [3:0] p_kernel_val_2_V_1_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_src_data_stream_0_V_read;
reg p_src_data_stream_1_V_read;
reg p_src_data_stream_2_V_read;
reg p_dst_data_stream_0_V_write;
reg p_dst_data_stream_1_V_write;
reg p_dst_data_stream_2_V_write;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_22;
reg    p_src_data_stream_0_V_blk_n;
reg    ap_reg_ppiten_pp0_it2;
reg    ap_reg_ppiten_pp0_it0;
reg    ap_reg_ppiten_pp0_it1;
reg    ap_reg_ppiten_pp0_it3;
reg    ap_reg_ppiten_pp0_it4;
reg    ap_reg_ppiten_pp0_it5;
reg   [0:0] exitcond_reg_2628;
reg   [0:0] ap_reg_ppstg_exitcond_reg_2628_pp0_iter1;
reg   [0:0] or_cond_i_i_reg_2637;
reg   [0:0] ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1;
reg   [0:0] icmp_reg_2577;
reg   [0:0] tmp_8_reg_2568;
reg    p_src_data_stream_1_V_blk_n;
reg    p_src_data_stream_2_V_blk_n;
reg    p_dst_data_stream_0_V_blk_n;
reg   [0:0] or_cond_i_reg_2664;
reg   [0:0] ap_reg_ppstg_or_cond_i_reg_2664_pp0_iter4;
reg    p_dst_data_stream_1_V_blk_n;
reg    p_dst_data_stream_2_V_blk_n;
reg   [10:0] p_027_0_i_reg_560;
wire   [1:0] tmp_6_fu_571_p2;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_125;
wire  signed [10:0] OP2_V_0_0_1_cast_fu_583_p1;
reg  signed [10:0] OP2_V_0_0_1_cast_reg_2517;
wire   [0:0] tmp_7_fu_577_p2;
wire  signed [9:0] OP2_V_0_0_2_cast_fu_586_p1;
reg  signed [9:0] OP2_V_0_0_2_cast_reg_2524;
wire  signed [9:0] OP2_V_0_1_cast_fu_589_p1;
reg  signed [9:0] OP2_V_0_1_cast_reg_2531;
wire   [10:0] OP2_V_0_1_2_cast_fu_592_p1;
reg   [10:0] OP2_V_0_1_2_cast_reg_2538;
wire  signed [9:0] OP2_V_0_2_cast_fu_595_p1;
reg  signed [9:0] OP2_V_0_2_cast_reg_2545;
wire   [9:0] tmp_s_fu_598_p1;
reg   [9:0] tmp_s_reg_2552;
wire   [0:0] exitcond1_fu_605_p2;
reg    ap_sig_cseq_ST_st3_fsm_2;
reg    ap_sig_150;
wire   [10:0] i_V_fu_611_p2;
reg   [10:0] i_V_reg_2563;
wire   [0:0] tmp_8_fu_617_p2;
wire   [0:0] tmp_82_not_fu_623_p2;
reg   [0:0] tmp_82_not_reg_2572;
wire   [0:0] icmp_fu_639_p2;
wire   [0:0] tmp_2_fu_645_p2;
reg   [0:0] tmp_2_reg_2582;
wire   [0:0] tmp_128_0_1_fu_651_p2;
reg   [0:0] tmp_128_0_1_reg_2586;
wire   [0:0] tmp_3_fu_657_p2;
reg   [0:0] tmp_3_reg_2590;
wire   [1:0] row_assign_s_fu_813_p2;
reg   [1:0] row_assign_s_reg_2603;
wire   [1:0] row_assign_10_0_1_t_fu_845_p2;
reg   [1:0] row_assign_10_0_1_t_reg_2608;
wire   [1:0] row_assign_10_0_2_t_fu_877_p2;
reg   [1:0] row_assign_10_0_2_t_reg_2615;
wire   [1:0] row_assign_10_1_0_t_fu_913_p2;
reg   [1:0] row_assign_10_1_0_t_reg_2622;
wire   [0:0] exitcond_fu_923_p2;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_3;
reg    ap_sig_180;
reg    ap_sig_196;
reg    ap_sig_206;
reg   [0:0] ap_reg_ppstg_exitcond_reg_2628_pp0_iter2;
reg   [0:0] ap_reg_ppstg_exitcond_reg_2628_pp0_iter3;
wire   [10:0] j_V_fu_929_p2;
wire   [0:0] or_cond_i_i_fu_981_p2;
wire   [13:0] x_fu_1059_p3;
reg   [13:0] x_reg_2641;
wire   [1:0] tmp_75_fu_1067_p1;
reg   [1:0] tmp_75_reg_2646;
reg   [1:0] ap_reg_ppstg_tmp_75_reg_2646_pp0_iter1;
wire   [0:0] brmerge_fu_1071_p2;
reg   [0:0] brmerge_reg_2651;
reg   [0:0] ap_reg_ppstg_brmerge_reg_2651_pp0_iter1;
wire   [0:0] or_cond_i_fu_1076_p2;
reg   [0:0] ap_reg_ppstg_or_cond_i_reg_2664_pp0_iter1;
reg   [0:0] ap_reg_ppstg_or_cond_i_reg_2664_pp0_iter2;
reg   [0:0] ap_reg_ppstg_or_cond_i_reg_2664_pp0_iter3;
reg   [10:0] k_buf_0_val_3_addr_reg_2668;
reg   [10:0] k_buf_0_val_4_addr_reg_2674;
reg   [10:0] k_buf_0_val_5_addr_reg_2680;
reg   [10:0] k_buf_1_val_3_addr_reg_2686;
reg   [10:0] k_buf_1_val_4_addr_reg_2692;
reg   [10:0] k_buf_1_val_5_addr_reg_2698;
reg   [10:0] k_buf_2_val_3_addr_reg_2704;
reg   [10:0] k_buf_2_val_4_addr_reg_2710;
reg   [10:0] k_buf_2_val_5_addr_reg_2716;
wire   [7:0] src_kernel_win_0_val_0_0_fu_1236_p3;
reg   [7:0] src_kernel_win_0_val_0_0_reg_2722;
wire   [7:0] src_kernel_win_0_val_1_0_fu_1254_p3;
reg   [7:0] src_kernel_win_0_val_1_0_reg_2728;
reg   [7:0] ap_reg_ppstg_src_kernel_win_0_val_1_0_reg_2728_pp0_iter3;
wire   [7:0] src_kernel_win_0_val_2_0_fu_1272_p3;
reg   [7:0] src_kernel_win_0_val_2_0_reg_2734;
wire   [7:0] src_kernel_win_1_val_0_0_fu_1404_p3;
reg   [7:0] src_kernel_win_1_val_0_0_reg_2740;
wire   [7:0] src_kernel_win_1_val_1_0_fu_1422_p3;
reg   [7:0] src_kernel_win_1_val_1_0_reg_2746;
reg   [7:0] ap_reg_ppstg_src_kernel_win_1_val_1_0_reg_2746_pp0_iter3;
wire   [7:0] src_kernel_win_1_val_2_0_fu_1440_p3;
reg   [7:0] src_kernel_win_1_val_2_0_reg_2752;
wire   [7:0] src_kernel_win_2_val_0_0_fu_1554_p3;
reg   [7:0] src_kernel_win_2_val_0_0_reg_2758;
wire   [7:0] src_kernel_win_2_val_1_0_fu_1572_p3;
reg   [7:0] src_kernel_win_2_val_1_0_reg_2764;
reg   [7:0] ap_reg_ppstg_src_kernel_win_2_val_1_0_reg_2764_pp0_iter3;
wire   [7:0] src_kernel_win_2_val_2_0_fu_1590_p3;
reg   [7:0] src_kernel_win_2_val_2_0_reg_2770;
wire  signed [10:0] grp_fu_2177_p3;
reg  signed [10:0] p_Val2_5_0_0_2_reg_2776;
wire   [9:0] p_Val2_0_2_fu_1637_p2;
reg  signed [9:0] p_Val2_0_2_reg_2781;
wire   [9:0] grp_fu_2170_p3;
reg   [9:0] tmp3_reg_2786;
wire  signed [10:0] grp_fu_2184_p3;
reg  signed [10:0] p_Val2_5_1_0_2_reg_2791;
wire   [9:0] p_Val2_1_2_fu_1689_p2;
reg  signed [9:0] p_Val2_1_2_reg_2796;
wire   [9:0] grp_fu_2163_p3;
reg   [9:0] tmp7_reg_2801;
wire  signed [10:0] grp_fu_2207_p3;
reg  signed [10:0] p_Val2_5_2_0_2_reg_2806;
wire   [9:0] p_Val2_2_2_fu_1741_p2;
reg  signed [9:0] p_Val2_2_2_reg_2811;
wire   [9:0] grp_fu_2140_p3;
reg   [9:0] tmp11_reg_2816;
wire   [11:0] p_Val2_3_fu_1853_p2;
reg   [11:0] p_Val2_3_reg_2821;
reg   [0:0] isneg_reg_2826;
wire   [0:0] not_i_i_i_fu_1877_p2;
reg   [0:0] not_i_i_i_reg_2832;
wire   [11:0] p_Val2_6_fu_1911_p2;
reg   [11:0] p_Val2_6_reg_2837;
reg   [0:0] isneg_1_reg_2842;
wire   [0:0] not_i_i_i5_fu_1935_p2;
reg   [0:0] not_i_i_i5_reg_2848;
wire   [11:0] p_Val2_s_52_fu_1969_p2;
reg   [11:0] p_Val2_s_52_reg_2853;
reg   [0:0] isneg_2_reg_2858;
wire   [0:0] not_i_i_i1_fu_1993_p2;
reg   [0:0] not_i_i_i1_reg_2864;
wire   [10:0] k_buf_0_val_3_address0;
reg    k_buf_0_val_3_ce0;
wire   [7:0] k_buf_0_val_3_q0;
reg    k_buf_0_val_3_ce1;
reg    k_buf_0_val_3_we1;
wire   [10:0] k_buf_0_val_4_address0;
reg    k_buf_0_val_4_ce0;
wire   [7:0] k_buf_0_val_4_q0;
reg    k_buf_0_val_4_ce1;
reg    k_buf_0_val_4_we1;
reg   [7:0] k_buf_0_val_4_d1;
wire   [10:0] k_buf_0_val_5_address0;
reg    k_buf_0_val_5_ce0;
wire   [7:0] k_buf_0_val_5_q0;
reg    k_buf_0_val_5_ce1;
reg    k_buf_0_val_5_we1;
reg   [7:0] k_buf_0_val_5_d1;
wire   [10:0] k_buf_1_val_3_address0;
reg    k_buf_1_val_3_ce0;
wire   [7:0] k_buf_1_val_3_q0;
reg    k_buf_1_val_3_ce1;
reg    k_buf_1_val_3_we1;
wire   [10:0] k_buf_1_val_4_address0;
reg    k_buf_1_val_4_ce0;
wire   [7:0] k_buf_1_val_4_q0;
reg    k_buf_1_val_4_ce1;
reg    k_buf_1_val_4_we1;
reg   [7:0] k_buf_1_val_4_d1;
wire   [10:0] k_buf_1_val_5_address0;
reg    k_buf_1_val_5_ce0;
wire   [7:0] k_buf_1_val_5_q0;
reg    k_buf_1_val_5_ce1;
reg    k_buf_1_val_5_we1;
reg   [7:0] k_buf_1_val_5_d1;
wire   [10:0] k_buf_2_val_3_address0;
reg    k_buf_2_val_3_ce0;
wire   [7:0] k_buf_2_val_3_q0;
reg    k_buf_2_val_3_ce1;
reg    k_buf_2_val_3_we1;
wire   [10:0] k_buf_2_val_4_address0;
reg    k_buf_2_val_4_ce0;
wire   [7:0] k_buf_2_val_4_q0;
reg    k_buf_2_val_4_ce1;
reg    k_buf_2_val_4_we1;
reg   [7:0] k_buf_2_val_4_d1;
wire   [10:0] k_buf_2_val_5_address0;
reg    k_buf_2_val_5_ce0;
wire   [7:0] k_buf_2_val_5_q0;
reg    k_buf_2_val_5_ce1;
reg    k_buf_2_val_5_we1;
reg   [7:0] k_buf_2_val_5_d1;
reg   [1:0] tmp_5_reg_538;
reg   [10:0] p_014_0_i_reg_549;
reg    ap_sig_cseq_ST_st10_fsm_4;
reg    ap_sig_444;
wire   [63:0] tmp_23_fu_1084_p1;
reg   [7:0] src_kernel_win_0_val_0_1_fu_178;
reg   [7:0] src_kernel_win_0_val_0_1_1_fu_182;
reg   [7:0] src_kernel_win_0_val_1_1_fu_186;
reg   [7:0] src_kernel_win_0_val_1_1_1_fu_190;
reg   [7:0] src_kernel_win_0_val_2_1_fu_194;
reg   [7:0] src_kernel_win_0_val_2_1_1_fu_198;
reg   [7:0] src_kernel_win_1_val_0_1_fu_202;
reg   [7:0] src_kernel_win_1_val_0_1_1_fu_206;
reg   [7:0] src_kernel_win_1_val_1_1_fu_210;
reg   [7:0] src_kernel_win_1_val_1_1_1_fu_214;
reg   [7:0] src_kernel_win_1_val_2_1_fu_218;
reg   [7:0] src_kernel_win_1_val_2_1_1_fu_222;
reg   [7:0] src_kernel_win_2_val_0_1_fu_226;
reg   [7:0] src_kernel_win_2_val_0_1_1_fu_230;
reg   [7:0] src_kernel_win_2_val_1_1_fu_234;
reg   [7:0] src_kernel_win_2_val_1_1_1_fu_238;
reg   [7:0] src_kernel_win_2_val_2_1_fu_242;
reg   [7:0] src_kernel_win_2_val_2_1_1_fu_246;
reg   [7:0] right_border_buf_0_val_0_1_fu_250;
wire   [7:0] col_buf_0_val_0_0_fu_1141_p3;
reg   [7:0] right_border_buf_0_val_0_1_1_fu_254;
reg   [7:0] right_border_buf_2_val_2_1_fu_258;
reg   [7:0] right_border_buf_0_val_1_1_fu_262;
wire   [7:0] col_buf_0_val_1_0_fu_1160_p3;
reg   [7:0] right_border_buf_0_val_1_1_1_fu_266;
reg   [7:0] right_border_buf_2_val_2_1_1_fu_270;
wire   [7:0] col_buf_2_val_2_0_fu_1506_p3;
reg   [7:0] right_border_buf_0_val_2_1_fu_274;
wire   [7:0] col_buf_0_val_2_0_fu_1179_p3;
reg   [7:0] right_border_buf_0_val_2_1_1_fu_278;
reg   [7:0] right_border_buf_2_val_1_1_fu_282;
reg   [7:0] right_border_buf_1_val_0_1_fu_286;
wire   [7:0] col_buf_1_val_0_0_fu_1309_p3;
reg   [7:0] right_border_buf_1_val_0_1_1_fu_290;
reg   [7:0] right_border_buf_2_val_1_1_1_fu_294;
wire   [7:0] col_buf_2_val_1_0_fu_1487_p3;
reg   [7:0] right_border_buf_1_val_1_1_fu_298;
wire   [7:0] col_buf_1_val_1_0_fu_1328_p3;
reg   [7:0] right_border_buf_1_val_1_1_1_fu_302;
reg   [7:0] right_border_buf_2_val_0_1_fu_306;
reg   [7:0] right_border_buf_1_val_2_1_fu_310;
wire   [7:0] col_buf_1_val_2_0_fu_1347_p3;
reg   [7:0] right_border_buf_1_val_2_1_1_fu_314;
reg   [7:0] right_border_buf_2_val_0_1_1_fu_318;
wire   [7:0] col_buf_2_val_0_0_fu_1468_p3;
wire   [9:0] tmp_15_fu_629_p4;
wire   [11:0] p_014_0_i_cast_fu_601_p1;
wire   [11:0] tmp_4_fu_663_p2;
wire   [0:0] tmp_17_fu_669_p3;
wire   [0:0] tmp_9_fu_683_p2;
wire   [0:0] rev_fu_677_p2;
wire   [0:0] tmp_19_fu_695_p3;
wire   [11:0] p_assign_7_fu_703_p2;
wire   [11:0] p_p2_i424_i_fu_709_p3;
wire   [11:0] p_assign_6_0_1_fu_729_p2;
wire   [11:0] p_assign_6_0_2_fu_755_p2;
wire   [11:0] p_assign_8_fu_723_p2;
wire   [0:0] tmp_10_fu_717_p2;
wire   [1:0] tmp_50_fu_789_p1;
wire   [1:0] tmp_60_fu_793_p1;
wire   [0:0] or_cond_i423_i_fu_689_p2;
wire   [1:0] tmp_48_fu_785_p1;
wire   [1:0] tmp_61_fu_797_p3;
wire   [1:0] tmp_62_fu_805_p3;
wire   [1:0] tmp_24_fu_751_p1;
wire   [0:0] tmp_22_fu_743_p3;
wire   [1:0] tmp_64_fu_823_p2;
wire   [1:0] tmp_63_fu_819_p1;
wire   [0:0] tmp_20_fu_735_p3;
wire   [1:0] tmp_65_fu_829_p3;
wire   [1:0] tmp_11_fu_837_p3;
wire   [1:0] tmp_37_fu_777_p1;
wire   [0:0] tmp_35_fu_769_p3;
wire   [1:0] tmp_67_fu_855_p2;
wire   [1:0] tmp_66_fu_851_p1;
wire   [0:0] tmp_30_fu_761_p3;
wire   [1:0] tmp_68_fu_861_p3;
wire   [1:0] tmp_12_fu_869_p3;
wire   [1:0] tmp_41_fu_781_p1;
wire   [1:0] tmp_70_fu_887_p1;
wire   [1:0] tmp_71_fu_891_p2;
wire   [1:0] tmp_69_fu_883_p1;
wire   [1:0] tmp_13_fu_897_p3;
wire   [1:0] tmp_14_fu_905_p3;
wire   [9:0] tmp_72_fu_935_p4;
wire   [11:0] p_027_0_i_cast_fu_919_p1;
wire   [11:0] ImagLoc_x_fu_951_p2;
wire   [0:0] tmp_73_fu_961_p3;
wire   [0:0] tmp_18_fu_975_p2;
wire   [0:0] rev1_fu_969_p2;
wire   [0:0] tmp_74_fu_987_p3;
wire   [11:0] p_assign_1_fu_995_p2;
wire   [11:0] p_p2_i_i_fu_1001_p3;
wire  signed [12:0] p_p2_i_i_cast_cast_fu_1013_p1;
wire   [12:0] p_assign_2_fu_1023_p2;
wire  signed [13:0] ImagLoc_x_cast_fu_957_p1;
wire   [13:0] p_assign_2_cast_fu_1029_p1;
wire   [0:0] tmp_21_not_fu_1041_p2;
wire   [0:0] tmp_21_fu_1017_p2;
wire   [0:0] sel_tmp1_fu_1047_p2;
wire   [0:0] sel_tmp2_fu_1053_p2;
wire  signed [13:0] p_p2_i_i_cast_fu_1009_p1;
wire   [13:0] sel_tmp_fu_1033_p3;
wire   [0:0] icmp1_fu_945_p2;
wire  signed [31:0] x_cast_fu_1081_p1;
wire   [1:0] col_assign_3_0_t_fu_1124_p2;
wire   [7:0] tmp_25_fu_1129_p5;
wire   [7:0] tmp_26_fu_1148_p5;
wire   [7:0] tmp_27_fu_1167_p5;
wire   [7:0] tmp_28_fu_1225_p5;
wire   [7:0] tmp_29_fu_1243_p5;
wire   [7:0] tmp_31_fu_1261_p5;
wire   [7:0] tmp_34_fu_1297_p5;
wire   [7:0] tmp_36_fu_1316_p5;
wire   [7:0] tmp_38_fu_1335_p5;
wire   [7:0] tmp_39_fu_1393_p5;
wire   [7:0] tmp_40_fu_1411_p5;
wire   [7:0] tmp_42_fu_1429_p5;
wire   [7:0] tmp_45_fu_1456_p5;
wire   [7:0] tmp_46_fu_1475_p5;
wire   [7:0] tmp_47_fu_1494_p5;
wire   [7:0] tmp_49_fu_1543_p5;
wire   [7:0] tmp_51_fu_1561_p5;
wire   [7:0] tmp_52_fu_1579_p5;
wire   [8:0] OP1_V_0_0_cast_fu_1609_p1;
wire  signed [8:0] p_Val2_1_fu_1613_p2;
wire  signed [9:0] grp_fu_2236_p3;
wire  signed [1:0] p_Val2_0_2_fu_1637_p0;
wire   [7:0] p_Val2_0_2_fu_1637_p1;
wire   [8:0] OP1_V_1_0_cast_fu_1661_p1;
wire  signed [8:0] p_Val2_s_fu_1665_p2;
wire  signed [9:0] grp_fu_2199_p3;
wire  signed [1:0] p_Val2_1_2_fu_1689_p0;
wire   [7:0] p_Val2_1_2_fu_1689_p1;
wire   [8:0] OP1_V_2_0_cast_fu_1713_p1;
wire  signed [8:0] p_Val2_2_fu_1717_p2;
wire  signed [9:0] grp_fu_2228_p3;
wire  signed [1:0] p_Val2_2_2_fu_1741_p0;
wire   [7:0] p_Val2_2_2_fu_1741_p1;
wire  signed [10:0] grp_fu_2214_p3;
wire  signed [10:0] grp_fu_2191_p3;
wire  signed [11:0] tmp1_cast_fu_1838_p1;
wire  signed [11:0] tmp2_cast_fu_1841_p1;
wire   [11:0] p_Val2_5_0_2_fu_1844_p2;
wire   [11:0] tmp3_cast_fu_1850_p1;
wire   [3:0] tmp_33_fu_1867_p4;
wire  signed [10:0] grp_fu_2221_p3;
wire  signed [10:0] grp_fu_2155_p3;
wire  signed [11:0] tmp5_cast_fu_1896_p1;
wire  signed [11:0] tmp6_cast_fu_1899_p1;
wire   [11:0] p_Val2_5_1_2_fu_1902_p2;
wire   [11:0] tmp7_cast_fu_1908_p1;
wire   [3:0] tmp_44_fu_1925_p4;
wire  signed [10:0] grp_fu_2244_p3;
wire  signed [10:0] grp_fu_2147_p3;
wire  signed [11:0] tmp9_cast_fu_1954_p1;
wire  signed [11:0] tmp10_cast_fu_1957_p1;
wire   [11:0] p_Val2_5_2_2_fu_1960_p2;
wire   [11:0] tmp11_cast_fu_1966_p1;
wire   [3:0] tmp_54_fu_1983_p4;
wire   [0:0] tmp_3_i_i_fu_2038_p2;
wire   [0:0] overflow_fu_2043_p2;
wire   [0:0] tmp_i_i_fu_2056_p2;
wire   [7:0] p_mux_i_i_cast_fu_2048_p3;
wire   [7:0] p_Val2_4_fu_2035_p1;
wire   [0:0] tmp_3_i_i4_fu_2073_p2;
wire   [0:0] overflow_1_fu_2078_p2;
wire   [0:0] tmp_i_i8_fu_2091_p2;
wire   [7:0] p_mux_i_i7_cast_fu_2083_p3;
wire   [7:0] p_Val2_7_fu_2070_p1;
wire   [0:0] tmp_3_i_i1_fu_2108_p2;
wire   [0:0] overflow_2_fu_2113_p2;
wire   [0:0] tmp_i_i1_fu_2126_p2;
wire   [7:0] p_mux_i_i16_cast_fu_2118_p3;
wire   [7:0] p_Val2_8_fu_2105_p1;
wire   [3:0] grp_fu_2140_p0;
wire   [7:0] grp_fu_2140_p1;
wire   [7:0] grp_fu_2140_p2;
wire  signed [1:0] grp_fu_2147_p0;
wire   [7:0] grp_fu_2147_p1;
wire  signed [1:0] grp_fu_2155_p0;
wire   [7:0] grp_fu_2155_p1;
wire   [3:0] grp_fu_2163_p0;
wire   [7:0] grp_fu_2163_p1;
wire   [7:0] grp_fu_2163_p2;
wire   [3:0] grp_fu_2170_p0;
wire   [7:0] grp_fu_2170_p1;
wire   [7:0] grp_fu_2170_p2;
wire  signed [2:0] grp_fu_2177_p0;
wire   [7:0] grp_fu_2177_p1;
wire  signed [2:0] grp_fu_2184_p0;
wire   [7:0] grp_fu_2184_p1;
wire  signed [1:0] grp_fu_2191_p0;
wire   [7:0] grp_fu_2191_p1;
wire  signed [1:0] grp_fu_2199_p0;
wire   [7:0] grp_fu_2199_p1;
wire  signed [2:0] grp_fu_2207_p0;
wire   [7:0] grp_fu_2207_p1;
wire   [2:0] grp_fu_2214_p0;
wire   [7:0] grp_fu_2214_p1;
wire   [2:0] grp_fu_2221_p0;
wire   [7:0] grp_fu_2221_p1;
wire  signed [1:0] grp_fu_2228_p0;
wire   [7:0] grp_fu_2228_p1;
wire  signed [1:0] grp_fu_2236_p0;
wire   [7:0] grp_fu_2236_p1;
wire   [2:0] grp_fu_2244_p0;
wire   [7:0] grp_fu_2244_p1;
reg   [4:0] ap_NS_fsm;
wire   [9:0] grp_fu_2140_p10;
wire   [9:0] grp_fu_2140_p20;
wire   [9:0] grp_fu_2147_p10;
wire   [9:0] grp_fu_2155_p10;
wire   [9:0] grp_fu_2163_p10;
wire   [9:0] grp_fu_2163_p20;
wire   [9:0] grp_fu_2170_p10;
wire   [9:0] grp_fu_2170_p20;
wire   [10:0] grp_fu_2177_p10;
wire   [10:0] grp_fu_2184_p10;
wire   [9:0] grp_fu_2191_p10;
wire   [9:0] grp_fu_2199_p10;
wire   [10:0] grp_fu_2207_p10;
wire   [10:0] grp_fu_2214_p10;
wire   [10:0] grp_fu_2221_p10;
wire   [9:0] grp_fu_2228_p10;
wire   [9:0] grp_fu_2236_p10;
wire   [10:0] grp_fu_2244_p10;
wire   [9:0] p_Val2_0_2_fu_1637_p10;
wire   [9:0] p_Val2_1_2_fu_1689_p10;
wire   [9:0] p_Val2_2_2_fu_1741_p10;
reg    ap_sig_1618;
reg    ap_sig_1620;
reg    ap_sig_1617;
reg    ap_sig_1623;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'b1;
#0 ap_reg_ppiten_pp0_it2 = 1'b0;
#0 ap_reg_ppiten_pp0_it0 = 1'b0;
#0 ap_reg_ppiten_pp0_it1 = 1'b0;
#0 ap_reg_ppiten_pp0_it3 = 1'b0;
#0 ap_reg_ppiten_pp0_it4 = 1'b0;
#0 ap_reg_ppiten_pp0_it5 = 1'b0;
end

split_ip_Filter2D_k_buf_0_val_3 #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_3_address0),
    .ce0(k_buf_0_val_3_ce0),
    .q0(k_buf_0_val_3_q0),
    .address1(k_buf_0_val_3_addr_reg_2668),
    .ce1(k_buf_0_val_3_ce1),
    .we1(k_buf_0_val_3_we1),
    .d1(p_src_data_stream_0_V_dout)
);

split_ip_Filter2D_k_buf_0_val_3 #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_4_address0),
    .ce0(k_buf_0_val_4_ce0),
    .q0(k_buf_0_val_4_q0),
    .address1(k_buf_0_val_4_addr_reg_2674),
    .ce1(k_buf_0_val_4_ce1),
    .we1(k_buf_0_val_4_we1),
    .d1(k_buf_0_val_4_d1)
);

split_ip_Filter2D_k_buf_0_val_3 #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_5_address0),
    .ce0(k_buf_0_val_5_ce0),
    .q0(k_buf_0_val_5_q0),
    .address1(k_buf_0_val_5_addr_reg_2680),
    .ce1(k_buf_0_val_5_ce1),
    .we1(k_buf_0_val_5_we1),
    .d1(k_buf_0_val_5_d1)
);

split_ip_Filter2D_k_buf_0_val_3 #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_1_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_1_val_3_address0),
    .ce0(k_buf_1_val_3_ce0),
    .q0(k_buf_1_val_3_q0),
    .address1(k_buf_1_val_3_addr_reg_2686),
    .ce1(k_buf_1_val_3_ce1),
    .we1(k_buf_1_val_3_we1),
    .d1(p_src_data_stream_1_V_dout)
);

split_ip_Filter2D_k_buf_0_val_3 #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_1_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_1_val_4_address0),
    .ce0(k_buf_1_val_4_ce0),
    .q0(k_buf_1_val_4_q0),
    .address1(k_buf_1_val_4_addr_reg_2692),
    .ce1(k_buf_1_val_4_ce1),
    .we1(k_buf_1_val_4_we1),
    .d1(k_buf_1_val_4_d1)
);

split_ip_Filter2D_k_buf_0_val_3 #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_1_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_1_val_5_address0),
    .ce0(k_buf_1_val_5_ce0),
    .q0(k_buf_1_val_5_q0),
    .address1(k_buf_1_val_5_addr_reg_2698),
    .ce1(k_buf_1_val_5_ce1),
    .we1(k_buf_1_val_5_we1),
    .d1(k_buf_1_val_5_d1)
);

split_ip_Filter2D_k_buf_0_val_3 #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_2_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_2_val_3_address0),
    .ce0(k_buf_2_val_3_ce0),
    .q0(k_buf_2_val_3_q0),
    .address1(k_buf_2_val_3_addr_reg_2704),
    .ce1(k_buf_2_val_3_ce1),
    .we1(k_buf_2_val_3_we1),
    .d1(p_src_data_stream_2_V_dout)
);

split_ip_Filter2D_k_buf_0_val_3 #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_2_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_2_val_4_address0),
    .ce0(k_buf_2_val_4_ce0),
    .q0(k_buf_2_val_4_q0),
    .address1(k_buf_2_val_4_addr_reg_2710),
    .ce1(k_buf_2_val_4_ce1),
    .we1(k_buf_2_val_4_we1),
    .d1(k_buf_2_val_4_d1)
);

split_ip_Filter2D_k_buf_0_val_3 #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_2_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_2_val_5_address0),
    .ce0(k_buf_2_val_5_ce0),
    .q0(k_buf_2_val_5_q0),
    .address1(k_buf_2_val_5_addr_reg_2716),
    .ce1(k_buf_2_val_5_ce1),
    .we1(k_buf_2_val_5_we1),
    .d1(k_buf_2_val_5_d1)
);

split_ip_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
split_ip_mux_3to1_sel2_8_1_U20(
    .din1(right_border_buf_0_val_0_1_fu_250),
    .din2(right_border_buf_0_val_0_1_1_fu_254),
    .din3(ap_const_lv8_0),
    .din4(col_assign_3_0_t_fu_1124_p2),
    .dout(tmp_25_fu_1129_p5)
);

split_ip_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
split_ip_mux_3to1_sel2_8_1_U21(
    .din1(right_border_buf_0_val_1_1_fu_262),
    .din2(right_border_buf_0_val_1_1_1_fu_266),
    .din3(ap_const_lv8_0),
    .din4(col_assign_3_0_t_fu_1124_p2),
    .dout(tmp_26_fu_1148_p5)
);

split_ip_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
split_ip_mux_3to1_sel2_8_1_U22(
    .din1(right_border_buf_0_val_2_1_fu_274),
    .din2(right_border_buf_0_val_2_1_1_fu_278),
    .din3(ap_const_lv8_0),
    .din4(col_assign_3_0_t_fu_1124_p2),
    .dout(tmp_27_fu_1167_p5)
);

split_ip_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
split_ip_mux_3to1_sel2_8_1_U23(
    .din1(col_buf_0_val_0_0_fu_1141_p3),
    .din2(col_buf_0_val_1_0_fu_1160_p3),
    .din3(col_buf_0_val_2_0_fu_1179_p3),
    .din4(row_assign_s_reg_2603),
    .dout(tmp_28_fu_1225_p5)
);

split_ip_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
split_ip_mux_3to1_sel2_8_1_U24(
    .din1(col_buf_0_val_0_0_fu_1141_p3),
    .din2(col_buf_0_val_1_0_fu_1160_p3),
    .din3(col_buf_0_val_2_0_fu_1179_p3),
    .din4(row_assign_10_0_1_t_reg_2608),
    .dout(tmp_29_fu_1243_p5)
);

split_ip_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
split_ip_mux_3to1_sel2_8_1_U25(
    .din1(col_buf_0_val_0_0_fu_1141_p3),
    .din2(col_buf_0_val_1_0_fu_1160_p3),
    .din3(col_buf_0_val_2_0_fu_1179_p3),
    .din4(row_assign_10_0_2_t_reg_2615),
    .dout(tmp_31_fu_1261_p5)
);

split_ip_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
split_ip_mux_3to1_sel2_8_1_U26(
    .din1(right_border_buf_1_val_0_1_fu_286),
    .din2(right_border_buf_1_val_0_1_1_fu_290),
    .din3(ap_const_lv8_0),
    .din4(col_assign_3_0_t_fu_1124_p2),
    .dout(tmp_34_fu_1297_p5)
);

split_ip_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
split_ip_mux_3to1_sel2_8_1_U27(
    .din1(right_border_buf_1_val_1_1_fu_298),
    .din2(right_border_buf_1_val_1_1_1_fu_302),
    .din3(ap_const_lv8_0),
    .din4(col_assign_3_0_t_fu_1124_p2),
    .dout(tmp_36_fu_1316_p5)
);

split_ip_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
split_ip_mux_3to1_sel2_8_1_U28(
    .din1(right_border_buf_1_val_2_1_fu_310),
    .din2(right_border_buf_1_val_2_1_1_fu_314),
    .din3(ap_const_lv8_0),
    .din4(col_assign_3_0_t_fu_1124_p2),
    .dout(tmp_38_fu_1335_p5)
);

split_ip_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
split_ip_mux_3to1_sel2_8_1_U29(
    .din1(col_buf_1_val_0_0_fu_1309_p3),
    .din2(col_buf_1_val_1_0_fu_1328_p3),
    .din3(col_buf_1_val_2_0_fu_1347_p3),
    .din4(row_assign_10_1_0_t_reg_2622),
    .dout(tmp_39_fu_1393_p5)
);

split_ip_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
split_ip_mux_3to1_sel2_8_1_U30(
    .din1(col_buf_1_val_0_0_fu_1309_p3),
    .din2(col_buf_1_val_1_0_fu_1328_p3),
    .din3(col_buf_1_val_2_0_fu_1347_p3),
    .din4(row_assign_10_0_1_t_reg_2608),
    .dout(tmp_40_fu_1411_p5)
);

split_ip_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
split_ip_mux_3to1_sel2_8_1_U31(
    .din1(col_buf_1_val_0_0_fu_1309_p3),
    .din2(col_buf_1_val_1_0_fu_1328_p3),
    .din3(col_buf_1_val_2_0_fu_1347_p3),
    .din4(row_assign_10_0_2_t_reg_2615),
    .dout(tmp_42_fu_1429_p5)
);

split_ip_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
split_ip_mux_3to1_sel2_8_1_U32(
    .din1(right_border_buf_2_val_0_1_1_fu_318),
    .din2(right_border_buf_2_val_0_1_fu_306),
    .din3(ap_const_lv8_0),
    .din4(col_assign_3_0_t_fu_1124_p2),
    .dout(tmp_45_fu_1456_p5)
);

split_ip_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
split_ip_mux_3to1_sel2_8_1_U33(
    .din1(right_border_buf_2_val_1_1_1_fu_294),
    .din2(right_border_buf_2_val_1_1_fu_282),
    .din3(ap_const_lv8_0),
    .din4(col_assign_3_0_t_fu_1124_p2),
    .dout(tmp_46_fu_1475_p5)
);

split_ip_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
split_ip_mux_3to1_sel2_8_1_U34(
    .din1(right_border_buf_2_val_2_1_1_fu_270),
    .din2(right_border_buf_2_val_2_1_fu_258),
    .din3(ap_const_lv8_0),
    .din4(col_assign_3_0_t_fu_1124_p2),
    .dout(tmp_47_fu_1494_p5)
);

split_ip_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
split_ip_mux_3to1_sel2_8_1_U35(
    .din1(col_buf_2_val_0_0_fu_1468_p3),
    .din2(col_buf_2_val_1_0_fu_1487_p3),
    .din3(col_buf_2_val_2_0_fu_1506_p3),
    .din4(row_assign_10_1_0_t_reg_2622),
    .dout(tmp_49_fu_1543_p5)
);

split_ip_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
split_ip_mux_3to1_sel2_8_1_U36(
    .din1(col_buf_2_val_0_0_fu_1468_p3),
    .din2(col_buf_2_val_1_0_fu_1487_p3),
    .din3(col_buf_2_val_2_0_fu_1506_p3),
    .din4(row_assign_10_0_1_t_reg_2608),
    .dout(tmp_51_fu_1561_p5)
);

split_ip_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
split_ip_mux_3to1_sel2_8_1_U37(
    .din1(col_buf_2_val_0_0_fu_1468_p3),
    .din2(col_buf_2_val_1_0_fu_1487_p3),
    .din3(col_buf_2_val_2_0_fu_1506_p3),
    .din4(row_assign_10_0_2_t_reg_2615),
    .dout(tmp_52_fu_1579_p5)
);

split_ip_mac_muladd_4ns_8ns_8ns_10_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .dout_WIDTH( 10 ))
split_ip_mac_muladd_4ns_8ns_8ns_10_1_U38(
    .din0(grp_fu_2140_p0),
    .din1(grp_fu_2140_p1),
    .din2(grp_fu_2140_p2),
    .dout(grp_fu_2140_p3)
);

split_ip_mac_muladd_2s_8ns_10s_11_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 10 ),
    .dout_WIDTH( 11 ))
split_ip_mac_muladd_2s_8ns_10s_11_1_U39(
    .din0(grp_fu_2147_p0),
    .din1(grp_fu_2147_p1),
    .din2(p_Val2_2_2_reg_2811),
    .dout(grp_fu_2147_p3)
);

split_ip_mac_muladd_2s_8ns_10s_11_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 10 ),
    .dout_WIDTH( 11 ))
split_ip_mac_muladd_2s_8ns_10s_11_1_U40(
    .din0(grp_fu_2155_p0),
    .din1(grp_fu_2155_p1),
    .din2(p_Val2_1_2_reg_2796),
    .dout(grp_fu_2155_p3)
);

split_ip_mac_muladd_4ns_8ns_8ns_10_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .dout_WIDTH( 10 ))
split_ip_mac_muladd_4ns_8ns_8ns_10_1_U41(
    .din0(grp_fu_2163_p0),
    .din1(grp_fu_2163_p1),
    .din2(grp_fu_2163_p2),
    .dout(grp_fu_2163_p3)
);

split_ip_mac_muladd_4ns_8ns_8ns_10_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .dout_WIDTH( 10 ))
split_ip_mac_muladd_4ns_8ns_8ns_10_1_U42(
    .din0(grp_fu_2170_p0),
    .din1(grp_fu_2170_p1),
    .din2(grp_fu_2170_p2),
    .dout(grp_fu_2170_p3)
);

split_ip_mac_muladd_3s_8ns_10s_11_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 10 ),
    .dout_WIDTH( 11 ))
split_ip_mac_muladd_3s_8ns_10s_11_1_U43(
    .din0(grp_fu_2177_p0),
    .din1(grp_fu_2177_p1),
    .din2(grp_fu_2236_p3),
    .dout(grp_fu_2177_p3)
);

split_ip_mac_muladd_3s_8ns_10s_11_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 10 ),
    .dout_WIDTH( 11 ))
split_ip_mac_muladd_3s_8ns_10s_11_1_U44(
    .din0(grp_fu_2184_p0),
    .din1(grp_fu_2184_p1),
    .din2(grp_fu_2199_p3),
    .dout(grp_fu_2184_p3)
);

split_ip_mac_muladd_2s_8ns_10s_11_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 10 ),
    .dout_WIDTH( 11 ))
split_ip_mac_muladd_2s_8ns_10s_11_1_U45(
    .din0(grp_fu_2191_p0),
    .din1(grp_fu_2191_p1),
    .din2(p_Val2_0_2_reg_2781),
    .dout(grp_fu_2191_p3)
);

split_ip_mac_muladd_2s_8ns_9s_10_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 9 ),
    .dout_WIDTH( 10 ))
split_ip_mac_muladd_2s_8ns_9s_10_1_U46(
    .din0(grp_fu_2199_p0),
    .din1(grp_fu_2199_p1),
    .din2(p_Val2_s_fu_1665_p2),
    .dout(grp_fu_2199_p3)
);

split_ip_mac_muladd_3s_8ns_10s_11_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 10 ),
    .dout_WIDTH( 11 ))
split_ip_mac_muladd_3s_8ns_10s_11_1_U47(
    .din0(grp_fu_2207_p0),
    .din1(grp_fu_2207_p1),
    .din2(grp_fu_2228_p3),
    .dout(grp_fu_2207_p3)
);

split_ip_mac_muladd_3ns_8ns_11s_11_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 11 ),
    .dout_WIDTH( 11 ))
split_ip_mac_muladd_3ns_8ns_11s_11_1_U48(
    .din0(grp_fu_2214_p0),
    .din1(grp_fu_2214_p1),
    .din2(p_Val2_5_0_0_2_reg_2776),
    .dout(grp_fu_2214_p3)
);

split_ip_mac_muladd_3ns_8ns_11s_11_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 11 ),
    .dout_WIDTH( 11 ))
split_ip_mac_muladd_3ns_8ns_11s_11_1_U49(
    .din0(grp_fu_2221_p0),
    .din1(grp_fu_2221_p1),
    .din2(p_Val2_5_1_0_2_reg_2791),
    .dout(grp_fu_2221_p3)
);

split_ip_mac_muladd_2s_8ns_9s_10_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 9 ),
    .dout_WIDTH( 10 ))
split_ip_mac_muladd_2s_8ns_9s_10_1_U50(
    .din0(grp_fu_2228_p0),
    .din1(grp_fu_2228_p1),
    .din2(p_Val2_2_fu_1717_p2),
    .dout(grp_fu_2228_p3)
);

split_ip_mac_muladd_2s_8ns_9s_10_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 9 ),
    .dout_WIDTH( 10 ))
split_ip_mac_muladd_2s_8ns_9s_10_1_U51(
    .din0(grp_fu_2236_p0),
    .din1(grp_fu_2236_p1),
    .din2(p_Val2_1_fu_1613_p2),
    .dout(grp_fu_2236_p3)
);

split_ip_mac_muladd_3ns_8ns_11s_11_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 11 ),
    .dout_WIDTH( 11 ))
split_ip_mac_muladd_3ns_8ns_11s_11_1_U52(
    .din0(grp_fu_2244_p0),
    .din1(grp_fu_2244_p1),
    .din2(p_Val2_5_2_0_2_reg_2806),
    .dout(grp_fu_2244_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b0 == exitcond_fu_923_p2))) begin
            ap_reg_ppiten_pp0_it0 <= 1'b0;
        end else if (((1'b1 == ap_sig_cseq_ST_st3_fsm_2) & (1'b0 == exitcond1_fu_605_p2))) begin
            ap_reg_ppiten_pp0_it0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)))) begin
            ap_reg_ppiten_pp0_it1 <= ap_reg_ppiten_pp0_it0;
        end else if (((1'b1 == ap_sig_cseq_ST_st3_fsm_2) & (1'b0 == exitcond1_fu_605_p2))) begin
            ap_reg_ppiten_pp0_it1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it3 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) begin
            if (~(1'b1 == ap_reg_ppiten_pp0_it1)) begin
                ap_reg_ppiten_pp0_it3 <= 1'b0;
            end else if ((1'b1 == ap_reg_ppiten_pp0_it1)) begin
                ap_reg_ppiten_pp0_it3 <= ap_reg_ppiten_pp0_it2;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it4 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) begin
            ap_reg_ppiten_pp0_it4 <= ap_reg_ppiten_pp0_it3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it5 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) begin
            ap_reg_ppiten_pp0_it5 <= ap_reg_ppiten_pp0_it4;
        end else if (((1'b1 == ap_sig_cseq_ST_st3_fsm_2) & (1'b0 == exitcond1_fu_605_p2))) begin
            ap_reg_ppiten_pp0_it5 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st10_fsm_4)) begin
        p_014_0_i_reg_549 <= i_V_reg_2563;
    end else if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(1'b0 == tmp_7_fu_577_p2))) begin
        p_014_0_i_reg_549 <= ap_const_lv11_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & (1'b0 == exitcond_fu_923_p2))) begin
        p_027_0_i_reg_560 <= j_V_fu_929_p2;
    end else if (((1'b1 == ap_sig_cseq_ST_st3_fsm_2) & (1'b0 == exitcond1_fu_605_p2))) begin
        p_027_0_i_reg_560 <= ap_const_lv11_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
        tmp_5_reg_538 <= ap_const_lv2_0;
    end else if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (1'b0 == tmp_7_fu_577_p2))) begin
        tmp_5_reg_538 <= tmp_6_fu_571_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(1'b0 == tmp_7_fu_577_p2))) begin
        OP2_V_0_0_1_cast_reg_2517 <= OP2_V_0_0_1_cast_fu_583_p1;
        OP2_V_0_0_2_cast_reg_2524 <= OP2_V_0_0_2_cast_fu_586_p1;
        OP2_V_0_1_2_cast_reg_2538[2 : 0] <= OP2_V_0_1_2_cast_fu_592_p1[2 : 0];
        OP2_V_0_1_cast_reg_2531 <= OP2_V_0_1_cast_fu_589_p1;
        OP2_V_0_2_cast_reg_2545 <= OP2_V_0_2_cast_fu_595_p1;
        tmp_s_reg_2552[3 : 0] <= tmp_s_fu_598_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)))) begin
        ap_reg_ppstg_brmerge_reg_2651_pp0_iter1 <= brmerge_reg_2651;
        ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 <= exitcond_reg_2628;
        ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1 <= or_cond_i_i_reg_2637;
        ap_reg_ppstg_or_cond_i_reg_2664_pp0_iter1 <= or_cond_i_reg_2664;
        ap_reg_ppstg_tmp_75_reg_2646_pp0_iter1 <= tmp_75_reg_2646;
        exitcond_reg_2628 <= exitcond_fu_923_p2;
    end
end

always @ (posedge ap_clk) begin
    if (~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) begin
        ap_reg_ppstg_exitcond_reg_2628_pp0_iter2 <= ap_reg_ppstg_exitcond_reg_2628_pp0_iter1;
        ap_reg_ppstg_exitcond_reg_2628_pp0_iter3 <= ap_reg_ppstg_exitcond_reg_2628_pp0_iter2;
        ap_reg_ppstg_or_cond_i_reg_2664_pp0_iter2 <= ap_reg_ppstg_or_cond_i_reg_2664_pp0_iter1;
        ap_reg_ppstg_or_cond_i_reg_2664_pp0_iter3 <= ap_reg_ppstg_or_cond_i_reg_2664_pp0_iter2;
        ap_reg_ppstg_or_cond_i_reg_2664_pp0_iter4 <= ap_reg_ppstg_or_cond_i_reg_2664_pp0_iter3;
        ap_reg_ppstg_src_kernel_win_0_val_1_0_reg_2728_pp0_iter3 <= src_kernel_win_0_val_1_0_reg_2728;
        ap_reg_ppstg_src_kernel_win_1_val_1_0_reg_2746_pp0_iter3 <= src_kernel_win_1_val_1_0_reg_2746;
        ap_reg_ppstg_src_kernel_win_2_val_1_0_reg_2764_pp0_iter3 <= src_kernel_win_2_val_1_0_reg_2764;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & (1'b0 == exitcond_fu_923_p2))) begin
        brmerge_reg_2651 <= brmerge_fu_1071_p2;
        or_cond_i_i_reg_2637 <= or_cond_i_i_fu_981_p2;
        or_cond_i_reg_2664 <= or_cond_i_fu_1076_p2;
        tmp_75_reg_2646 <= tmp_75_fu_1067_p1;
        x_reg_2641 <= x_fu_1059_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        i_V_reg_2563 <= i_V_fu_611_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st3_fsm_2) & (1'b0 == exitcond1_fu_605_p2))) begin
        icmp_reg_2577 <= icmp_fu_639_p2;
        row_assign_10_0_1_t_reg_2608 <= row_assign_10_0_1_t_fu_845_p2;
        row_assign_10_0_2_t_reg_2615 <= row_assign_10_0_2_t_fu_877_p2;
        row_assign_10_1_0_t_reg_2622 <= row_assign_10_1_0_t_fu_913_p2;
        row_assign_s_reg_2603 <= row_assign_s_fu_813_p2;
        tmp_128_0_1_reg_2586 <= tmp_128_0_1_fu_651_p2;
        tmp_2_reg_2582 <= tmp_2_fu_645_p2;
        tmp_3_reg_2590 <= tmp_3_fu_657_p2;
        tmp_82_not_reg_2572 <= tmp_82_not_fu_623_p2;
        tmp_8_reg_2568 <= tmp_8_fu_617_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b0 == ap_reg_ppstg_or_cond_i_reg_2664_pp0_iter3))) begin
        isneg_1_reg_2842 <= p_Val2_6_fu_1911_p2[ap_const_lv32_B];
        isneg_2_reg_2858 <= p_Val2_s_52_fu_1969_p2[ap_const_lv32_B];
        isneg_reg_2826 <= p_Val2_3_fu_1853_p2[ap_const_lv32_B];
        not_i_i_i1_reg_2864 <= not_i_i_i1_fu_1993_p2;
        not_i_i_i5_reg_2848 <= not_i_i_i5_fu_1935_p2;
        not_i_i_i_reg_2832 <= not_i_i_i_fu_1877_p2;
        p_Val2_3_reg_2821 <= p_Val2_3_fu_1853_p2;
        p_Val2_6_reg_2837 <= p_Val2_6_fu_1911_p2;
        p_Val2_s_52_reg_2853 <= p_Val2_s_52_fu_1969_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & (exitcond_reg_2628 == 1'b0))) begin
        k_buf_0_val_3_addr_reg_2668 <= tmp_23_fu_1084_p1;
        k_buf_0_val_4_addr_reg_2674 <= tmp_23_fu_1084_p1;
        k_buf_0_val_5_addr_reg_2680 <= tmp_23_fu_1084_p1;
        k_buf_1_val_3_addr_reg_2686 <= tmp_23_fu_1084_p1;
        k_buf_1_val_4_addr_reg_2692 <= tmp_23_fu_1084_p1;
        k_buf_1_val_5_addr_reg_2698 <= tmp_23_fu_1084_p1;
        k_buf_2_val_3_addr_reg_2704 <= tmp_23_fu_1084_p1;
        k_buf_2_val_4_addr_reg_2710 <= tmp_23_fu_1084_p1;
        k_buf_2_val_5_addr_reg_2716 <= tmp_23_fu_1084_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b0 == ap_reg_ppstg_or_cond_i_reg_2664_pp0_iter2))) begin
        p_Val2_0_2_reg_2781 <= p_Val2_0_2_fu_1637_p2;
        p_Val2_1_2_reg_2796 <= p_Val2_1_2_fu_1689_p2;
        p_Val2_2_2_reg_2811 <= p_Val2_2_2_fu_1741_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it3) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b0 == ap_reg_ppstg_or_cond_i_reg_2664_pp0_iter2))) begin
        p_Val2_5_0_0_2_reg_2776 <= grp_fu_2177_p3;
        p_Val2_5_1_0_2_reg_2791 <= grp_fu_2184_p3;
        p_Val2_5_2_0_2_reg_2806 <= grp_fu_2207_p3;
        tmp11_reg_2816 <= grp_fu_2140_p3;
        tmp3_reg_2786 <= grp_fu_2170_p3;
        tmp7_reg_2801 <= grp_fu_2163_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & ~(1'b0 == icmp_reg_2577) & ~(1'b0 == tmp_8_reg_2568) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)))) begin
        right_border_buf_0_val_0_1_1_fu_254 <= right_border_buf_0_val_0_1_fu_250;
        right_border_buf_0_val_0_1_fu_250 <= col_buf_0_val_0_0_fu_1141_p3;
        right_border_buf_0_val_1_1_1_fu_266 <= right_border_buf_0_val_1_1_fu_262;
        right_border_buf_0_val_1_1_fu_262 <= col_buf_0_val_1_0_fu_1160_p3;
        right_border_buf_0_val_2_1_1_fu_278 <= right_border_buf_0_val_2_1_fu_274;
        right_border_buf_0_val_2_1_fu_274 <= col_buf_0_val_2_0_fu_1179_p3;
        right_border_buf_1_val_0_1_1_fu_290 <= right_border_buf_1_val_0_1_fu_286;
        right_border_buf_1_val_0_1_fu_286 <= col_buf_1_val_0_0_fu_1309_p3;
        right_border_buf_1_val_1_1_1_fu_302 <= right_border_buf_1_val_1_1_fu_298;
        right_border_buf_1_val_1_1_fu_298 <= col_buf_1_val_1_0_fu_1328_p3;
        right_border_buf_1_val_2_1_1_fu_314 <= right_border_buf_1_val_2_1_fu_310;
        right_border_buf_1_val_2_1_fu_310 <= col_buf_1_val_2_0_fu_1347_p3;
        right_border_buf_2_val_0_1_1_fu_318 <= col_buf_2_val_0_0_fu_1468_p3;
        right_border_buf_2_val_0_1_fu_306 <= right_border_buf_2_val_0_1_1_fu_318;
        right_border_buf_2_val_1_1_1_fu_294 <= col_buf_2_val_1_0_fu_1487_p3;
        right_border_buf_2_val_1_1_fu_282 <= right_border_buf_2_val_1_1_1_fu_294;
        right_border_buf_2_val_2_1_1_fu_270 <= col_buf_2_val_2_0_fu_1506_p3;
        right_border_buf_2_val_2_1_fu_258 <= right_border_buf_2_val_2_1_1_fu_270;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)))) begin
        src_kernel_win_0_val_0_0_reg_2722 <= src_kernel_win_0_val_0_0_fu_1236_p3;
        src_kernel_win_0_val_1_0_reg_2728 <= src_kernel_win_0_val_1_0_fu_1254_p3;
        src_kernel_win_0_val_2_0_reg_2734 <= src_kernel_win_0_val_2_0_fu_1272_p3;
        src_kernel_win_1_val_0_0_reg_2740 <= src_kernel_win_1_val_0_0_fu_1404_p3;
        src_kernel_win_1_val_1_0_reg_2746 <= src_kernel_win_1_val_1_0_fu_1422_p3;
        src_kernel_win_1_val_2_0_reg_2752 <= src_kernel_win_1_val_2_0_fu_1440_p3;
        src_kernel_win_2_val_0_0_reg_2758 <= src_kernel_win_2_val_0_0_fu_1554_p3;
        src_kernel_win_2_val_1_0_reg_2764 <= src_kernel_win_2_val_1_0_fu_1572_p3;
        src_kernel_win_2_val_2_0_reg_2770 <= src_kernel_win_2_val_2_0_fu_1590_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it3) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & (1'b0 == ap_reg_ppstg_exitcond_reg_2628_pp0_iter2))) begin
        src_kernel_win_0_val_0_1_1_fu_182 <= src_kernel_win_0_val_0_1_fu_178;
        src_kernel_win_0_val_0_1_fu_178 <= src_kernel_win_0_val_0_0_reg_2722;
        src_kernel_win_0_val_2_1_1_fu_198 <= src_kernel_win_0_val_2_1_fu_194;
        src_kernel_win_0_val_2_1_fu_194 <= src_kernel_win_0_val_2_0_reg_2734;
        src_kernel_win_1_val_0_1_1_fu_206 <= src_kernel_win_1_val_0_1_fu_202;
        src_kernel_win_1_val_0_1_fu_202 <= src_kernel_win_1_val_0_0_reg_2740;
        src_kernel_win_1_val_2_1_1_fu_222 <= src_kernel_win_1_val_2_1_fu_218;
        src_kernel_win_1_val_2_1_fu_218 <= src_kernel_win_1_val_2_0_reg_2752;
        src_kernel_win_2_val_0_1_1_fu_230 <= src_kernel_win_2_val_0_1_fu_226;
        src_kernel_win_2_val_0_1_fu_226 <= src_kernel_win_2_val_0_0_reg_2758;
        src_kernel_win_2_val_2_1_1_fu_246 <= src_kernel_win_2_val_2_1_fu_242;
        src_kernel_win_2_val_2_1_fu_242 <= src_kernel_win_2_val_2_0_reg_2770;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it4) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & (1'b0 == ap_reg_ppstg_exitcond_reg_2628_pp0_iter3))) begin
        src_kernel_win_0_val_1_1_1_fu_190 <= src_kernel_win_0_val_1_1_fu_186;
        src_kernel_win_0_val_1_1_fu_186 <= ap_reg_ppstg_src_kernel_win_0_val_1_0_reg_2728_pp0_iter3;
        src_kernel_win_1_val_1_1_1_fu_214 <= src_kernel_win_1_val_1_1_fu_210;
        src_kernel_win_1_val_1_1_fu_210 <= ap_reg_ppstg_src_kernel_win_1_val_1_0_reg_2746_pp0_iter3;
        src_kernel_win_2_val_1_1_1_fu_238 <= src_kernel_win_2_val_1_1_fu_234;
        src_kernel_win_2_val_1_1_fu_234 <= ap_reg_ppstg_src_kernel_win_2_val_1_0_reg_2764_pp0_iter3;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_start) & (1'b1 == ap_sig_cseq_ST_st1_fsm_0)) | ((1'b1 == ap_sig_cseq_ST_st3_fsm_2) & ~(1'b0 == exitcond1_fu_605_p2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st3_fsm_2) & ~(1'b0 == exitcond1_fu_605_p2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_180) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_3 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_3 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_444) begin
        ap_sig_cseq_ST_st10_fsm_4 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st10_fsm_4 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_22) begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_125) begin
        ap_sig_cseq_ST_st2_fsm_1 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_150) begin
        ap_sig_cseq_ST_st3_fsm_2 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st3_fsm_2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)))) begin
        k_buf_0_val_3_ce0 = 1'b1;
    end else begin
        k_buf_0_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & ~(1'b0 == icmp_reg_2577) & ~(1'b0 == tmp_8_reg_2568) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & (1'b0 == icmp_reg_2577) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b0 == tmp_2_reg_2582)))) begin
        k_buf_0_val_3_ce1 = 1'b1;
    end else begin
        k_buf_0_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & ~(1'b0 == icmp_reg_2577) & ~(1'b0 == tmp_8_reg_2568) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & (1'b0 == icmp_reg_2577) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b0 == tmp_2_reg_2582)))) begin
        k_buf_0_val_3_we1 = 1'b1;
    end else begin
        k_buf_0_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)))) begin
        k_buf_0_val_4_ce0 = 1'b1;
    end else begin
        k_buf_0_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & ~(1'b0 == icmp_reg_2577) & ~(1'b0 == tmp_8_reg_2568) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & (1'b0 == icmp_reg_2577) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b0 == tmp_128_0_1_reg_2586)))) begin
        k_buf_0_val_4_ce1 = 1'b1;
    end else begin
        k_buf_0_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_1617) begin
        if (ap_sig_1620) begin
            k_buf_0_val_4_d1 = k_buf_0_val_3_q0;
        end else if (ap_sig_1618) begin
            k_buf_0_val_4_d1 = p_src_data_stream_0_V_dout;
        end else begin
            k_buf_0_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & ~(1'b0 == icmp_reg_2577) & ~(1'b0 == tmp_8_reg_2568) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & (1'b0 == icmp_reg_2577) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b0 == tmp_128_0_1_reg_2586)))) begin
        k_buf_0_val_4_we1 = 1'b1;
    end else begin
        k_buf_0_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)))) begin
        k_buf_0_val_5_ce0 = 1'b1;
    end else begin
        k_buf_0_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & ~(1'b0 == icmp_reg_2577) & ~(1'b0 == tmp_8_reg_2568) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & (1'b0 == icmp_reg_2577) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b0 == tmp_2_reg_2582)))) begin
        k_buf_0_val_5_ce1 = 1'b1;
    end else begin
        k_buf_0_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_1617) begin
        if (ap_sig_1620) begin
            k_buf_0_val_5_d1 = k_buf_0_val_4_q0;
        end else if (ap_sig_1623) begin
            k_buf_0_val_5_d1 = p_src_data_stream_0_V_dout;
        end else begin
            k_buf_0_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & ~(1'b0 == icmp_reg_2577) & ~(1'b0 == tmp_8_reg_2568) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & (1'b0 == icmp_reg_2577) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b0 == tmp_2_reg_2582)))) begin
        k_buf_0_val_5_we1 = 1'b1;
    end else begin
        k_buf_0_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)))) begin
        k_buf_1_val_3_ce0 = 1'b1;
    end else begin
        k_buf_1_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & ~(1'b0 == icmp_reg_2577) & ~(1'b0 == tmp_8_reg_2568) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & (1'b0 == icmp_reg_2577) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b0 == tmp_2_reg_2582)))) begin
        k_buf_1_val_3_ce1 = 1'b1;
    end else begin
        k_buf_1_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & ~(1'b0 == icmp_reg_2577) & ~(1'b0 == tmp_8_reg_2568) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & (1'b0 == icmp_reg_2577) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b0 == tmp_2_reg_2582)))) begin
        k_buf_1_val_3_we1 = 1'b1;
    end else begin
        k_buf_1_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)))) begin
        k_buf_1_val_4_ce0 = 1'b1;
    end else begin
        k_buf_1_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & ~(1'b0 == icmp_reg_2577) & ~(1'b0 == tmp_8_reg_2568) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & (1'b0 == icmp_reg_2577) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b0 == tmp_128_0_1_reg_2586)))) begin
        k_buf_1_val_4_ce1 = 1'b1;
    end else begin
        k_buf_1_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_1617) begin
        if (ap_sig_1620) begin
            k_buf_1_val_4_d1 = k_buf_1_val_3_q0;
        end else if (ap_sig_1618) begin
            k_buf_1_val_4_d1 = p_src_data_stream_1_V_dout;
        end else begin
            k_buf_1_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_1_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & ~(1'b0 == icmp_reg_2577) & ~(1'b0 == tmp_8_reg_2568) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & (1'b0 == icmp_reg_2577) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b0 == tmp_128_0_1_reg_2586)))) begin
        k_buf_1_val_4_we1 = 1'b1;
    end else begin
        k_buf_1_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)))) begin
        k_buf_1_val_5_ce0 = 1'b1;
    end else begin
        k_buf_1_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & ~(1'b0 == icmp_reg_2577) & ~(1'b0 == tmp_8_reg_2568) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & (1'b0 == icmp_reg_2577) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b0 == tmp_2_reg_2582)))) begin
        k_buf_1_val_5_ce1 = 1'b1;
    end else begin
        k_buf_1_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_1617) begin
        if (ap_sig_1620) begin
            k_buf_1_val_5_d1 = k_buf_1_val_4_q0;
        end else if (ap_sig_1623) begin
            k_buf_1_val_5_d1 = p_src_data_stream_1_V_dout;
        end else begin
            k_buf_1_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_1_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & ~(1'b0 == icmp_reg_2577) & ~(1'b0 == tmp_8_reg_2568) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & (1'b0 == icmp_reg_2577) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b0 == tmp_2_reg_2582)))) begin
        k_buf_1_val_5_we1 = 1'b1;
    end else begin
        k_buf_1_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)))) begin
        k_buf_2_val_3_ce0 = 1'b1;
    end else begin
        k_buf_2_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & ~(1'b0 == icmp_reg_2577) & ~(1'b0 == tmp_8_reg_2568) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & (1'b0 == icmp_reg_2577) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b0 == tmp_2_reg_2582)))) begin
        k_buf_2_val_3_ce1 = 1'b1;
    end else begin
        k_buf_2_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & ~(1'b0 == icmp_reg_2577) & ~(1'b0 == tmp_8_reg_2568) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & (1'b0 == icmp_reg_2577) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b0 == tmp_2_reg_2582)))) begin
        k_buf_2_val_3_we1 = 1'b1;
    end else begin
        k_buf_2_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)))) begin
        k_buf_2_val_4_ce0 = 1'b1;
    end else begin
        k_buf_2_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & ~(1'b0 == icmp_reg_2577) & ~(1'b0 == tmp_8_reg_2568) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & (1'b0 == icmp_reg_2577) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b0 == tmp_128_0_1_reg_2586)))) begin
        k_buf_2_val_4_ce1 = 1'b1;
    end else begin
        k_buf_2_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_1617) begin
        if (ap_sig_1620) begin
            k_buf_2_val_4_d1 = k_buf_2_val_3_q0;
        end else if (ap_sig_1618) begin
            k_buf_2_val_4_d1 = p_src_data_stream_2_V_dout;
        end else begin
            k_buf_2_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_2_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & ~(1'b0 == icmp_reg_2577) & ~(1'b0 == tmp_8_reg_2568) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & (1'b0 == icmp_reg_2577) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b0 == tmp_128_0_1_reg_2586)))) begin
        k_buf_2_val_4_we1 = 1'b1;
    end else begin
        k_buf_2_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)))) begin
        k_buf_2_val_5_ce0 = 1'b1;
    end else begin
        k_buf_2_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & ~(1'b0 == icmp_reg_2577) & ~(1'b0 == tmp_8_reg_2568) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & (1'b0 == icmp_reg_2577) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b0 == tmp_2_reg_2582)))) begin
        k_buf_2_val_5_ce1 = 1'b1;
    end else begin
        k_buf_2_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_1617) begin
        if (ap_sig_1620) begin
            k_buf_2_val_5_d1 = k_buf_2_val_4_q0;
        end else if (ap_sig_1623) begin
            k_buf_2_val_5_d1 = p_src_data_stream_2_V_dout;
        end else begin
            k_buf_2_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_2_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & ~(1'b0 == icmp_reg_2577) & ~(1'b0 == tmp_8_reg_2568) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & (1'b0 == icmp_reg_2577) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b0 == tmp_2_reg_2582)))) begin
        k_buf_2_val_5_we1 = 1'b1;
    end else begin
        k_buf_2_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it5) & ~(1'b0 == ap_reg_ppstg_or_cond_i_reg_2664_pp0_iter4))) begin
        p_dst_data_stream_0_V_blk_n = p_dst_data_stream_0_V_full_n;
    end else begin
        p_dst_data_stream_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it5) & ~(1'b0 == ap_reg_ppstg_or_cond_i_reg_2664_pp0_iter4) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)))) begin
        p_dst_data_stream_0_V_write = 1'b1;
    end else begin
        p_dst_data_stream_0_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it5) & ~(1'b0 == ap_reg_ppstg_or_cond_i_reg_2664_pp0_iter4))) begin
        p_dst_data_stream_1_V_blk_n = p_dst_data_stream_1_V_full_n;
    end else begin
        p_dst_data_stream_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it5) & ~(1'b0 == ap_reg_ppstg_or_cond_i_reg_2664_pp0_iter4) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)))) begin
        p_dst_data_stream_1_V_write = 1'b1;
    end else begin
        p_dst_data_stream_1_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it5) & ~(1'b0 == ap_reg_ppstg_or_cond_i_reg_2664_pp0_iter4))) begin
        p_dst_data_stream_2_V_blk_n = p_dst_data_stream_2_V_full_n;
    end else begin
        p_dst_data_stream_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it5) & ~(1'b0 == ap_reg_ppstg_or_cond_i_reg_2664_pp0_iter4) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)))) begin
        p_dst_data_stream_2_V_write = 1'b1;
    end else begin
        p_dst_data_stream_2_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & ~(1'b0 == icmp_reg_2577) & ~(1'b0 == tmp_8_reg_2568)) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & (1'b0 == icmp_reg_2577)))) begin
        p_src_data_stream_0_V_blk_n = p_src_data_stream_0_V_empty_n;
    end else begin
        p_src_data_stream_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & (1'b0 == icmp_reg_2577) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & ~(1'b0 == icmp_reg_2577) & ~(1'b0 == tmp_8_reg_2568) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))))) begin
        p_src_data_stream_0_V_read = 1'b1;
    end else begin
        p_src_data_stream_0_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & ~(1'b0 == icmp_reg_2577) & ~(1'b0 == tmp_8_reg_2568)) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & (1'b0 == icmp_reg_2577)))) begin
        p_src_data_stream_1_V_blk_n = p_src_data_stream_1_V_empty_n;
    end else begin
        p_src_data_stream_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & (1'b0 == icmp_reg_2577) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & ~(1'b0 == icmp_reg_2577) & ~(1'b0 == tmp_8_reg_2568) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))))) begin
        p_src_data_stream_1_V_read = 1'b1;
    end else begin
        p_src_data_stream_1_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & ~(1'b0 == icmp_reg_2577) & ~(1'b0 == tmp_8_reg_2568)) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & (1'b0 == icmp_reg_2577)))) begin
        p_src_data_stream_2_V_blk_n = p_src_data_stream_2_V_empty_n;
    end else begin
        p_src_data_stream_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & (1'b0 == icmp_reg_2577) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & ~(1'b0 == icmp_reg_2577) & ~(1'b0 == tmp_8_reg_2568) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206))))) begin
        p_src_data_stream_2_V_read = 1'b1;
    end else begin
        p_src_data_stream_2_V_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : begin
            if (~(ap_start == 1'b0)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : begin
            if (~(1'b0 == tmp_7_fu_577_p2)) begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end
        end
        ap_ST_st3_fsm_2 : begin
            if (~(1'b0 == exitcond1_fu_605_p2)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_3;
            end
        end
        ap_ST_pp0_stg0_fsm_3 : begin
            if ((~((1'b1 == ap_reg_ppiten_pp0_it5) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b1 == ap_reg_ppiten_pp0_it4)) & ~((1'b1 == ap_reg_ppiten_pp0_it2) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b1 == ap_reg_ppiten_pp0_it1) & ~(1'b1 == ap_reg_ppiten_pp0_it3)))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_3;
            end else if ((((1'b1 == ap_reg_ppiten_pp0_it5) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b1 == ap_reg_ppiten_pp0_it4)) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_196) | ((1'b1 == ap_reg_ppiten_pp0_it5) & ap_sig_206)) & ~(1'b1 == ap_reg_ppiten_pp0_it1) & ~(1'b1 == ap_reg_ppiten_pp0_it3)))) begin
                ap_NS_fsm = ap_ST_st10_fsm_4;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_3;
            end
        end
        ap_ST_st10_fsm_4 : begin
            ap_NS_fsm = ap_ST_st3_fsm_2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ImagLoc_x_cast_fu_957_p1 = $signed(ImagLoc_x_fu_951_p2);

assign ImagLoc_x_fu_951_p2 = ($signed(ap_const_lv12_FFF) + $signed(p_027_0_i_cast_fu_919_p1));

assign OP1_V_0_0_cast_fu_1609_p1 = src_kernel_win_0_val_2_1_1_fu_198;

assign OP1_V_1_0_cast_fu_1661_p1 = src_kernel_win_1_val_2_1_1_fu_222;

assign OP1_V_2_0_cast_fu_1713_p1 = src_kernel_win_2_val_2_1_1_fu_246;

assign OP2_V_0_0_1_cast_fu_583_p1 = $signed(p_kernel_val_0_V_1_read);

assign OP2_V_0_0_2_cast_fu_586_p1 = $signed(p_kernel_val_0_V_2_read);

assign OP2_V_0_1_2_cast_fu_592_p1 = p_kernel_val_1_V_2_read;

assign OP2_V_0_1_cast_fu_589_p1 = $signed(p_kernel_val_1_V_0_read);

assign OP2_V_0_2_cast_fu_595_p1 = $signed(p_kernel_val_2_V_0_read);

always @ (*) begin
    ap_sig_125 = (1'b1 == ap_CS_fsm[ap_const_lv32_1]);
end

always @ (*) begin
    ap_sig_150 = (1'b1 == ap_CS_fsm[ap_const_lv32_2]);
end

always @ (*) begin
    ap_sig_1617 = ((1'b1 == ap_reg_ppiten_pp0_it2) & (ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1));
end

always @ (*) begin
    ap_sig_1618 = ((1'b0 == icmp_reg_2577) & ~(1'b0 == tmp_128_0_1_reg_2586));
end

always @ (*) begin
    ap_sig_1620 = (~(1'b0 == icmp_reg_2577) & ~(1'b0 == tmp_8_reg_2568));
end

always @ (*) begin
    ap_sig_1623 = ((1'b0 == icmp_reg_2577) & ~(1'b0 == tmp_2_reg_2582));
end

always @ (*) begin
    ap_sig_180 = (1'b1 == ap_CS_fsm[ap_const_lv32_3]);
end

always @ (*) begin
    ap_sig_196 = (((ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & (1'b0 == icmp_reg_2577) & (p_src_data_stream_0_V_empty_n == 1'b0)) | ((ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & ~(1'b0 == icmp_reg_2577) & ~(1'b0 == tmp_8_reg_2568) & (p_src_data_stream_0_V_empty_n == 1'b0)) | ((ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & (1'b0 == icmp_reg_2577) & (p_src_data_stream_1_V_empty_n == 1'b0)) | ((ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & ~(1'b0 == icmp_reg_2577) & ~(1'b0 == tmp_8_reg_2568) & (p_src_data_stream_1_V_empty_n == 1'b0)) | ((ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & (1'b0 == icmp_reg_2577) & (p_src_data_stream_2_V_empty_n == 1'b0)) | ((ap_reg_ppstg_exitcond_reg_2628_pp0_iter1 == 1'b0) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_reg_2637_pp0_iter1) & ~(1'b0 == icmp_reg_2577) & ~(1'b0 == tmp_8_reg_2568) & (p_src_data_stream_2_V_empty_n == 1'b0)));
end

always @ (*) begin
    ap_sig_206 = ((~(1'b0 == ap_reg_ppstg_or_cond_i_reg_2664_pp0_iter4) & (p_dst_data_stream_0_V_full_n == 1'b0)) | (~(1'b0 == ap_reg_ppstg_or_cond_i_reg_2664_pp0_iter4) & (p_dst_data_stream_1_V_full_n == 1'b0)) | (~(1'b0 == ap_reg_ppstg_or_cond_i_reg_2664_pp0_iter4) & (p_dst_data_stream_2_V_full_n == 1'b0)));
end

always @ (*) begin
    ap_sig_22 = (ap_CS_fsm[ap_const_lv32_0] == 1'b1);
end

always @ (*) begin
    ap_sig_444 = (1'b1 == ap_CS_fsm[ap_const_lv32_4]);
end

assign brmerge_fu_1071_p2 = (tmp_82_not_reg_2572 | tmp_18_fu_975_p2);

assign col_assign_3_0_t_fu_1124_p2 = (ap_reg_ppstg_tmp_75_reg_2646_pp0_iter1 ^ ap_const_lv2_3);

assign col_buf_0_val_0_0_fu_1141_p3 = ((ap_reg_ppstg_brmerge_reg_2651_pp0_iter1[0:0] === 1'b1) ? k_buf_0_val_3_q0 : tmp_25_fu_1129_p5);

assign col_buf_0_val_1_0_fu_1160_p3 = ((ap_reg_ppstg_brmerge_reg_2651_pp0_iter1[0:0] === 1'b1) ? k_buf_0_val_4_q0 : tmp_26_fu_1148_p5);

assign col_buf_0_val_2_0_fu_1179_p3 = ((ap_reg_ppstg_brmerge_reg_2651_pp0_iter1[0:0] === 1'b1) ? k_buf_0_val_5_q0 : tmp_27_fu_1167_p5);

assign col_buf_1_val_0_0_fu_1309_p3 = ((ap_reg_ppstg_brmerge_reg_2651_pp0_iter1[0:0] === 1'b1) ? k_buf_1_val_3_q0 : tmp_34_fu_1297_p5);

assign col_buf_1_val_1_0_fu_1328_p3 = ((ap_reg_ppstg_brmerge_reg_2651_pp0_iter1[0:0] === 1'b1) ? k_buf_1_val_4_q0 : tmp_36_fu_1316_p5);

assign col_buf_1_val_2_0_fu_1347_p3 = ((ap_reg_ppstg_brmerge_reg_2651_pp0_iter1[0:0] === 1'b1) ? k_buf_1_val_5_q0 : tmp_38_fu_1335_p5);

assign col_buf_2_val_0_0_fu_1468_p3 = ((ap_reg_ppstg_brmerge_reg_2651_pp0_iter1[0:0] === 1'b1) ? k_buf_2_val_3_q0 : tmp_45_fu_1456_p5);

assign col_buf_2_val_1_0_fu_1487_p3 = ((ap_reg_ppstg_brmerge_reg_2651_pp0_iter1[0:0] === 1'b1) ? k_buf_2_val_4_q0 : tmp_46_fu_1475_p5);

assign col_buf_2_val_2_0_fu_1506_p3 = ((ap_reg_ppstg_brmerge_reg_2651_pp0_iter1[0:0] === 1'b1) ? k_buf_2_val_5_q0 : tmp_47_fu_1494_p5);

assign exitcond1_fu_605_p2 = ((p_014_0_i_reg_549 == ap_const_lv11_43A) ? 1'b1 : 1'b0);

assign exitcond_fu_923_p2 = ((p_027_0_i_reg_560 == ap_const_lv11_782) ? 1'b1 : 1'b0);

assign grp_fu_2140_p0 = tmp_s_reg_2552;

assign grp_fu_2140_p1 = grp_fu_2140_p10;

assign grp_fu_2140_p10 = src_kernel_win_2_val_0_1_fu_226;

assign grp_fu_2140_p2 = grp_fu_2140_p20;

assign grp_fu_2140_p20 = src_kernel_win_2_val_0_0_reg_2758;

assign grp_fu_2147_p0 = OP2_V_0_1_cast_reg_2531;

assign grp_fu_2147_p1 = grp_fu_2147_p10;

assign grp_fu_2147_p10 = src_kernel_win_2_val_1_1_1_fu_238;

assign grp_fu_2155_p0 = OP2_V_0_1_cast_reg_2531;

assign grp_fu_2155_p1 = grp_fu_2155_p10;

assign grp_fu_2155_p10 = src_kernel_win_1_val_1_1_1_fu_214;

assign grp_fu_2163_p0 = tmp_s_reg_2552;

assign grp_fu_2163_p1 = grp_fu_2163_p10;

assign grp_fu_2163_p10 = src_kernel_win_1_val_0_1_fu_202;

assign grp_fu_2163_p2 = grp_fu_2163_p20;

assign grp_fu_2163_p20 = src_kernel_win_1_val_0_0_reg_2740;

assign grp_fu_2170_p0 = tmp_s_reg_2552;

assign grp_fu_2170_p1 = grp_fu_2170_p10;

assign grp_fu_2170_p10 = src_kernel_win_0_val_0_1_fu_178;

assign grp_fu_2170_p2 = grp_fu_2170_p20;

assign grp_fu_2170_p20 = src_kernel_win_0_val_0_0_reg_2722;

assign grp_fu_2177_p0 = OP2_V_0_0_1_cast_reg_2517;

assign grp_fu_2177_p1 = grp_fu_2177_p10;

assign grp_fu_2177_p10 = src_kernel_win_0_val_2_1_fu_194;

assign grp_fu_2184_p0 = OP2_V_0_0_1_cast_reg_2517;

assign grp_fu_2184_p1 = grp_fu_2184_p10;

assign grp_fu_2184_p10 = src_kernel_win_1_val_2_1_fu_218;

assign grp_fu_2191_p0 = OP2_V_0_1_cast_reg_2531;

assign grp_fu_2191_p1 = grp_fu_2191_p10;

assign grp_fu_2191_p10 = src_kernel_win_0_val_1_1_1_fu_190;

assign grp_fu_2199_p0 = OP2_V_0_0_2_cast_reg_2524;

assign grp_fu_2199_p1 = grp_fu_2199_p10;

assign grp_fu_2199_p10 = src_kernel_win_1_val_2_0_reg_2752;

assign grp_fu_2207_p0 = OP2_V_0_0_1_cast_reg_2517;

assign grp_fu_2207_p1 = grp_fu_2207_p10;

assign grp_fu_2207_p10 = src_kernel_win_2_val_2_1_fu_242;

assign grp_fu_2214_p0 = OP2_V_0_1_2_cast_reg_2538;

assign grp_fu_2214_p1 = grp_fu_2214_p10;

assign grp_fu_2214_p10 = ap_reg_ppstg_src_kernel_win_0_val_1_0_reg_2728_pp0_iter3;

assign grp_fu_2221_p0 = OP2_V_0_1_2_cast_reg_2538;

assign grp_fu_2221_p1 = grp_fu_2221_p10;

assign grp_fu_2221_p10 = ap_reg_ppstg_src_kernel_win_1_val_1_0_reg_2746_pp0_iter3;

assign grp_fu_2228_p0 = OP2_V_0_0_2_cast_reg_2524;

assign grp_fu_2228_p1 = grp_fu_2228_p10;

assign grp_fu_2228_p10 = src_kernel_win_2_val_2_0_reg_2770;

assign grp_fu_2236_p0 = OP2_V_0_0_2_cast_reg_2524;

assign grp_fu_2236_p1 = grp_fu_2236_p10;

assign grp_fu_2236_p10 = src_kernel_win_0_val_2_0_reg_2734;

assign grp_fu_2244_p0 = OP2_V_0_1_2_cast_reg_2538;

assign grp_fu_2244_p1 = grp_fu_2244_p10;

assign grp_fu_2244_p10 = ap_reg_ppstg_src_kernel_win_2_val_1_0_reg_2764_pp0_iter3;

assign i_V_fu_611_p2 = (p_014_0_i_reg_549 + ap_const_lv11_1);

assign icmp1_fu_945_p2 = ((tmp_72_fu_935_p4 != ap_const_lv10_0) ? 1'b1 : 1'b0);

assign icmp_fu_639_p2 = ((tmp_15_fu_629_p4 != ap_const_lv10_0) ? 1'b1 : 1'b0);

assign j_V_fu_929_p2 = (p_027_0_i_reg_560 + ap_const_lv11_1);

assign k_buf_0_val_3_address0 = tmp_23_fu_1084_p1;

assign k_buf_0_val_4_address0 = tmp_23_fu_1084_p1;

assign k_buf_0_val_5_address0 = tmp_23_fu_1084_p1;

assign k_buf_1_val_3_address0 = tmp_23_fu_1084_p1;

assign k_buf_1_val_4_address0 = tmp_23_fu_1084_p1;

assign k_buf_1_val_5_address0 = tmp_23_fu_1084_p1;

assign k_buf_2_val_3_address0 = tmp_23_fu_1084_p1;

assign k_buf_2_val_4_address0 = tmp_23_fu_1084_p1;

assign k_buf_2_val_5_address0 = tmp_23_fu_1084_p1;

assign not_i_i_i1_fu_1993_p2 = ((tmp_54_fu_1983_p4 != ap_const_lv4_0) ? 1'b1 : 1'b0);

assign not_i_i_i5_fu_1935_p2 = ((tmp_44_fu_1925_p4 != ap_const_lv4_0) ? 1'b1 : 1'b0);

assign not_i_i_i_fu_1877_p2 = ((tmp_33_fu_1867_p4 != ap_const_lv4_0) ? 1'b1 : 1'b0);

assign or_cond_i423_i_fu_689_p2 = (tmp_9_fu_683_p2 & rev_fu_677_p2);

assign or_cond_i_fu_1076_p2 = (icmp_reg_2577 & icmp1_fu_945_p2);

assign or_cond_i_i_fu_981_p2 = (tmp_18_fu_975_p2 & rev1_fu_969_p2);

assign overflow_1_fu_2078_p2 = (not_i_i_i5_reg_2848 & tmp_3_i_i4_fu_2073_p2);

assign overflow_2_fu_2113_p2 = (not_i_i_i1_reg_2864 & tmp_3_i_i1_fu_2108_p2);

assign overflow_fu_2043_p2 = (not_i_i_i_reg_2832 & tmp_3_i_i_fu_2038_p2);

assign p_014_0_i_cast_fu_601_p1 = p_014_0_i_reg_549;

assign p_027_0_i_cast_fu_919_p1 = p_027_0_i_reg_560;

assign p_Val2_0_2_fu_1637_p0 = OP2_V_0_2_cast_reg_2545;

assign p_Val2_0_2_fu_1637_p1 = p_Val2_0_2_fu_1637_p10;

assign p_Val2_0_2_fu_1637_p10 = src_kernel_win_0_val_0_1_1_fu_182;

assign p_Val2_0_2_fu_1637_p2 = ($signed(p_Val2_0_2_fu_1637_p0) * $signed({{1'b0}, {p_Val2_0_2_fu_1637_p1}}));

assign p_Val2_1_2_fu_1689_p0 = OP2_V_0_2_cast_reg_2545;

assign p_Val2_1_2_fu_1689_p1 = p_Val2_1_2_fu_1689_p10;

assign p_Val2_1_2_fu_1689_p10 = src_kernel_win_1_val_0_1_1_fu_206;

assign p_Val2_1_2_fu_1689_p2 = ($signed(p_Val2_1_2_fu_1689_p0) * $signed({{1'b0}, {p_Val2_1_2_fu_1689_p1}}));

assign p_Val2_1_fu_1613_p2 = (ap_const_lv9_0 - OP1_V_0_0_cast_fu_1609_p1);

assign p_Val2_2_2_fu_1741_p0 = OP2_V_0_2_cast_reg_2545;

assign p_Val2_2_2_fu_1741_p1 = p_Val2_2_2_fu_1741_p10;

assign p_Val2_2_2_fu_1741_p10 = src_kernel_win_2_val_0_1_1_fu_230;

assign p_Val2_2_2_fu_1741_p2 = ($signed(p_Val2_2_2_fu_1741_p0) * $signed({{1'b0}, {p_Val2_2_2_fu_1741_p1}}));

assign p_Val2_2_fu_1717_p2 = (ap_const_lv9_0 - OP1_V_2_0_cast_fu_1713_p1);

assign p_Val2_3_fu_1853_p2 = (p_Val2_5_0_2_fu_1844_p2 + tmp3_cast_fu_1850_p1);

assign p_Val2_4_fu_2035_p1 = p_Val2_3_reg_2821[7:0];

assign p_Val2_5_0_2_fu_1844_p2 = ($signed(tmp1_cast_fu_1838_p1) + $signed(tmp2_cast_fu_1841_p1));

assign p_Val2_5_1_2_fu_1902_p2 = ($signed(tmp5_cast_fu_1896_p1) + $signed(tmp6_cast_fu_1899_p1));

assign p_Val2_5_2_2_fu_1960_p2 = ($signed(tmp9_cast_fu_1954_p1) + $signed(tmp10_cast_fu_1957_p1));

assign p_Val2_6_fu_1911_p2 = (p_Val2_5_1_2_fu_1902_p2 + tmp7_cast_fu_1908_p1);

assign p_Val2_7_fu_2070_p1 = p_Val2_6_reg_2837[7:0];

assign p_Val2_8_fu_2105_p1 = p_Val2_s_52_reg_2853[7:0];

assign p_Val2_s_52_fu_1969_p2 = (p_Val2_5_2_2_fu_1960_p2 + tmp11_cast_fu_1966_p1);

assign p_Val2_s_fu_1665_p2 = (ap_const_lv9_0 - OP1_V_1_0_cast_fu_1661_p1);

assign p_assign_1_fu_995_p2 = (ap_const_lv12_1 - p_027_0_i_cast_fu_919_p1);

assign p_assign_2_cast_fu_1029_p1 = p_assign_2_fu_1023_p2;

assign p_assign_2_fu_1023_p2 = ($signed(ap_const_lv13_EFE) - $signed(p_p2_i_i_cast_cast_fu_1013_p1));

assign p_assign_6_0_1_fu_729_p2 = ($signed(p_014_0_i_cast_fu_601_p1) + $signed(ap_const_lv12_FFE));

assign p_assign_6_0_2_fu_755_p2 = ($signed(p_014_0_i_cast_fu_601_p1) + $signed(ap_const_lv12_FFD));

assign p_assign_7_fu_703_p2 = (ap_const_lv12_1 - p_014_0_i_cast_fu_601_p1);

assign p_assign_8_fu_723_p2 = ($signed(ap_const_lv12_86E) - $signed(p_p2_i424_i_fu_709_p3));

assign p_dst_data_stream_0_V_din = ((tmp_i_i_fu_2056_p2[0:0] === 1'b1) ? p_mux_i_i_cast_fu_2048_p3 : p_Val2_4_fu_2035_p1);

assign p_dst_data_stream_1_V_din = ((tmp_i_i8_fu_2091_p2[0:0] === 1'b1) ? p_mux_i_i7_cast_fu_2083_p3 : p_Val2_7_fu_2070_p1);

assign p_dst_data_stream_2_V_din = ((tmp_i_i1_fu_2126_p2[0:0] === 1'b1) ? p_mux_i_i16_cast_fu_2118_p3 : p_Val2_8_fu_2105_p1);

assign p_mux_i_i16_cast_fu_2118_p3 = ((tmp_3_i_i1_fu_2108_p2[0:0] === 1'b1) ? ap_const_lv8_FF : ap_const_lv8_0);

assign p_mux_i_i7_cast_fu_2083_p3 = ((tmp_3_i_i4_fu_2073_p2[0:0] === 1'b1) ? ap_const_lv8_FF : ap_const_lv8_0);

assign p_mux_i_i_cast_fu_2048_p3 = ((tmp_3_i_i_fu_2038_p2[0:0] === 1'b1) ? ap_const_lv8_FF : ap_const_lv8_0);

assign p_p2_i424_i_fu_709_p3 = ((tmp_19_fu_695_p3[0:0] === 1'b1) ? p_assign_7_fu_703_p2 : tmp_4_fu_663_p2);

assign p_p2_i_i_cast_cast_fu_1013_p1 = $signed(p_p2_i_i_fu_1001_p3);

assign p_p2_i_i_cast_fu_1009_p1 = $signed(p_p2_i_i_fu_1001_p3);

assign p_p2_i_i_fu_1001_p3 = ((tmp_74_fu_987_p3[0:0] === 1'b1) ? p_assign_1_fu_995_p2 : ImagLoc_x_fu_951_p2);

assign rev1_fu_969_p2 = (tmp_73_fu_961_p3 ^ 1'b1);

assign rev_fu_677_p2 = (tmp_17_fu_669_p3 ^ 1'b1);

assign row_assign_10_0_1_t_fu_845_p2 = (tmp_11_fu_837_p3 ^ ap_const_lv2_3);

assign row_assign_10_0_2_t_fu_877_p2 = (tmp_12_fu_869_p3 ^ ap_const_lv2_3);

assign row_assign_10_1_0_t_fu_913_p2 = (tmp_14_fu_905_p3 ^ ap_const_lv2_3);

assign row_assign_s_fu_813_p2 = (tmp_62_fu_805_p3 ^ ap_const_lv2_3);

assign sel_tmp1_fu_1047_p2 = (tmp_73_fu_961_p3 | tmp_21_not_fu_1041_p2);

assign sel_tmp2_fu_1053_p2 = (tmp_21_fu_1017_p2 & sel_tmp1_fu_1047_p2);

assign sel_tmp_fu_1033_p3 = ((or_cond_i_i_fu_981_p2[0:0] === 1'b1) ? ImagLoc_x_cast_fu_957_p1 : p_assign_2_cast_fu_1029_p1);

assign src_kernel_win_0_val_0_0_fu_1236_p3 = ((tmp_3_reg_2590[0:0] === 1'b1) ? tmp_28_fu_1225_p5 : col_buf_0_val_0_0_fu_1141_p3);

assign src_kernel_win_0_val_1_0_fu_1254_p3 = ((tmp_3_reg_2590[0:0] === 1'b1) ? tmp_29_fu_1243_p5 : col_buf_0_val_1_0_fu_1160_p3);

assign src_kernel_win_0_val_2_0_fu_1272_p3 = ((tmp_3_reg_2590[0:0] === 1'b1) ? tmp_31_fu_1261_p5 : col_buf_0_val_2_0_fu_1179_p3);

assign src_kernel_win_1_val_0_0_fu_1404_p3 = ((tmp_3_reg_2590[0:0] === 1'b1) ? tmp_39_fu_1393_p5 : col_buf_1_val_0_0_fu_1309_p3);

assign src_kernel_win_1_val_1_0_fu_1422_p3 = ((tmp_3_reg_2590[0:0] === 1'b1) ? tmp_40_fu_1411_p5 : col_buf_1_val_1_0_fu_1328_p3);

assign src_kernel_win_1_val_2_0_fu_1440_p3 = ((tmp_3_reg_2590[0:0] === 1'b1) ? tmp_42_fu_1429_p5 : col_buf_1_val_2_0_fu_1347_p3);

assign src_kernel_win_2_val_0_0_fu_1554_p3 = ((tmp_3_reg_2590[0:0] === 1'b1) ? tmp_49_fu_1543_p5 : col_buf_2_val_0_0_fu_1468_p3);

assign src_kernel_win_2_val_1_0_fu_1572_p3 = ((tmp_3_reg_2590[0:0] === 1'b1) ? tmp_51_fu_1561_p5 : col_buf_2_val_1_0_fu_1487_p3);

assign src_kernel_win_2_val_2_0_fu_1590_p3 = ((tmp_3_reg_2590[0:0] === 1'b1) ? tmp_52_fu_1579_p5 : col_buf_2_val_2_0_fu_1506_p3);

assign tmp10_cast_fu_1957_p1 = grp_fu_2147_p3;

assign tmp11_cast_fu_1966_p1 = tmp11_reg_2816;

assign tmp1_cast_fu_1838_p1 = grp_fu_2214_p3;

assign tmp2_cast_fu_1841_p1 = grp_fu_2191_p3;

assign tmp3_cast_fu_1850_p1 = tmp3_reg_2786;

assign tmp5_cast_fu_1896_p1 = grp_fu_2221_p3;

assign tmp6_cast_fu_1899_p1 = grp_fu_2155_p3;

assign tmp7_cast_fu_1908_p1 = tmp7_reg_2801;

assign tmp9_cast_fu_1954_p1 = grp_fu_2244_p3;

assign tmp_10_fu_717_p2 = (($signed(p_p2_i424_i_fu_709_p3) < $signed(12'b10000111000)) ? 1'b1 : 1'b0);

assign tmp_11_fu_837_p3 = ((tmp_20_fu_735_p3[0:0] === 1'b1) ? tmp_65_fu_829_p3 : tmp_63_fu_819_p1);

assign tmp_128_0_1_fu_651_p2 = ((p_014_0_i_reg_549 == ap_const_lv11_0) ? 1'b1 : 1'b0);

assign tmp_12_fu_869_p3 = ((tmp_30_fu_761_p3[0:0] === 1'b1) ? tmp_68_fu_861_p3 : tmp_66_fu_851_p1);

assign tmp_13_fu_897_p3 = ((tmp_10_fu_717_p2[0:0] === 1'b1) ? tmp_70_fu_887_p1 : tmp_71_fu_891_p2);

assign tmp_14_fu_905_p3 = ((or_cond_i423_i_fu_689_p2[0:0] === 1'b1) ? tmp_69_fu_883_p1 : tmp_13_fu_897_p3);

assign tmp_15_fu_629_p4 = {{p_014_0_i_reg_549[ap_const_lv32_A : ap_const_lv32_1]}};

assign tmp_17_fu_669_p3 = tmp_4_fu_663_p2[ap_const_lv32_B];

assign tmp_18_fu_975_p2 = (($signed(ImagLoc_x_fu_951_p2) < $signed(12'b11110000000)) ? 1'b1 : 1'b0);

assign tmp_19_fu_695_p3 = tmp_4_fu_663_p2[ap_const_lv32_B];

assign tmp_20_fu_735_p3 = p_assign_6_0_1_fu_729_p2[ap_const_lv32_B];

assign tmp_21_fu_1017_p2 = (($signed(p_p2_i_i_fu_1001_p3) < $signed(12'b11110000000)) ? 1'b1 : 1'b0);

assign tmp_21_not_fu_1041_p2 = (tmp_18_fu_975_p2 ^ 1'b1);

assign tmp_22_fu_743_p3 = p_assign_6_0_1_fu_729_p2[ap_const_lv32_B];

assign tmp_23_fu_1084_p1 = $unsigned(x_cast_fu_1081_p1);

assign tmp_24_fu_751_p1 = p_014_0_i_reg_549[1:0];

assign tmp_2_fu_645_p2 = ((p_014_0_i_reg_549 == ap_const_lv11_1) ? 1'b1 : 1'b0);

assign tmp_30_fu_761_p3 = p_assign_6_0_2_fu_755_p2[ap_const_lv32_B];

assign tmp_33_fu_1867_p4 = {{p_Val2_3_fu_1853_p2[ap_const_lv32_B : ap_const_lv32_8]}};

assign tmp_35_fu_769_p3 = p_assign_6_0_2_fu_755_p2[ap_const_lv32_B];

assign tmp_37_fu_777_p1 = p_014_0_i_reg_549[1:0];

assign tmp_3_fu_657_p2 = ((p_014_0_i_reg_549 > ap_const_lv11_438) ? 1'b1 : 1'b0);

assign tmp_3_i_i1_fu_2108_p2 = (isneg_2_reg_2858 ^ 1'b1);

assign tmp_3_i_i4_fu_2073_p2 = (isneg_1_reg_2842 ^ 1'b1);

assign tmp_3_i_i_fu_2038_p2 = (isneg_reg_2826 ^ 1'b1);

assign tmp_41_fu_781_p1 = p_p2_i424_i_fu_709_p3[1:0];

assign tmp_44_fu_1925_p4 = {{p_Val2_6_fu_1911_p2[ap_const_lv32_B : ap_const_lv32_8]}};

assign tmp_48_fu_785_p1 = tmp_4_fu_663_p2[1:0];

assign tmp_4_fu_663_p2 = ($signed(p_014_0_i_cast_fu_601_p1) + $signed(ap_const_lv12_FFF));

assign tmp_50_fu_789_p1 = p_p2_i424_i_fu_709_p3[1:0];

assign tmp_54_fu_1983_p4 = {{p_Val2_s_52_fu_1969_p2[ap_const_lv32_B : ap_const_lv32_8]}};

assign tmp_60_fu_793_p1 = p_assign_8_fu_723_p2[1:0];

assign tmp_61_fu_797_p3 = ((tmp_10_fu_717_p2[0:0] === 1'b1) ? tmp_50_fu_789_p1 : tmp_60_fu_793_p1);

assign tmp_62_fu_805_p3 = ((or_cond_i423_i_fu_689_p2[0:0] === 1'b1) ? tmp_48_fu_785_p1 : tmp_61_fu_797_p3);

assign tmp_63_fu_819_p1 = p_assign_6_0_1_fu_729_p2[1:0];

assign tmp_64_fu_823_p2 = ($signed(ap_const_lv2_2) - $signed(tmp_24_fu_751_p1));

assign tmp_65_fu_829_p3 = ((tmp_22_fu_743_p3[0:0] === 1'b1) ? tmp_64_fu_823_p2 : tmp_63_fu_819_p1);

assign tmp_66_fu_851_p1 = p_assign_6_0_2_fu_755_p2[1:0];

assign tmp_67_fu_855_p2 = (tmp_37_fu_777_p1 ^ ap_const_lv2_3);

assign tmp_68_fu_861_p3 = ((tmp_35_fu_769_p3[0:0] === 1'b1) ? tmp_67_fu_855_p2 : tmp_66_fu_851_p1);

assign tmp_69_fu_883_p1 = tmp_4_fu_663_p2[1:0];

assign tmp_6_fu_571_p2 = (tmp_5_reg_538 + ap_const_lv2_1);

assign tmp_70_fu_887_p1 = p_p2_i424_i_fu_709_p3[1:0];

assign tmp_71_fu_891_p2 = ($signed(ap_const_lv2_2) - $signed(tmp_41_fu_781_p1));

assign tmp_72_fu_935_p4 = {{p_027_0_i_reg_560[ap_const_lv32_A : ap_const_lv32_1]}};

assign tmp_73_fu_961_p3 = ImagLoc_x_fu_951_p2[ap_const_lv32_B];

assign tmp_74_fu_987_p3 = ImagLoc_x_fu_951_p2[ap_const_lv32_B];

assign tmp_75_fu_1067_p1 = x_fu_1059_p3[1:0];

assign tmp_7_fu_577_p2 = ((tmp_5_reg_538 == ap_const_lv2_2) ? 1'b1 : 1'b0);

assign tmp_82_not_fu_623_p2 = ((p_014_0_i_reg_549 > ap_const_lv11_437) ? 1'b1 : 1'b0);

assign tmp_8_fu_617_p2 = ((p_014_0_i_reg_549 < ap_const_lv11_438) ? 1'b1 : 1'b0);

assign tmp_9_fu_683_p2 = (($signed(tmp_4_fu_663_p2) < $signed(12'b10000111000)) ? 1'b1 : 1'b0);

assign tmp_i_i1_fu_2126_p2 = (isneg_2_reg_2858 | overflow_2_fu_2113_p2);

assign tmp_i_i8_fu_2091_p2 = (isneg_1_reg_2842 | overflow_1_fu_2078_p2);

assign tmp_i_i_fu_2056_p2 = (isneg_reg_2826 | overflow_fu_2043_p2);

assign tmp_s_fu_598_p1 = p_kernel_val_2_V_1_read;

assign x_cast_fu_1081_p1 = $signed(x_reg_2641);

assign x_fu_1059_p3 = ((sel_tmp2_fu_1053_p2[0:0] === 1'b1) ? p_p2_i_i_cast_fu_1009_p1 : sel_tmp_fu_1033_p3);

always @ (posedge ap_clk) begin
    OP2_V_0_1_2_cast_reg_2538[10:3] <= 8'b00000000;
    tmp_s_reg_2552[9:4] <= 6'b000000;
end

endmodule //split_ip_Filter2D
