// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "split_ip_sobel.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic split_ip_sobel::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic split_ip_sobel::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> split_ip_sobel::ap_ST_st1_fsm_0 = "1";
const sc_lv<2> split_ip_sobel::ap_ST_st2_fsm_1 = "10";
const sc_lv<32> split_ip_sobel::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> split_ip_sobel::ap_const_lv1_1 = "1";
const sc_lv<1> split_ip_sobel::ap_const_lv1_0 = "0";
const sc_lv<32> split_ip_sobel::ap_const_lv32_1 = "1";
const sc_lv<3> split_ip_sobel::ap_const_lv3_6 = "110";
const sc_lv<3> split_ip_sobel::ap_const_lv3_0 = "000";
const sc_lv<2> split_ip_sobel::ap_const_lv2_3 = "11";
const sc_lv<2> split_ip_sobel::ap_const_lv2_1 = "1";
const sc_lv<2> split_ip_sobel::ap_const_lv2_0 = "00";
const sc_lv<2> split_ip_sobel::ap_const_lv2_2 = "10";
const sc_lv<3> split_ip_sobel::ap_const_lv3_2 = "10";
const sc_lv<4> split_ip_sobel::ap_const_lv4_2 = "10";
const sc_lv<4> split_ip_sobel::ap_const_lv4_0 = "0000";
const sc_lv<8> split_ip_sobel::ap_const_lv8_1 = "1";

split_ip_sobel::split_ip_sobel(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_split_ip_Filter2D_fu_56 = new split_ip_Filter2D("grp_split_ip_Filter2D_fu_56");
    grp_split_ip_Filter2D_fu_56->ap_clk(ap_clk);
    grp_split_ip_Filter2D_fu_56->ap_rst(ap_rst);
    grp_split_ip_Filter2D_fu_56->ap_start(grp_split_ip_Filter2D_fu_56_ap_start);
    grp_split_ip_Filter2D_fu_56->ap_done(grp_split_ip_Filter2D_fu_56_ap_done);
    grp_split_ip_Filter2D_fu_56->ap_idle(grp_split_ip_Filter2D_fu_56_ap_idle);
    grp_split_ip_Filter2D_fu_56->ap_ready(grp_split_ip_Filter2D_fu_56_ap_ready);
    grp_split_ip_Filter2D_fu_56->p_src_data_stream_0_V_dout(img_in_data_stream_0_V_dout);
    grp_split_ip_Filter2D_fu_56->p_src_data_stream_0_V_empty_n(img_in_data_stream_0_V_empty_n);
    grp_split_ip_Filter2D_fu_56->p_src_data_stream_0_V_read(grp_split_ip_Filter2D_fu_56_p_src_data_stream_0_V_read);
    grp_split_ip_Filter2D_fu_56->p_src_data_stream_1_V_dout(img_in_data_stream_1_V_dout);
    grp_split_ip_Filter2D_fu_56->p_src_data_stream_1_V_empty_n(img_in_data_stream_1_V_empty_n);
    grp_split_ip_Filter2D_fu_56->p_src_data_stream_1_V_read(grp_split_ip_Filter2D_fu_56_p_src_data_stream_1_V_read);
    grp_split_ip_Filter2D_fu_56->p_src_data_stream_2_V_dout(img_in_data_stream_2_V_dout);
    grp_split_ip_Filter2D_fu_56->p_src_data_stream_2_V_empty_n(img_in_data_stream_2_V_empty_n);
    grp_split_ip_Filter2D_fu_56->p_src_data_stream_2_V_read(grp_split_ip_Filter2D_fu_56_p_src_data_stream_2_V_read);
    grp_split_ip_Filter2D_fu_56->p_dst_data_stream_0_V_din(grp_split_ip_Filter2D_fu_56_p_dst_data_stream_0_V_din);
    grp_split_ip_Filter2D_fu_56->p_dst_data_stream_0_V_full_n(img_out_data_stream_0_V_full_n);
    grp_split_ip_Filter2D_fu_56->p_dst_data_stream_0_V_write(grp_split_ip_Filter2D_fu_56_p_dst_data_stream_0_V_write);
    grp_split_ip_Filter2D_fu_56->p_dst_data_stream_1_V_din(grp_split_ip_Filter2D_fu_56_p_dst_data_stream_1_V_din);
    grp_split_ip_Filter2D_fu_56->p_dst_data_stream_1_V_full_n(img_out_data_stream_1_V_full_n);
    grp_split_ip_Filter2D_fu_56->p_dst_data_stream_1_V_write(grp_split_ip_Filter2D_fu_56_p_dst_data_stream_1_V_write);
    grp_split_ip_Filter2D_fu_56->p_dst_data_stream_2_V_din(grp_split_ip_Filter2D_fu_56_p_dst_data_stream_2_V_din);
    grp_split_ip_Filter2D_fu_56->p_dst_data_stream_2_V_full_n(img_out_data_stream_2_V_full_n);
    grp_split_ip_Filter2D_fu_56->p_dst_data_stream_2_V_write(grp_split_ip_Filter2D_fu_56_p_dst_data_stream_2_V_write);
    grp_split_ip_Filter2D_fu_56->p_kernel_val_0_V_1_read(grp_split_ip_Filter2D_fu_56_p_kernel_val_0_V_1_read);
    grp_split_ip_Filter2D_fu_56->p_kernel_val_0_V_2_read(grp_split_ip_Filter2D_fu_56_p_kernel_val_0_V_2_read);
    grp_split_ip_Filter2D_fu_56->p_kernel_val_1_V_0_read(grp_split_ip_Filter2D_fu_56_p_kernel_val_1_V_0_read);
    grp_split_ip_Filter2D_fu_56->p_kernel_val_1_V_2_read(grp_split_ip_Filter2D_fu_56_p_kernel_val_1_V_2_read);
    grp_split_ip_Filter2D_fu_56->p_kernel_val_2_V_0_read(grp_split_ip_Filter2D_fu_56_p_kernel_val_2_V_0_read);
    grp_split_ip_Filter2D_fu_56->p_kernel_val_2_V_1_read(grp_split_ip_Filter2D_fu_56_p_kernel_val_2_V_1_read);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( tmp_i_reg_96 );
    sensitive << ( grp_split_ip_Filter2D_fu_56_ap_done );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( tmp_i_reg_96 );
    sensitive << ( grp_split_ip_Filter2D_fu_56_ap_done );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_ap_sig_112);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_20);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_66);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( direction_empty_n );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_20 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_112 );

    SC_METHOD(thread_direction_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( direction_empty_n );

    SC_METHOD(thread_direction_read);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_66 );

    SC_METHOD(thread_grp_split_ip_Filter2D_fu_56_ap_start);
    sensitive << ( ap_reg_grp_split_ip_Filter2D_fu_56_ap_start );

    SC_METHOD(thread_grp_split_ip_Filter2D_fu_56_p_kernel_val_0_V_1_read);
    sensitive << ( tmp_i_reg_96 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_split_ip_Filter2D_fu_56_p_kernel_val_0_V_2_read);
    sensitive << ( tmp_i_reg_96 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_split_ip_Filter2D_fu_56_p_kernel_val_1_V_0_read);
    sensitive << ( tmp_i_reg_96 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_split_ip_Filter2D_fu_56_p_kernel_val_1_V_2_read);
    sensitive << ( tmp_i_reg_96 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_split_ip_Filter2D_fu_56_p_kernel_val_2_V_0_read);
    sensitive << ( tmp_i_reg_96 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_split_ip_Filter2D_fu_56_p_kernel_val_2_V_1_read);
    sensitive << ( tmp_i_reg_96 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_img_in_data_stream_0_V_read);
    sensitive << ( tmp_i_reg_96 );
    sensitive << ( grp_split_ip_Filter2D_fu_56_p_src_data_stream_0_V_read );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_img_in_data_stream_1_V_read);
    sensitive << ( tmp_i_reg_96 );
    sensitive << ( grp_split_ip_Filter2D_fu_56_p_src_data_stream_1_V_read );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_img_in_data_stream_2_V_read);
    sensitive << ( tmp_i_reg_96 );
    sensitive << ( grp_split_ip_Filter2D_fu_56_p_src_data_stream_2_V_read );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_img_out_data_stream_0_V_din);
    sensitive << ( tmp_i_reg_96 );
    sensitive << ( grp_split_ip_Filter2D_fu_56_p_dst_data_stream_0_V_din );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_img_out_data_stream_0_V_write);
    sensitive << ( tmp_i_reg_96 );
    sensitive << ( grp_split_ip_Filter2D_fu_56_p_dst_data_stream_0_V_write );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_img_out_data_stream_1_V_din);
    sensitive << ( tmp_i_reg_96 );
    sensitive << ( grp_split_ip_Filter2D_fu_56_p_dst_data_stream_1_V_din );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_img_out_data_stream_1_V_write);
    sensitive << ( tmp_i_reg_96 );
    sensitive << ( grp_split_ip_Filter2D_fu_56_p_dst_data_stream_1_V_write );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_img_out_data_stream_2_V_din);
    sensitive << ( tmp_i_reg_96 );
    sensitive << ( grp_split_ip_Filter2D_fu_56_p_dst_data_stream_2_V_din );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_img_out_data_stream_2_V_write);
    sensitive << ( tmp_i_reg_96 );
    sensitive << ( grp_split_ip_Filter2D_fu_56_p_dst_data_stream_2_V_write );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_tmp_i_fu_90_p2);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( direction_dout );
    sensitive << ( ap_sig_66 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_i_reg_96 );
    sensitive << ( ap_sig_66 );
    sensitive << ( grp_split_ip_Filter2D_fu_56_ap_done );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "01";
    ap_reg_grp_split_ip_Filter2D_fu_56_ap_start = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "split_ip_sobel_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, img_in_data_stream_0_V_dout, "(port)img_in_data_stream_0_V_dout");
    sc_trace(mVcdFile, img_in_data_stream_0_V_empty_n, "(port)img_in_data_stream_0_V_empty_n");
    sc_trace(mVcdFile, img_in_data_stream_0_V_read, "(port)img_in_data_stream_0_V_read");
    sc_trace(mVcdFile, img_in_data_stream_1_V_dout, "(port)img_in_data_stream_1_V_dout");
    sc_trace(mVcdFile, img_in_data_stream_1_V_empty_n, "(port)img_in_data_stream_1_V_empty_n");
    sc_trace(mVcdFile, img_in_data_stream_1_V_read, "(port)img_in_data_stream_1_V_read");
    sc_trace(mVcdFile, img_in_data_stream_2_V_dout, "(port)img_in_data_stream_2_V_dout");
    sc_trace(mVcdFile, img_in_data_stream_2_V_empty_n, "(port)img_in_data_stream_2_V_empty_n");
    sc_trace(mVcdFile, img_in_data_stream_2_V_read, "(port)img_in_data_stream_2_V_read");
    sc_trace(mVcdFile, img_out_data_stream_0_V_din, "(port)img_out_data_stream_0_V_din");
    sc_trace(mVcdFile, img_out_data_stream_0_V_full_n, "(port)img_out_data_stream_0_V_full_n");
    sc_trace(mVcdFile, img_out_data_stream_0_V_write, "(port)img_out_data_stream_0_V_write");
    sc_trace(mVcdFile, img_out_data_stream_1_V_din, "(port)img_out_data_stream_1_V_din");
    sc_trace(mVcdFile, img_out_data_stream_1_V_full_n, "(port)img_out_data_stream_1_V_full_n");
    sc_trace(mVcdFile, img_out_data_stream_1_V_write, "(port)img_out_data_stream_1_V_write");
    sc_trace(mVcdFile, img_out_data_stream_2_V_din, "(port)img_out_data_stream_2_V_din");
    sc_trace(mVcdFile, img_out_data_stream_2_V_full_n, "(port)img_out_data_stream_2_V_full_n");
    sc_trace(mVcdFile, img_out_data_stream_2_V_write, "(port)img_out_data_stream_2_V_write");
    sc_trace(mVcdFile, direction_dout, "(port)direction_dout");
    sc_trace(mVcdFile, direction_empty_n, "(port)direction_empty_n");
    sc_trace(mVcdFile, direction_read, "(port)direction_read");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_20, "ap_sig_20");
    sc_trace(mVcdFile, direction_blk_n, "direction_blk_n");
    sc_trace(mVcdFile, tmp_i_fu_90_p2, "tmp_i_fu_90_p2");
    sc_trace(mVcdFile, tmp_i_reg_96, "tmp_i_reg_96");
    sc_trace(mVcdFile, ap_sig_66, "ap_sig_66");
    sc_trace(mVcdFile, grp_split_ip_Filter2D_fu_56_ap_start, "grp_split_ip_Filter2D_fu_56_ap_start");
    sc_trace(mVcdFile, grp_split_ip_Filter2D_fu_56_ap_done, "grp_split_ip_Filter2D_fu_56_ap_done");
    sc_trace(mVcdFile, grp_split_ip_Filter2D_fu_56_ap_idle, "grp_split_ip_Filter2D_fu_56_ap_idle");
    sc_trace(mVcdFile, grp_split_ip_Filter2D_fu_56_ap_ready, "grp_split_ip_Filter2D_fu_56_ap_ready");
    sc_trace(mVcdFile, grp_split_ip_Filter2D_fu_56_p_src_data_stream_0_V_read, "grp_split_ip_Filter2D_fu_56_p_src_data_stream_0_V_read");
    sc_trace(mVcdFile, grp_split_ip_Filter2D_fu_56_p_src_data_stream_1_V_read, "grp_split_ip_Filter2D_fu_56_p_src_data_stream_1_V_read");
    sc_trace(mVcdFile, grp_split_ip_Filter2D_fu_56_p_src_data_stream_2_V_read, "grp_split_ip_Filter2D_fu_56_p_src_data_stream_2_V_read");
    sc_trace(mVcdFile, grp_split_ip_Filter2D_fu_56_p_dst_data_stream_0_V_din, "grp_split_ip_Filter2D_fu_56_p_dst_data_stream_0_V_din");
    sc_trace(mVcdFile, grp_split_ip_Filter2D_fu_56_p_dst_data_stream_0_V_write, "grp_split_ip_Filter2D_fu_56_p_dst_data_stream_0_V_write");
    sc_trace(mVcdFile, grp_split_ip_Filter2D_fu_56_p_dst_data_stream_1_V_din, "grp_split_ip_Filter2D_fu_56_p_dst_data_stream_1_V_din");
    sc_trace(mVcdFile, grp_split_ip_Filter2D_fu_56_p_dst_data_stream_1_V_write, "grp_split_ip_Filter2D_fu_56_p_dst_data_stream_1_V_write");
    sc_trace(mVcdFile, grp_split_ip_Filter2D_fu_56_p_dst_data_stream_2_V_din, "grp_split_ip_Filter2D_fu_56_p_dst_data_stream_2_V_din");
    sc_trace(mVcdFile, grp_split_ip_Filter2D_fu_56_p_dst_data_stream_2_V_write, "grp_split_ip_Filter2D_fu_56_p_dst_data_stream_2_V_write");
    sc_trace(mVcdFile, grp_split_ip_Filter2D_fu_56_p_kernel_val_0_V_1_read, "grp_split_ip_Filter2D_fu_56_p_kernel_val_0_V_1_read");
    sc_trace(mVcdFile, grp_split_ip_Filter2D_fu_56_p_kernel_val_0_V_2_read, "grp_split_ip_Filter2D_fu_56_p_kernel_val_0_V_2_read");
    sc_trace(mVcdFile, grp_split_ip_Filter2D_fu_56_p_kernel_val_1_V_0_read, "grp_split_ip_Filter2D_fu_56_p_kernel_val_1_V_0_read");
    sc_trace(mVcdFile, grp_split_ip_Filter2D_fu_56_p_kernel_val_1_V_2_read, "grp_split_ip_Filter2D_fu_56_p_kernel_val_1_V_2_read");
    sc_trace(mVcdFile, grp_split_ip_Filter2D_fu_56_p_kernel_val_2_V_0_read, "grp_split_ip_Filter2D_fu_56_p_kernel_val_2_V_0_read");
    sc_trace(mVcdFile, grp_split_ip_Filter2D_fu_56_p_kernel_val_2_V_1_read, "grp_split_ip_Filter2D_fu_56_p_kernel_val_2_V_1_read");
    sc_trace(mVcdFile, ap_reg_grp_split_ip_Filter2D_fu_56_ap_start, "ap_reg_grp_split_ip_Filter2D_fu_56_ap_start");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_112, "ap_sig_112");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

split_ip_sobel::~split_ip_sobel() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete grp_split_ip_Filter2D_fu_56;
}

void split_ip_sobel::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                    !((esl_seteq<1,1,1>(tmp_i_reg_96.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, grp_split_ip_Filter2D_fu_56_ap_done.read())) || (!esl_seteq<1,1,1>(tmp_i_reg_96.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, grp_split_ip_Filter2D_fu_56_ap_done.read()))))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_grp_split_ip_Filter2D_fu_56_ap_start = ap_const_logic_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
              !ap_sig_66.read() && 
              esl_seteq<1,1,1>(tmp_i_fu_90_p2.read(), ap_const_lv1_0)) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
              !ap_sig_66.read() && 
              !esl_seteq<1,1,1>(tmp_i_fu_90_p2.read(), ap_const_lv1_0)))) {
            ap_reg_grp_split_ip_Filter2D_fu_56_ap_start = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_split_ip_Filter2D_fu_56_ap_ready.read())) {
            ap_reg_grp_split_ip_Filter2D_fu_56_ap_start = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && !ap_sig_66.read())) {
        tmp_i_reg_96 = tmp_i_fu_90_p2.read();
    }
}

void split_ip_sobel::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_done_reg.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          !((esl_seteq<1,1,1>(tmp_i_reg_96.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, grp_split_ip_Filter2D_fu_56_ap_done.read())) || (!esl_seteq<1,1,1>(tmp_i_reg_96.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, grp_split_ip_Filter2D_fu_56_ap_done.read())))))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void split_ip_sobel::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void split_ip_sobel::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         !((esl_seteq<1,1,1>(tmp_i_reg_96.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, grp_split_ip_Filter2D_fu_56_ap_done.read())) || (!esl_seteq<1,1,1>(tmp_i_reg_96.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, grp_split_ip_Filter2D_fu_56_ap_done.read()))))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void split_ip_sobel::thread_ap_sig_112() {
    ap_sig_112 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void split_ip_sobel::thread_ap_sig_20() {
    ap_sig_20 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void split_ip_sobel::thread_ap_sig_66() {
    ap_sig_66 = (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(direction_empty_n.read(), ap_const_logic_0));
}

void split_ip_sobel::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_20.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void split_ip_sobel::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_112.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void split_ip_sobel::thread_direction_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        direction_blk_n = direction_empty_n.read();
    } else {
        direction_blk_n = ap_const_logic_1;
    }
}

void split_ip_sobel::thread_direction_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !ap_sig_66.read())) {
        direction_read = ap_const_logic_1;
    } else {
        direction_read = ap_const_logic_0;
    }
}

void split_ip_sobel::thread_grp_split_ip_Filter2D_fu_56_ap_start() {
    grp_split_ip_Filter2D_fu_56_ap_start = ap_reg_grp_split_ip_Filter2D_fu_56_ap_start.read();
}

void split_ip_sobel::thread_grp_split_ip_Filter2D_fu_56_p_kernel_val_0_V_1_read() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        if (!esl_seteq<1,1,1>(tmp_i_reg_96.read(), ap_const_lv1_0)) {
            grp_split_ip_Filter2D_fu_56_p_kernel_val_0_V_1_read = ap_const_lv3_0;
        } else if (esl_seteq<1,1,1>(tmp_i_reg_96.read(), ap_const_lv1_0)) {
            grp_split_ip_Filter2D_fu_56_p_kernel_val_0_V_1_read = ap_const_lv3_6;
        } else {
            grp_split_ip_Filter2D_fu_56_p_kernel_val_0_V_1_read = "XXX";
        }
    } else {
        grp_split_ip_Filter2D_fu_56_p_kernel_val_0_V_1_read = "XXX";
    }
}

void split_ip_sobel::thread_grp_split_ip_Filter2D_fu_56_p_kernel_val_0_V_2_read() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        if (!esl_seteq<1,1,1>(tmp_i_reg_96.read(), ap_const_lv1_0)) {
            grp_split_ip_Filter2D_fu_56_p_kernel_val_0_V_2_read = ap_const_lv2_1;
        } else if (esl_seteq<1,1,1>(tmp_i_reg_96.read(), ap_const_lv1_0)) {
            grp_split_ip_Filter2D_fu_56_p_kernel_val_0_V_2_read = ap_const_lv2_3;
        } else {
            grp_split_ip_Filter2D_fu_56_p_kernel_val_0_V_2_read =  (sc_lv<2>) ("XX");
        }
    } else {
        grp_split_ip_Filter2D_fu_56_p_kernel_val_0_V_2_read =  (sc_lv<2>) ("XX");
    }
}

void split_ip_sobel::thread_grp_split_ip_Filter2D_fu_56_p_kernel_val_1_V_0_read() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        if (!esl_seteq<1,1,1>(tmp_i_reg_96.read(), ap_const_lv1_0)) {
            grp_split_ip_Filter2D_fu_56_p_kernel_val_1_V_0_read = ap_const_lv2_2;
        } else if (esl_seteq<1,1,1>(tmp_i_reg_96.read(), ap_const_lv1_0)) {
            grp_split_ip_Filter2D_fu_56_p_kernel_val_1_V_0_read = ap_const_lv2_0;
        } else {
            grp_split_ip_Filter2D_fu_56_p_kernel_val_1_V_0_read =  (sc_lv<2>) ("XX");
        }
    } else {
        grp_split_ip_Filter2D_fu_56_p_kernel_val_1_V_0_read =  (sc_lv<2>) ("XX");
    }
}

void split_ip_sobel::thread_grp_split_ip_Filter2D_fu_56_p_kernel_val_1_V_2_read() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        if (!esl_seteq<1,1,1>(tmp_i_reg_96.read(), ap_const_lv1_0)) {
            grp_split_ip_Filter2D_fu_56_p_kernel_val_1_V_2_read = ap_const_lv3_2;
        } else if (esl_seteq<1,1,1>(tmp_i_reg_96.read(), ap_const_lv1_0)) {
            grp_split_ip_Filter2D_fu_56_p_kernel_val_1_V_2_read = ap_const_lv3_0;
        } else {
            grp_split_ip_Filter2D_fu_56_p_kernel_val_1_V_2_read = "XXX";
        }
    } else {
        grp_split_ip_Filter2D_fu_56_p_kernel_val_1_V_2_read = "XXX";
    }
}

void split_ip_sobel::thread_grp_split_ip_Filter2D_fu_56_p_kernel_val_2_V_0_read() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        if (!esl_seteq<1,1,1>(tmp_i_reg_96.read(), ap_const_lv1_0)) {
            grp_split_ip_Filter2D_fu_56_p_kernel_val_2_V_0_read = ap_const_lv2_3;
        } else if (esl_seteq<1,1,1>(tmp_i_reg_96.read(), ap_const_lv1_0)) {
            grp_split_ip_Filter2D_fu_56_p_kernel_val_2_V_0_read = ap_const_lv2_1;
        } else {
            grp_split_ip_Filter2D_fu_56_p_kernel_val_2_V_0_read =  (sc_lv<2>) ("XX");
        }
    } else {
        grp_split_ip_Filter2D_fu_56_p_kernel_val_2_V_0_read =  (sc_lv<2>) ("XX");
    }
}

void split_ip_sobel::thread_grp_split_ip_Filter2D_fu_56_p_kernel_val_2_V_1_read() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        if (!esl_seteq<1,1,1>(tmp_i_reg_96.read(), ap_const_lv1_0)) {
            grp_split_ip_Filter2D_fu_56_p_kernel_val_2_V_1_read = ap_const_lv4_0;
        } else if (esl_seteq<1,1,1>(tmp_i_reg_96.read(), ap_const_lv1_0)) {
            grp_split_ip_Filter2D_fu_56_p_kernel_val_2_V_1_read = ap_const_lv4_2;
        } else {
            grp_split_ip_Filter2D_fu_56_p_kernel_val_2_V_1_read =  (sc_lv<4>) ("XXXX");
        }
    } else {
        grp_split_ip_Filter2D_fu_56_p_kernel_val_2_V_1_read =  (sc_lv<4>) ("XXXX");
    }
}

void split_ip_sobel::thread_img_in_data_stream_0_V_read() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          esl_seteq<1,1,1>(tmp_i_reg_96.read(), ap_const_lv1_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          !esl_seteq<1,1,1>(tmp_i_reg_96.read(), ap_const_lv1_0)))) {
        img_in_data_stream_0_V_read = grp_split_ip_Filter2D_fu_56_p_src_data_stream_0_V_read.read();
    } else {
        img_in_data_stream_0_V_read = ap_const_logic_0;
    }
}

void split_ip_sobel::thread_img_in_data_stream_1_V_read() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          esl_seteq<1,1,1>(tmp_i_reg_96.read(), ap_const_lv1_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          !esl_seteq<1,1,1>(tmp_i_reg_96.read(), ap_const_lv1_0)))) {
        img_in_data_stream_1_V_read = grp_split_ip_Filter2D_fu_56_p_src_data_stream_1_V_read.read();
    } else {
        img_in_data_stream_1_V_read = ap_const_logic_0;
    }
}

void split_ip_sobel::thread_img_in_data_stream_2_V_read() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          esl_seteq<1,1,1>(tmp_i_reg_96.read(), ap_const_lv1_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          !esl_seteq<1,1,1>(tmp_i_reg_96.read(), ap_const_lv1_0)))) {
        img_in_data_stream_2_V_read = grp_split_ip_Filter2D_fu_56_p_src_data_stream_2_V_read.read();
    } else {
        img_in_data_stream_2_V_read = ap_const_logic_0;
    }
}

void split_ip_sobel::thread_img_out_data_stream_0_V_din() {
    img_out_data_stream_0_V_din = grp_split_ip_Filter2D_fu_56_p_dst_data_stream_0_V_din.read();
}

void split_ip_sobel::thread_img_out_data_stream_0_V_write() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          esl_seteq<1,1,1>(tmp_i_reg_96.read(), ap_const_lv1_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          !esl_seteq<1,1,1>(tmp_i_reg_96.read(), ap_const_lv1_0)))) {
        img_out_data_stream_0_V_write = grp_split_ip_Filter2D_fu_56_p_dst_data_stream_0_V_write.read();
    } else {
        img_out_data_stream_0_V_write = ap_const_logic_0;
    }
}

void split_ip_sobel::thread_img_out_data_stream_1_V_din() {
    img_out_data_stream_1_V_din = grp_split_ip_Filter2D_fu_56_p_dst_data_stream_1_V_din.read();
}

void split_ip_sobel::thread_img_out_data_stream_1_V_write() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          esl_seteq<1,1,1>(tmp_i_reg_96.read(), ap_const_lv1_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          !esl_seteq<1,1,1>(tmp_i_reg_96.read(), ap_const_lv1_0)))) {
        img_out_data_stream_1_V_write = grp_split_ip_Filter2D_fu_56_p_dst_data_stream_1_V_write.read();
    } else {
        img_out_data_stream_1_V_write = ap_const_logic_0;
    }
}

void split_ip_sobel::thread_img_out_data_stream_2_V_din() {
    img_out_data_stream_2_V_din = grp_split_ip_Filter2D_fu_56_p_dst_data_stream_2_V_din.read();
}

void split_ip_sobel::thread_img_out_data_stream_2_V_write() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          esl_seteq<1,1,1>(tmp_i_reg_96.read(), ap_const_lv1_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          !esl_seteq<1,1,1>(tmp_i_reg_96.read(), ap_const_lv1_0)))) {
        img_out_data_stream_2_V_write = grp_split_ip_Filter2D_fu_56_p_dst_data_stream_2_V_write.read();
    } else {
        img_out_data_stream_2_V_write = ap_const_logic_0;
    }
}

void split_ip_sobel::thread_tmp_i_fu_90_p2() {
    tmp_i_fu_90_p2 = (!direction_dout.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<1>(): sc_lv<1>(direction_dout.read() == ap_const_lv8_1);
}

void split_ip_sobel::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!ap_sig_66.read()) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (!((esl_seteq<1,1,1>(tmp_i_reg_96.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, grp_split_ip_Filter2D_fu_56_ap_done.read())) || (!esl_seteq<1,1,1>(tmp_i_reg_96.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, grp_split_ip_Filter2D_fu_56_ap_done.read())))) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<2>) ("XX");
            break;
    }
}

}

