-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2016.2
-- Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pynq_filters_operator_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    v : IN STD_LOGIC_VECTOR (63 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of pynq_filters_operator_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv11_7FF : STD_LOGIC_VECTOR (10 downto 0) := "11111111111";
    constant ap_const_lv52_0 : STD_LOGIC_VECTOR (51 downto 0) := "0000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv54_0 : STD_LOGIC_VECTOR (53 downto 0) := "000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv63_0 : STD_LOGIC_VECTOR (62 downto 0) := "000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv12_433 : STD_LOGIC_VECTOR (11 downto 0) := "010000110011";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv11_433 : STD_LOGIC_VECTOR (10 downto 0) := "10000110011";
    constant ap_const_lv12_36 : STD_LOGIC_VECTOR (11 downto 0) := "000000110110";
    constant ap_const_lv11_601 : STD_LOGIC_VECTOR (10 downto 0) := "11000000001";
    constant ap_const_lv12_9 : STD_LOGIC_VECTOR (11 downto 0) := "000000001001";
    constant ap_const_lv12_A : STD_LOGIC_VECTOR (11 downto 0) := "000000001010";
    constant ap_const_lv10_3FF : STD_LOGIC_VECTOR (9 downto 0) := "1111111111";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv12_FFF : STD_LOGIC_VECTOR (11 downto 0) := "111111111111";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv12_B : STD_LOGIC_VECTOR (11 downto 0) := "000000001011";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv54_3FFFFFFFFFFFFF : STD_LOGIC_VECTOR (53 downto 0) := "111111111111111111111111111111111111111111111111111111";
    constant ap_const_lv10_1FF : STD_LOGIC_VECTOR (9 downto 0) := "0111111111";
    constant ap_const_lv10_200 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal isneg_reg_882 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_isneg_reg_882_pp0_iter1 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_fu_132_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal p_Result_s_reg_892 : STD_LOGIC_VECTOR (53 downto 0);
    signal man_V_1_fu_136_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal man_V_1_reg_897 : STD_LOGIC_VECTOR (53 downto 0);
    signal F2_fu_148_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal F2_reg_902 : STD_LOGIC_VECTOR (11 downto 0);
    signal QUAN_INC_fu_154_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal QUAN_INC_reg_910 : STD_LOGIC_VECTOR (0 downto 0);
    signal F2_2_fu_166_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal F2_2_reg_916 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_reg_ppstg_F2_2_reg_916_pp0_iter1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_2_fu_174_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_923 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_tmp_2_reg_923_pp0_iter1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_fu_180_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_reg_930 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_16_fu_200_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_16_reg_935 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_tmp_16_reg_935_pp0_iter1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_tmp_16_reg_935_pp0_iter2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_27_fu_224_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_27_reg_941 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_tmp_27_reg_941_pp0_iter1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_tmp_27_reg_941_pp0_iter2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp60_demorgan_fu_230_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp60_demorgan_reg_947 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_sel_tmp60_demorgan_reg_947_pp0_iter1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_sel_tmp60_demorgan_reg_947_pp0_iter2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_20_fu_244_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_20_reg_953 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_7_fu_248_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_reg_959 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_34_fu_310_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_34_reg_964 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_4_fu_322_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_Val2_4_reg_969 : STD_LOGIC_VECTOR (9 downto 0);
    signal sel_tmp2_fu_347_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp2_reg_975 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp3_fu_352_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp3_reg_980 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp12_demorgan_fu_358_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp12_demorgan_reg_985 : STD_LOGIC_VECTOR (0 downto 0);
    signal carry_1_i_fu_380_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal carry_1_i_reg_990 : STD_LOGIC_VECTOR (0 downto 0);
    signal pos1_fu_386_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal pos1_reg_997 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_17_fu_404_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_17_reg_1002 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev_fu_418_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev_reg_1009 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_ones_1_fu_444_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_ones_1_reg_1016 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_39_reg_1023 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_21_fu_458_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_21_reg_1028 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range2_all_ones_fu_480_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range2_all_ones_reg_1034 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_24_fu_486_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_24_reg_1039 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_zeros_1_fu_498_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_zeros_1_reg_1044 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp11_fu_516_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp11_reg_1049 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_5_fu_577_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_Val2_5_reg_1055 : STD_LOGIC_VECTOR (9 downto 0);
    signal sign_assign_fu_749_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sign_assign_reg_1062 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_fu_779_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_reg_1068 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge121_demorgan_i_fu_785_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge121_demorgan_i_reg_1074 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_2_fu_72_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal loc_V_fu_76_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal loc_V_1_fu_86_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal tmp_i_fu_90_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_i_54_fu_96_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_124_p3 : STD_LOGIC_VECTOR (52 downto 0);
    signal tmp_10_fu_108_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal tmp_6_fu_120_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_s_fu_160_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp6_fu_186_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_15_fu_194_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sel_tmp17_demorgan_fu_206_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_fu_142_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp17_fu_212_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp18_fu_218_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_demorgan_fu_102_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_s_fu_236_p3 : STD_LOGIC_VECTOR (53 downto 0);
    signal F2_2_cast_fu_241_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_9_fu_253_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal tmp_5_fu_257_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal tmp_23_fu_263_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_s_fu_267_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_12_fu_286_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_23_cast_fu_291_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_11_fu_281_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_33_fu_295_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_3_fu_274_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal qb_fu_303_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_fu_318_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_35_fu_328_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp1_fu_342_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_not_fu_362_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_sel_tmp_fu_368_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_14_fu_336_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_374_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal pos2_fu_395_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_37_fu_410_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal pos1_cast_fu_391_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_18_fu_424_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal tmp_19_fu_428_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal lD_fu_434_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp7_fu_438_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal pos2_cast_fu_400_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_22_fu_464_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal Range2_V_1_fu_468_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal r_V_fu_474_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal tmp_24_not_fu_504_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_25_fu_492_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp10_fu_510_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_19_cast_fu_525_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal F2_2_cast3_fu_522_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal tmp_3_fu_528_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal sel_tmp_fu_538_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sel_tmp7_fu_550_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp8_fu_555_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp4_fu_544_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sel_tmp5_fu_567_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp6_fu_572_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_29_fu_534_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sel_tmp9_fu_560_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal rev5_fu_593_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond115_i_fu_598_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range2_all_ones_1_i_fu_603_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_zeros_fu_619_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond117_i_fu_610_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_ones_fu_614_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp12_fu_633_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_119_i_fu_629_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_122_i_fu_624_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp13_fu_646_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_ones_2_i_fu_638_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_zeros_2_i_fu_653_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal carry_1_not_i_fu_668_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range2_all_ones_1_not_i_fu_673_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_40_fu_691_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge123_i_fu_679_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_ones_2_mux_i_fu_685_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_120_i_fu_698_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_ones_2_i_55_fu_712_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_ones_fu_704_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp14_fu_723_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newsignbit_fu_585_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp8_fu_734_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp16_fu_745_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_26_fu_717_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp15_fu_740_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_zeros_fu_661_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_zeros_not_fu_757_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_zeros_0_not_i_fu_763_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i_fu_768_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_28_fu_774_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_ones_0_i_fu_728_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge121_i_fu_791_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_fu_796_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sign_assign_not_fu_806_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp9_fu_811_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i_i_fu_801_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_30_fu_835_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_s_56_fu_828_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sel_tmp62_demorgan_fu_847_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp19_fu_840_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal brmerge_fu_816_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp21_fu_858_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp28_fu_863_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp22_fu_869_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_16_mux_fu_821_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sel_tmp20_fu_851_p3 : STD_LOGIC_VECTOR (9 downto 0);


begin



    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                F2_2_reg_916 <= F2_2_fu_166_p3;
                F2_reg_902 <= F2_fu_148_p2;
                QUAN_INC_reg_910 <= QUAN_INC_fu_154_p2;
                Range1_all_ones_1_reg_1016 <= Range1_all_ones_1_fu_444_p2;
                Range1_all_zeros_1_reg_1044 <= Range1_all_zeros_1_fu_498_p2;
                Range2_all_ones_reg_1034 <= Range2_all_ones_fu_480_p2;
                ap_reg_ppstg_F2_2_reg_916_pp0_iter1 <= F2_2_reg_916;
                ap_reg_ppstg_isneg_reg_882_pp0_iter1 <= isneg_reg_882;
                ap_reg_ppstg_sel_tmp60_demorgan_reg_947_pp0_iter1 <= sel_tmp60_demorgan_reg_947;
                ap_reg_ppstg_sel_tmp60_demorgan_reg_947_pp0_iter2 <= ap_reg_ppstg_sel_tmp60_demorgan_reg_947_pp0_iter1;
                ap_reg_ppstg_tmp_16_reg_935_pp0_iter1 <= tmp_16_reg_935;
                ap_reg_ppstg_tmp_16_reg_935_pp0_iter2 <= ap_reg_ppstg_tmp_16_reg_935_pp0_iter1;
                ap_reg_ppstg_tmp_27_reg_941_pp0_iter1 <= tmp_27_reg_941;
                ap_reg_ppstg_tmp_27_reg_941_pp0_iter2 <= ap_reg_ppstg_tmp_27_reg_941_pp0_iter1;
                ap_reg_ppstg_tmp_2_reg_923_pp0_iter1 <= tmp_2_reg_923;
                brmerge121_demorgan_i_reg_1074 <= brmerge121_demorgan_i_fu_785_p2;
                carry_1_i_reg_990 <= carry_1_i_fu_380_p2;
                isneg_reg_882 <= p_Val2_2_fu_72_p1(63 downto 63);
                man_V_1_reg_897 <= man_V_1_fu_136_p2;
                overflow_reg_1068 <= overflow_fu_779_p2;
                    p_Result_s_reg_892(51 downto 0) <= p_Result_s_fu_132_p1(51 downto 0);
                p_Val2_4_reg_969 <= p_Val2_4_fu_322_p2;
                p_Val2_5_reg_1055 <= p_Val2_5_fu_577_p3;
                pos1_reg_997 <= pos1_fu_386_p2;
                rev_reg_1009 <= rev_fu_418_p2;
                sel_tmp11_reg_1049 <= sel_tmp11_fu_516_p2;
                sel_tmp12_demorgan_reg_985 <= sel_tmp12_demorgan_fu_358_p2;
                sel_tmp2_reg_975 <= sel_tmp2_fu_347_p2;
                sel_tmp3_reg_980 <= sel_tmp3_fu_352_p2;
                sel_tmp60_demorgan_reg_947 <= sel_tmp60_demorgan_fu_230_p2;
                sign_assign_reg_1062 <= sign_assign_fu_749_p3;
                tmp_16_reg_935 <= tmp_16_fu_200_p2;
                tmp_17_reg_1002 <= tmp_17_fu_404_p2;
                tmp_20_reg_953 <= tmp_20_fu_244_p1;
                tmp_21_reg_1028 <= tmp_21_fu_458_p2;
                tmp_24_reg_1039 <= tmp_24_fu_486_p2;
                tmp_27_reg_941 <= tmp_27_fu_224_p2;
                tmp_2_reg_923 <= tmp_2_fu_174_p2;
                tmp_34_reg_964 <= p_Val2_3_fu_274_p3(9 downto 9);
                tmp_39_reg_1023 <= pos2_fu_395_p2(11 downto 11);
                tmp_4_reg_930 <= tmp_4_fu_180_p2;
                tmp_7_reg_959 <= tmp_7_fu_248_p2;
            end if;
        end if;
    end process;
    p_Result_s_reg_892(53 downto 52) <= "01";
        F2_2_cast3_fu_522_p1 <= std_logic_vector(resize(signed(ap_reg_ppstg_F2_2_reg_916_pp0_iter1),19));

        F2_2_cast_fu_241_p1 <= std_logic_vector(resize(signed(F2_2_reg_916),32));

    F2_2_fu_166_p3 <= 
        F2_fu_148_p2 when (QUAN_INC_fu_154_p2(0) = '1') else 
        tmp_s_fu_160_p2;
    F2_fu_148_p2 <= std_logic_vector(unsigned(ap_const_lv12_433) - unsigned(tmp_6_fu_120_p1));
    QUAN_INC_fu_154_p2 <= "1" when (signed(F2_fu_148_p2) > signed(ap_const_lv12_0)) else "0";
    Range1_all_ones_1_fu_444_p2 <= (tmp7_fu_438_p2 and tmp_17_fu_404_p2);
    Range1_all_ones_2_i_55_fu_712_p2 <= (carry_1_i_reg_990 and Range1_all_ones_2_i_fu_638_p3);
    Range1_all_ones_2_i_fu_638_p3 <= 
        Range1_all_ones_fu_614_p2 when (or_cond117_i_fu_610_p2(0) = '1') else 
        sel_tmp12_fu_633_p3;
    Range1_all_ones_2_mux_i_fu_685_p2 <= (Range1_all_ones_2_i_fu_638_p3 and carry_1_not_i_fu_668_p2);
    Range1_all_ones_fu_614_p2 <= (Range2_all_ones_1_i_fu_603_p3 and Range1_all_ones_1_reg_1016);
    Range1_all_zeros_1_fu_498_p2 <= "1" when (p_Val2_s_fu_236_p3 = ap_const_lv54_0) else "0";
    Range1_all_zeros_2_i_fu_653_p3 <= 
        p_122_i_fu_624_p2 when (or_cond117_i_fu_610_p2(0) = '1') else 
        sel_tmp13_fu_646_p3;
    Range1_all_zeros_fu_619_p2 <= (Range1_all_ones_1_reg_1016 xor ap_const_lv1_1);
    Range2_V_1_fu_468_p2 <= std_logic_vector(shift_right(unsigned(p_Val2_s_fu_236_p3),to_integer(unsigned('0' & tmp_22_fu_464_p1(31-1 downto 0)))));
    Range2_all_ones_1_i_fu_603_p3 <= 
        Range2_all_ones_reg_1034 when (or_cond115_i_fu_598_p2(0) = '1') else 
        rev5_fu_593_p2;
    Range2_all_ones_1_not_i_fu_673_p2 <= (Range2_all_ones_1_i_fu_603_p3 xor ap_const_lv1_1);
    Range2_all_ones_fu_480_p2 <= "1" when (Range2_V_1_fu_468_p2 = r_V_fu_474_p2) else "0";
    ap_return <= 
        p_Val2_16_mux_fu_821_p3 when (sel_tmp22_fu_869_p2(0) = '1') else 
        sel_tmp20_fu_851_p3;
    brmerge121_demorgan_i_fu_785_p2 <= (newsignbit_fu_585_p3 and deleted_ones_0_i_fu_728_p2);
    brmerge121_i_fu_791_p2 <= (brmerge121_demorgan_i_reg_1074 xor ap_const_lv1_1);
    brmerge123_i_fu_679_p2 <= (carry_1_not_i_fu_668_p2 or Range2_all_ones_1_not_i_fu_673_p2);
    brmerge_fu_816_p2 <= (tmp9_fu_811_p2 or brmerge121_demorgan_i_reg_1074);
    brmerge_i_fu_768_p2 <= (newsignbit_fu_585_p3 or deleted_zeros_0_not_i_fu_763_p2);
    brmerge_i_i_fu_801_p2 <= (underflow_fu_796_p2 or overflow_reg_1068);
    carry_1_i_fu_380_p2 <= (tmp_fu_374_p2 and sel_tmp3_fu_352_p2);
    carry_1_not_i_fu_668_p2 <= (carry_1_i_reg_990 xor ap_const_lv1_1);
    deleted_ones_0_i_fu_728_p2 <= (deleted_ones_fu_704_p3 or sel_tmp14_fu_723_p2);
    deleted_ones_fu_704_p3 <= 
        Range1_all_ones_2_mux_i_fu_685_p2 when (brmerge123_i_fu_679_p2(0) = '1') else 
        p_120_i_fu_698_p2;
    deleted_zeros_0_not_i_fu_763_p2 <= (tmp_17_reg_1002 and deleted_zeros_not_fu_757_p2);
    deleted_zeros_fu_661_p3 <= 
        Range1_all_ones_2_i_fu_638_p3 when (carry_1_i_reg_990(0) = '1') else 
        Range1_all_zeros_2_i_fu_653_p3;
    deleted_zeros_not_fu_757_p2 <= (deleted_zeros_fu_661_p3 xor ap_const_lv1_1);
    lD_fu_434_p1 <= tmp_19_fu_428_p2(1 - 1 downto 0);
    loc_V_1_fu_86_p1 <= p_Val2_2_fu_72_p1(52 - 1 downto 0);
    loc_V_fu_76_p4 <= p_Val2_2_fu_72_p1(62 downto 52);
    man_V_1_fu_136_p2 <= std_logic_vector(unsigned(ap_const_lv54_0) - unsigned(p_Result_s_fu_132_p1));
    newsignbit_fu_585_p3 <= p_Val2_5_fu_577_p3(9 downto 9);
    not_sel_tmp_fu_368_p2 <= (sel_tmp12_demorgan_fu_358_p2 or tmp_7_not_fu_362_p2);
    or_cond115_i_fu_598_p2 <= (tmp_21_reg_1028 and rev5_fu_593_p2);
    or_cond117_i_fu_610_p2 <= (tmp_21_reg_1028 and rev_reg_1009);
    overflow_fu_779_p2 <= (brmerge_i_fu_768_p2 and tmp_28_fu_774_p2);
    p_119_i_fu_629_p2 <= (Range1_all_zeros_1_reg_1044 or rev_reg_1009);
    p_120_i_fu_698_p2 <= (tmp_40_fu_691_p3 or Range1_all_zeros_fu_619_p2);
    p_122_i_fu_624_p2 <= (tmp_24_reg_1039 and Range1_all_zeros_fu_619_p2);
    p_Result_s_fu_132_p1 <= std_logic_vector(resize(unsigned(tmp_1_fu_124_p3),54));
    p_Val2_16_mux_fu_821_p3 <= 
        ap_const_lv10_1FF when (brmerge_i_i_fu_801_p2(0) = '1') else 
        p_Val2_5_reg_1055;
    p_Val2_2_fu_72_p1 <= v;
    p_Val2_3_fu_274_p3 <= 
        tmp_23_fu_263_p1 when (tmp_4_reg_930(0) = '1') else 
        p_s_fu_267_p3;
    p_Val2_4_fu_322_p2 <= std_logic_vector(unsigned(p_Val2_3_fu_274_p3) + unsigned(tmp_13_fu_318_p1));
    p_Val2_5_fu_577_p3 <= 
        tmp_29_fu_534_p1 when (sel_tmp6_fu_572_p2(0) = '1') else 
        sel_tmp9_fu_560_p3;
    p_Val2_s_56_fu_828_p3 <= 
        ap_const_lv10_0 when (ap_reg_ppstg_tmp_27_reg_941_pp0_iter2(0) = '1') else 
        ap_const_lv10_200;
    p_Val2_s_fu_236_p3 <= 
        man_V_1_reg_897 when (isneg_reg_882(0) = '1') else 
        p_Result_s_reg_892;
    p_s_fu_267_p3 <= 
        ap_const_lv10_3FF when (isneg_reg_882(0) = '1') else 
        ap_const_lv10_0;
        pos1_cast_fu_391_p1 <= std_logic_vector(resize(signed(pos1_fu_386_p2),32));

    pos1_fu_386_p2 <= std_logic_vector(unsigned(ap_const_lv12_A) + unsigned(F2_reg_902));
        pos2_cast_fu_400_p1 <= std_logic_vector(resize(signed(pos2_fu_395_p2),32));

    pos2_fu_395_p2 <= std_logic_vector(unsigned(ap_const_lv12_B) + unsigned(F2_reg_902));
    qb_fu_303_p3 <= 
        isneg_reg_882 when (tmp_11_fu_281_p2(0) = '1') else 
        tmp_33_fu_295_p3;
    r_V_fu_474_p2 <= std_logic_vector(shift_right(unsigned(ap_const_lv54_3FFFFFFFFFFFFF),to_integer(unsigned('0' & tmp_22_fu_464_p1(31-1 downto 0)))));
    rev5_fu_593_p2 <= (tmp_39_reg_1023 xor ap_const_lv1_1);
    rev_fu_418_p2 <= (tmp_37_fu_410_p3 xor ap_const_lv1_1);
    sel_tmp10_fu_510_p2 <= (tmp_37_fu_410_p3 or tmp_24_not_fu_504_p2);
    sel_tmp11_fu_516_p2 <= (tmp_25_fu_492_p2 and sel_tmp10_fu_510_p2);
    sel_tmp12_demorgan_fu_358_p2 <= (tmp_2_reg_923 or QUAN_INC_reg_910);
    sel_tmp12_fu_633_p3 <= 
        Range1_all_ones_1_reg_1016 when (sel_tmp11_reg_1049(0) = '1') else 
        rev_reg_1009;
    sel_tmp13_fu_646_p3 <= 
        Range1_all_zeros_fu_619_p2 when (sel_tmp11_reg_1049(0) = '1') else 
        p_119_i_fu_629_p2;
    sel_tmp14_fu_723_p2 <= (tmp_17_reg_1002 xor ap_const_lv1_1);
    sel_tmp15_fu_740_p2 <= (tmp8_fu_734_p2 and ap_reg_ppstg_isneg_reg_882_pp0_iter1);
    sel_tmp16_fu_745_p2 <= (tmp_17_reg_1002 and ap_reg_ppstg_isneg_reg_882_pp0_iter1);
    sel_tmp17_demorgan_fu_206_p2 <= (tmp_i_fu_90_p2 and tmp_i_54_fu_96_p2);
    sel_tmp17_fu_212_p2 <= (sel_tmp17_demorgan_fu_206_p2 xor ap_const_lv1_1);
    sel_tmp18_fu_218_p2 <= (tmp_8_fu_142_p2 and sel_tmp17_fu_212_p2);
    sel_tmp19_fu_840_p3 <= 
        p_Val2_s_56_fu_828_p3 when (tmp_30_fu_835_p2(0) = '1') else 
        p_Val2_5_reg_1055;
    sel_tmp1_fu_342_p2 <= (tmp_2_reg_923 xor ap_const_lv1_1);
    sel_tmp20_fu_851_p3 <= 
        sel_tmp19_fu_840_p3 when (sel_tmp62_demorgan_fu_847_p2(0) = '1') else 
        p_Val2_5_reg_1055;
    sel_tmp21_fu_858_p2 <= (ap_reg_ppstg_sel_tmp60_demorgan_reg_947_pp0_iter2 xor ap_const_lv1_1);
    sel_tmp22_fu_869_p2 <= (tmp28_fu_863_p2 and ap_reg_ppstg_tmp_16_reg_935_pp0_iter2);
    sel_tmp2_fu_347_p2 <= (QUAN_INC_reg_910 and sel_tmp1_fu_342_p2);
    sel_tmp3_fu_352_p2 <= (sel_tmp2_fu_347_p2 and tmp_34_fu_310_p3);
    sel_tmp4_fu_544_p3 <= 
        p_Val2_4_reg_969 when (sel_tmp3_reg_980(0) = '1') else 
        sel_tmp_fu_538_p3;
    sel_tmp5_fu_567_p2 <= (sel_tmp12_demorgan_reg_985 xor ap_const_lv1_1);
    sel_tmp60_demorgan_fu_230_p2 <= (tmp_demorgan_fu_102_p2 or tmp_8_fu_142_p2);
    sel_tmp62_demorgan_fu_847_p2 <= (ap_reg_ppstg_sel_tmp60_demorgan_reg_947_pp0_iter2 or ap_reg_ppstg_tmp_16_reg_935_pp0_iter2);
    sel_tmp6_fu_572_p2 <= (tmp_7_reg_959 and sel_tmp5_fu_567_p2);
    sel_tmp7_fu_550_p2 <= (tmp_34_reg_964 xor ap_const_lv1_1);
    sel_tmp8_fu_555_p2 <= (sel_tmp2_reg_975 and sel_tmp7_fu_550_p2);
    sel_tmp9_fu_560_p3 <= 
        p_Val2_4_reg_969 when (sel_tmp8_fu_555_p2(0) = '1') else 
        sel_tmp4_fu_544_p3;
    sel_tmp_fu_538_p3 <= 
        tmp_20_reg_953 when (ap_reg_ppstg_tmp_2_reg_923_pp0_iter1(0) = '1') else 
        ap_const_lv10_0;
    sign_assign_fu_749_p3 <= 
        tmp_26_fu_717_p2 when (sel_tmp16_fu_745_p2(0) = '1') else 
        sel_tmp15_fu_740_p2;
    sign_assign_not_fu_806_p2 <= (sign_assign_reg_1062 xor ap_const_lv1_1);
    tmp28_fu_863_p2 <= (brmerge_fu_816_p2 and sel_tmp21_fu_858_p2);
    tmp6_fu_186_p3 <= (ap_const_lv11_601 & QUAN_INC_fu_154_p2);
    tmp7_fu_438_p2 <= (lD_fu_434_p1 and rev_fu_418_p2);
    tmp8_fu_734_p2 <= (newsignbit_fu_585_p3 and sel_tmp14_fu_723_p2);
    tmp9_fu_811_p2 <= (overflow_reg_1068 or sign_assign_not_fu_806_p2);
    tmp_10_fu_108_p1 <= p_Val2_2_fu_72_p1(63 - 1 downto 0);
    tmp_11_fu_281_p2 <= "1" when (signed(F2_reg_902) > signed(ap_const_lv12_36)) else "0";
    tmp_12_fu_286_p2 <= std_logic_vector(signed(ap_const_lv12_FFF) + signed(F2_reg_902));
    tmp_13_fu_318_p1 <= std_logic_vector(resize(unsigned(qb_fu_303_p3),10));
    tmp_14_fu_336_p2 <= (tmp_35_fu_328_p3 xor ap_const_lv1_1);
    tmp_15_fu_194_p2 <= std_logic_vector(unsigned(tmp6_fu_186_p3) + unsigned(tmp_6_fu_120_p1));
    tmp_16_fu_200_p2 <= "1" when (signed(tmp_15_fu_194_p2) > signed(ap_const_lv12_9)) else "0";
    tmp_17_fu_404_p2 <= "1" when (signed(pos1_fu_386_p2) < signed(ap_const_lv12_36)) else "0";
    tmp_18_fu_424_p1 <= std_logic_vector(resize(unsigned(pos1_cast_fu_391_p1),54));
        tmp_19_cast_fu_525_p1 <= std_logic_vector(resize(signed(tmp_20_reg_953),19));

    tmp_19_fu_428_p2 <= std_logic_vector(shift_right(signed(p_Val2_s_fu_236_p3),to_integer(unsigned('0' & tmp_18_fu_424_p1(31-1 downto 0)))));
    tmp_1_fu_124_p3 <= (ap_const_lv1_1 & loc_V_1_fu_86_p1);
    tmp_20_fu_244_p1 <= p_Val2_s_fu_236_p3(10 - 1 downto 0);
    tmp_21_fu_458_p2 <= "1" when (signed(pos2_fu_395_p2) < signed(ap_const_lv12_36)) else "0";
    tmp_22_fu_464_p1 <= std_logic_vector(resize(unsigned(pos2_cast_fu_400_p1),54));
    tmp_23_cast_fu_291_p1 <= std_logic_vector(resize(unsigned(tmp_12_fu_286_p2),32));
    tmp_23_fu_263_p1 <= tmp_5_fu_257_p2(10 - 1 downto 0);
    tmp_24_fu_486_p2 <= "1" when (Range2_V_1_fu_468_p2 = ap_const_lv54_0) else "0";
    tmp_24_not_fu_504_p2 <= (tmp_21_fu_458_p2 xor ap_const_lv1_1);
    tmp_25_fu_492_p2 <= "1" when (pos2_fu_395_p2 = ap_const_lv12_36) else "0";
    tmp_26_fu_717_p2 <= (Range1_all_ones_2_i_55_fu_712_p2 xor ap_const_lv1_1);
    tmp_27_fu_224_p2 <= (sel_tmp18_fu_218_p2 or tmp_demorgan_fu_102_p2);
    tmp_28_fu_774_p2 <= (ap_reg_ppstg_isneg_reg_882_pp0_iter1 xor ap_const_lv1_1);
    tmp_29_fu_534_p1 <= tmp_3_fu_528_p2(10 - 1 downto 0);
    tmp_2_fu_174_p2 <= "1" when (loc_V_fu_76_p4 = ap_const_lv11_433) else "0";
    tmp_30_fu_835_p2 <= (ap_reg_ppstg_tmp_27_reg_941_pp0_iter2 or underflow_fu_796_p2);
    tmp_33_fu_295_p3 <= p_Val2_s_fu_236_p3(to_integer(unsigned(tmp_23_cast_fu_291_p1)) downto to_integer(unsigned(tmp_23_cast_fu_291_p1))) when (to_integer(unsigned(tmp_23_cast_fu_291_p1))>= 0 and to_integer(unsigned(tmp_23_cast_fu_291_p1))<=53) else "-";
    tmp_34_fu_310_p3 <= p_Val2_3_fu_274_p3(9 downto 9);
    tmp_35_fu_328_p3 <= p_Val2_4_fu_322_p2(9 downto 9);
    tmp_37_fu_410_p3 <= pos1_fu_386_p2(11 downto 11);
    tmp_3_fu_528_p2 <= std_logic_vector(shift_left(unsigned(tmp_19_cast_fu_525_p1),to_integer(unsigned('0' & F2_2_cast3_fu_522_p1(19-1 downto 0)))));
    tmp_40_fu_691_p3 <= pos1_reg_997(11 downto 11);
    tmp_4_fu_180_p2 <= "1" when (unsigned(F2_2_fu_166_p3) < unsigned(ap_const_lv12_36)) else "0";
    tmp_5_fu_257_p2 <= std_logic_vector(shift_right(signed(p_Val2_s_fu_236_p3),to_integer(unsigned('0' & tmp_9_fu_253_p1(31-1 downto 0)))));
    tmp_6_fu_120_p1 <= std_logic_vector(resize(unsigned(loc_V_fu_76_p4),12));
    tmp_7_fu_248_p2 <= "1" when (unsigned(F2_2_reg_916) < unsigned(ap_const_lv12_A)) else "0";
    tmp_7_not_fu_362_p2 <= (tmp_7_fu_248_p2 xor ap_const_lv1_1);
    tmp_8_fu_142_p2 <= "1" when (tmp_10_fu_108_p1 = ap_const_lv63_0) else "0";
    tmp_9_fu_253_p1 <= std_logic_vector(resize(unsigned(F2_2_cast_fu_241_p1),54));
    tmp_demorgan_fu_102_p2 <= (tmp_i_fu_90_p2 and tmp_i_54_fu_96_p2);
    tmp_fu_374_p2 <= (not_sel_tmp_fu_368_p2 and tmp_14_fu_336_p2);
    tmp_i_54_fu_96_p2 <= "0" when (loc_V_1_fu_86_p1 = ap_const_lv52_0) else "1";
    tmp_i_fu_90_p2 <= "1" when (loc_V_fu_76_p4 = ap_const_lv11_7FF) else "0";
    tmp_s_fu_160_p2 <= std_logic_vector(unsigned(ap_const_lv12_0) - unsigned(F2_fu_148_p2));
    underflow_fu_796_p2 <= (sign_assign_reg_1062 and brmerge121_i_fu_791_p2);
end behav;
