// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _pynq_filters_AddWeighted_HH_
#define _pynq_filters_AddWeighted_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "pynq_filters_arithm_pro_1.h"

namespace ap_rtl {

struct pynq_filters_AddWeighted : public sc_module {
    // Port declarations 34
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<10> > src1_data_stream_0_V_V_dout;
    sc_in< sc_logic > src1_data_stream_0_V_V_empty_n;
    sc_out< sc_logic > src1_data_stream_0_V_V_read;
    sc_in< sc_lv<10> > src1_data_stream_1_V_V_dout;
    sc_in< sc_logic > src1_data_stream_1_V_V_empty_n;
    sc_out< sc_logic > src1_data_stream_1_V_V_read;
    sc_in< sc_lv<10> > src1_data_stream_2_V_V_dout;
    sc_in< sc_logic > src1_data_stream_2_V_V_empty_n;
    sc_out< sc_logic > src1_data_stream_2_V_V_read;
    sc_in< sc_lv<10> > src2_data_stream_0_V_V_dout;
    sc_in< sc_logic > src2_data_stream_0_V_V_empty_n;
    sc_out< sc_logic > src2_data_stream_0_V_V_read;
    sc_in< sc_lv<10> > src2_data_stream_1_V_V_dout;
    sc_in< sc_logic > src2_data_stream_1_V_V_empty_n;
    sc_out< sc_logic > src2_data_stream_1_V_V_read;
    sc_in< sc_lv<10> > src2_data_stream_2_V_V_dout;
    sc_in< sc_logic > src2_data_stream_2_V_V_empty_n;
    sc_out< sc_logic > src2_data_stream_2_V_V_read;
    sc_out< sc_lv<10> > dst_data_stream_0_V_V_din;
    sc_in< sc_logic > dst_data_stream_0_V_V_full_n;
    sc_out< sc_logic > dst_data_stream_0_V_V_write;
    sc_out< sc_lv<10> > dst_data_stream_1_V_V_din;
    sc_in< sc_logic > dst_data_stream_1_V_V_full_n;
    sc_out< sc_logic > dst_data_stream_1_V_V_write;
    sc_out< sc_lv<10> > dst_data_stream_2_V_V_din;
    sc_in< sc_logic > dst_data_stream_2_V_V_full_n;
    sc_out< sc_logic > dst_data_stream_2_V_V_write;


    // Module declarations
    pynq_filters_AddWeighted(sc_module_name name);
    SC_HAS_PROCESS(pynq_filters_AddWeighted);

    ~pynq_filters_AddWeighted();

    sc_trace_file* mVcdFile;

    pynq_filters_arithm_pro_1* grp_pynq_filters_arithm_pro_1_fu_32;
    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<2> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_20;
    sc_signal< sc_logic > grp_pynq_filters_arithm_pro_1_fu_32_ap_start;
    sc_signal< sc_logic > grp_pynq_filters_arithm_pro_1_fu_32_ap_done;
    sc_signal< sc_logic > grp_pynq_filters_arithm_pro_1_fu_32_ap_idle;
    sc_signal< sc_logic > grp_pynq_filters_arithm_pro_1_fu_32_ap_ready;
    sc_signal< sc_logic > grp_pynq_filters_arithm_pro_1_fu_32_src1_data_stream_0_V_V_read;
    sc_signal< sc_logic > grp_pynq_filters_arithm_pro_1_fu_32_src1_data_stream_1_V_V_read;
    sc_signal< sc_logic > grp_pynq_filters_arithm_pro_1_fu_32_src1_data_stream_2_V_V_read;
    sc_signal< sc_logic > grp_pynq_filters_arithm_pro_1_fu_32_src2_data_stream_0_V_V_read;
    sc_signal< sc_logic > grp_pynq_filters_arithm_pro_1_fu_32_src2_data_stream_1_V_V_read;
    sc_signal< sc_logic > grp_pynq_filters_arithm_pro_1_fu_32_src2_data_stream_2_V_V_read;
    sc_signal< sc_lv<10> > grp_pynq_filters_arithm_pro_1_fu_32_dst_data_stream_0_V_V_din;
    sc_signal< sc_logic > grp_pynq_filters_arithm_pro_1_fu_32_dst_data_stream_0_V_V_write;
    sc_signal< sc_lv<10> > grp_pynq_filters_arithm_pro_1_fu_32_dst_data_stream_1_V_V_din;
    sc_signal< sc_logic > grp_pynq_filters_arithm_pro_1_fu_32_dst_data_stream_1_V_V_write;
    sc_signal< sc_lv<10> > grp_pynq_filters_arithm_pro_1_fu_32_dst_data_stream_2_V_V_din;
    sc_signal< sc_logic > grp_pynq_filters_arithm_pro_1_fu_32_dst_data_stream_2_V_V_write;
    sc_signal< sc_logic > ap_reg_grp_pynq_filters_arithm_pro_1_fu_32_ap_start;
    sc_signal< bool > ap_sig_101;
    sc_signal< sc_logic > ap_sig_cseq_ST_st2_fsm_1;
    sc_signal< bool > ap_sig_109;
    sc_signal< sc_lv<2> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<2> ap_ST_st1_fsm_0;
    static const sc_lv<2> ap_ST_st2_fsm_1;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sig_101();
    void thread_ap_sig_109();
    void thread_ap_sig_20();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_ap_sig_cseq_ST_st2_fsm_1();
    void thread_dst_data_stream_0_V_V_din();
    void thread_dst_data_stream_0_V_V_write();
    void thread_dst_data_stream_1_V_V_din();
    void thread_dst_data_stream_1_V_V_write();
    void thread_dst_data_stream_2_V_V_din();
    void thread_dst_data_stream_2_V_V_write();
    void thread_grp_pynq_filters_arithm_pro_1_fu_32_ap_start();
    void thread_src1_data_stream_0_V_V_read();
    void thread_src1_data_stream_1_V_V_read();
    void thread_src1_data_stream_2_V_V_read();
    void thread_src2_data_stream_0_V_V_read();
    void thread_src2_data_stream_1_V_V_read();
    void thread_src2_data_stream_2_V_V_read();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
