// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _pynq_filters_CvtColor_1_HH_
#define _pynq_filters_CvtColor_1_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "pynq_filters_mac_muladd_8ns_20ns_29ns_29_1.h"
#include "pynq_filters_mac_muladd_8ns_23ns_29ns_30_1.h"
#include "pynq_filters_mul_mul_8ns_22ns_29_1.h"

namespace ap_rtl {

struct pynq_filters_CvtColor_1 : public sc_module {
    // Port declarations 19
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<8> > p_src_data_stream_0_V_dout;
    sc_in< sc_logic > p_src_data_stream_0_V_empty_n;
    sc_out< sc_logic > p_src_data_stream_0_V_read;
    sc_in< sc_lv<8> > p_src_data_stream_1_V_dout;
    sc_in< sc_logic > p_src_data_stream_1_V_empty_n;
    sc_out< sc_logic > p_src_data_stream_1_V_read;
    sc_in< sc_lv<8> > p_src_data_stream_2_V_dout;
    sc_in< sc_logic > p_src_data_stream_2_V_empty_n;
    sc_out< sc_logic > p_src_data_stream_2_V_read;
    sc_out< sc_lv<8> > p_dst_data_stream_V_din;
    sc_in< sc_logic > p_dst_data_stream_V_full_n;
    sc_out< sc_logic > p_dst_data_stream_V_write;


    // Module declarations
    pynq_filters_CvtColor_1(sc_module_name name);
    SC_HAS_PROCESS(pynq_filters_CvtColor_1);

    ~pynq_filters_CvtColor_1();

    sc_trace_file* mVcdFile;

    pynq_filters_mac_muladd_8ns_20ns_29ns_29_1<1,1,8,20,29,29>* pynq_filters_mac_muladd_8ns_20ns_29ns_29_1_U31;
    pynq_filters_mac_muladd_8ns_23ns_29ns_30_1<1,1,8,23,29,30>* pynq_filters_mac_muladd_8ns_23ns_29ns_30_1_U32;
    pynq_filters_mul_mul_8ns_22ns_29_1<1,1,8,22,29>* pynq_filters_mul_mul_8ns_22ns_29_1_U33;
    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<4> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_22;
    sc_signal< sc_logic > p_src_data_stream_0_V_blk_n;
    sc_signal< sc_logic > ap_sig_cseq_ST_pp0_stg0_fsm_2;
    sc_signal< bool > ap_sig_51;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it1;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it0;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it2;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it3;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it4;
    sc_signal< sc_lv<1> > exitcond_reg_266;
    sc_signal< sc_logic > p_src_data_stream_1_V_blk_n;
    sc_signal< sc_logic > p_src_data_stream_2_V_blk_n;
    sc_signal< sc_logic > p_dst_data_stream_V_blk_n;
    sc_signal< sc_lv<1> > ap_reg_ppstg_exitcond_reg_266_pp0_iter3;
    sc_signal< sc_lv<10> > j_reg_126;
    sc_signal< sc_lv<1> > exitcond2_fu_137_p2;
    sc_signal< sc_logic > ap_sig_cseq_ST_st2_fsm_1;
    sc_signal< bool > ap_sig_83;
    sc_signal< sc_lv<9> > i_1_fu_143_p2;
    sc_signal< sc_lv<9> > i_1_reg_261;
    sc_signal< sc_lv<1> > exitcond_fu_149_p2;
    sc_signal< bool > ap_sig_96;
    sc_signal< bool > ap_sig_100;
    sc_signal< sc_lv<1> > ap_reg_ppstg_exitcond_reg_266_pp0_iter1;
    sc_signal< sc_lv<1> > ap_reg_ppstg_exitcond_reg_266_pp0_iter2;
    sc_signal< sc_lv<10> > j_1_fu_155_p2;
    sc_signal< sc_lv<8> > tmp_132_reg_275;
    sc_signal< sc_lv<8> > tmp_133_reg_280;
    sc_signal< sc_lv<8> > ap_reg_ppstg_tmp_133_reg_280_pp0_iter2;
    sc_signal< sc_lv<8> > tmp_134_reg_285;
    sc_signal< sc_lv<8> > ap_reg_ppstg_tmp_134_reg_285_pp0_iter2;
    sc_signal< sc_lv<29> > r_V_i_fu_251_p2;
    sc_signal< sc_lv<29> > r_V_i_reg_290;
    sc_signal< sc_lv<30> > grp_fu_241_p3;
    sc_signal< sc_lv<30> > r_V_1_reg_295;
    sc_signal< sc_lv<8> > p_Val2_23_reg_300;
    sc_signal< sc_lv<1> > tmp_128_reg_305;
    sc_signal< sc_lv<9> > i_reg_115;
    sc_signal< bool > ap_sig_150;
    sc_signal< sc_logic > ap_sig_cseq_ST_st8_fsm_3;
    sc_signal< bool > ap_sig_158;
    sc_signal< sc_lv<29> > grp_fu_233_p3;
    sc_signal< sc_lv<8> > tmp_7_i_i_i_fu_189_p1;
    sc_signal< sc_lv<8> > p_Val2_24_fu_199_p2;
    sc_signal< sc_lv<1> > tmp_129_fu_192_p3;
    sc_signal< sc_lv<1> > tmp_130_fu_204_p3;
    sc_signal< sc_lv<1> > p_Result_2_i_i_i_not_fu_212_p2;
    sc_signal< sc_lv<1> > not_carry_fu_218_p2;
    sc_signal< sc_lv<8> > grp_fu_233_p0;
    sc_signal< sc_lv<20> > grp_fu_233_p1;
    sc_signal< sc_lv<8> > grp_fu_241_p0;
    sc_signal< sc_lv<23> > grp_fu_241_p1;
    sc_signal< sc_lv<29> > grp_fu_241_p2;
    sc_signal< sc_lv<8> > r_V_i_fu_251_p0;
    sc_signal< sc_lv<22> > r_V_i_fu_251_p1;
    sc_signal< sc_lv<4> > ap_NS_fsm;
    sc_signal< sc_lv<28> > grp_fu_233_p00;
    sc_signal< sc_lv<30> > grp_fu_241_p00;
    sc_signal< sc_lv<30> > grp_fu_241_p20;
    sc_signal< sc_lv<29> > r_V_i_fu_251_p00;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<4> ap_ST_st1_fsm_0;
    static const sc_lv<4> ap_ST_st2_fsm_1;
    static const sc_lv<4> ap_ST_pp0_stg0_fsm_2;
    static const sc_lv<4> ap_ST_st8_fsm_3;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<9> ap_const_lv9_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<10> ap_const_lv10_0;
    static const sc_lv<9> ap_const_lv9_1E0;
    static const sc_lv<9> ap_const_lv9_1;
    static const sc_lv<10> ap_const_lv10_280;
    static const sc_lv<10> ap_const_lv10_1;
    static const sc_lv<32> ap_const_lv32_16;
    static const sc_lv<32> ap_const_lv32_1D;
    static const sc_lv<32> ap_const_lv32_15;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<8> ap_const_lv8_FF;
    static const sc_lv<28> ap_const_lv28_74BC6;
    static const sc_lv<30> ap_const_lv30_259168;
    static const sc_lv<29> ap_const_lv29_1322D0;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sig_100();
    void thread_ap_sig_150();
    void thread_ap_sig_158();
    void thread_ap_sig_22();
    void thread_ap_sig_51();
    void thread_ap_sig_83();
    void thread_ap_sig_96();
    void thread_ap_sig_cseq_ST_pp0_stg0_fsm_2();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_ap_sig_cseq_ST_st2_fsm_1();
    void thread_ap_sig_cseq_ST_st8_fsm_3();
    void thread_exitcond2_fu_137_p2();
    void thread_exitcond_fu_149_p2();
    void thread_grp_fu_233_p0();
    void thread_grp_fu_233_p00();
    void thread_grp_fu_233_p1();
    void thread_grp_fu_241_p0();
    void thread_grp_fu_241_p00();
    void thread_grp_fu_241_p1();
    void thread_grp_fu_241_p2();
    void thread_grp_fu_241_p20();
    void thread_i_1_fu_143_p2();
    void thread_j_1_fu_155_p2();
    void thread_not_carry_fu_218_p2();
    void thread_p_Result_2_i_i_i_not_fu_212_p2();
    void thread_p_Val2_24_fu_199_p2();
    void thread_p_dst_data_stream_V_blk_n();
    void thread_p_dst_data_stream_V_din();
    void thread_p_dst_data_stream_V_write();
    void thread_p_src_data_stream_0_V_blk_n();
    void thread_p_src_data_stream_0_V_read();
    void thread_p_src_data_stream_1_V_blk_n();
    void thread_p_src_data_stream_1_V_read();
    void thread_p_src_data_stream_2_V_blk_n();
    void thread_p_src_data_stream_2_V_read();
    void thread_r_V_i_fu_251_p0();
    void thread_r_V_i_fu_251_p00();
    void thread_r_V_i_fu_251_p1();
    void thread_tmp_129_fu_192_p3();
    void thread_tmp_130_fu_204_p3();
    void thread_tmp_7_i_i_i_fu_189_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
