#
# Vivado (TM) v2013.3 (64-bit)
#
# duncan_proj.tcl: Tcl script for re-creating project 'project_2'
#
# Generated by Vivado on Thu Oct 17 15:29:29 -0700 2013
# IP Build 189985 on Sat Oct  5 03:19:40 MDT 2013
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (duncan_proj.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' variable setting below at the start of the script)
#
#    "C:/Vivado_HLS_Tutorial/Using_IP_with_IPI/lab1/project_2/project_2.srcs/sources_1/bd/RealFFT/RealFFT.bd"
#    "C:/Vivado_HLS_Tutorial/Using_IP_with_IPI/lab1/project_2/project_2.srcs/sources_1/bd/RealFFT/hdl/RealFFT_wrapper.v"
#    "C:/Vivado_HLS_Tutorial/Using_IP_with_IPI/lab1/project_2/project_2.srcs/sim_1/imports/verilog_tb/realfft_rtl_tb.v"
#
# 3. The following remote source files that were added to the original project:-
#
#    <none>
#
#*****************************************************************************************

# Set the original project directory path for adding/importing sources in the new project
set orig_proj_dir "C:/Vivado_HLS_Tutorial/Using_IP_with_IPI/lab1/project_2"

# Create project
create_project project_2 ./project_2

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [get_projects project_2]
set_property "board" "xilinx.com:zynq:zc702:1.0" $obj
set_property "simulator_language" "Mixed" $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Add files to 'sources_1' fileset
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$orig_proj_dir/project_2.srcs/sources_1/bd/RealFFT/RealFFT.bd"]"\
 "[file normalize "$orig_proj_dir/project_2.srcs/sources_1/bd/RealFFT/hdl/RealFFT_wrapper.v"]"\
]
add_files -norecurse -fileset $obj $files

# Import local files from the original project
set files [list \
 "C:/Vivado_HLS_Tutorial/Using_IP_with_IPI/lab1/project_2/project_2.srcs/sources_1/bd/RealFFT/RealFFT.bd"\
 "C:/Vivado_HLS_Tutorial/Using_IP_with_IPI/lab1/project_2/project_2.srcs/sources_1/bd/RealFFT/hdl/RealFFT_wrapper.v"\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property "ip_repo_paths" "C:/Vivado_HLS_Tutorial/Using_IP_with_IPI/lab1/vivado_ip_repo" $obj
set_property "top" "RealFFT_wrapper" $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Add files to 'constrs_1' fileset
set obj [get_filesets constrs_1]
# Empty (no sources present)

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets sim_1] ""]} {
  create_fileset -simset sim_1
}

# Add files to 'sim_1' fileset
set obj [get_filesets sim_1]
# Import local files from the original project
set files [list \
 "[file normalize "$orig_proj_dir/project_2.srcs/sim_1/imports/verilog_tb/realfft_rtl_tb.v"]"\
]
set imported_files [import_files -fileset sim_1 $files]

# Set 'sim_1' fileset file properties for remote files
# None

# Set 'sim_1' fileset file properties for local files
# None

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property "top" "realfft_rtl_tb" $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs synth_1] ""]} {
  create_run -name synth_1 -part xc7z020clg484-1 -flow {Vivado Synthesis 2013} -strategy "Vivado Synthesis Defaults" -constrset constrs_1
}
set obj [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs impl_1] ""]} {
  create_run -name impl_1 -part xc7z020clg484-1 -flow {Vivado Implementation 2013} -strategy "Vivado Implementation Defaults" -constrset constrs_1 -parent_run synth_1
}
set obj [get_runs impl_1]


puts "INFO: Project created:project_2"
