<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE boost_serialization>
<boost_serialization signature="serialization::archive" version="14">
<syndb class_id="0" tracking_level="0" version="0">
	<userIPLatency>-1</userIPLatency>
	<userIPName></userIPName>
	<cdfg class_id="1" tracking_level="1" version="0" object_id="_0">
		<name>pynq_filters_arithm_pro</name>
		<ret_bitwidth>0</ret_bitwidth>
		<ports class_id="2" tracking_level="0" version="0">
			<count>3</count>
			<item_version>0</item_version>
			<item class_id="3" tracking_level="1" version="0" object_id="_1">
				<Value class_id="4" tracking_level="0" version="0">
					<Obj class_id="5" tracking_level="0" version="0">
						<type>1</type>
						<id>1</id>
						<name>src_data_stream_V_V</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo class_id="6" tracking_level="0" version="0">
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>src.data_stream.V.V</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>10</bitwidth>
				</Value>
				<direction>0</direction>
				<if_type>3</if_type>
				<array_size>0</array_size>
				<bit_vecs class_id="7" tracking_level="0" version="0">
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
			<item class_id_reference="3" object_id="_2">
				<Value>
					<Obj>
						<type>1</type>
						<id>2</id>
						<name>dst_data_stream_V_V</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>dst.data_stream.V.V</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>10</bitwidth>
				</Value>
				<direction>1</direction>
				<if_type>3</if_type>
				<array_size>0</array_size>
				<bit_vecs>
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
			<item class_id_reference="3" object_id="_3">
				<Value>
					<Obj>
						<type>1</type>
						<id>3</id>
						<name>p0</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>p0</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>64</bitwidth>
				</Value>
				<direction>0</direction>
				<if_type>0</if_type>
				<array_size>0</array_size>
				<bit_vecs>
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
		</ports>
		<nodes class_id="8" tracking_level="0" version="0">
			<count>21</count>
			<item_version>0</item_version>
			<item class_id="9" tracking_level="1" version="0" object_id="_4">
				<Value>
					<Obj>
						<type>0</type>
						<id>6</id>
						<name>p0_read</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>p0</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>64</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>51</item>
					<item>52</item>
				</oprand_edges>
				<opcode>read</opcode>
			</item>
			<item class_id_reference="9" object_id="_5">
				<Value>
					<Obj>
						<type>0</type>
						<id>7</id>
						<name></name>
						<fileName>C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/hls/hls_video_arithm.h</fileName>
						<fileDirectory>C:\Users\Misca\beuth_ws1920\ModellbasierterEntwurf\Versuch1_sharpen</fileDirectory>
						<lineNumber>411</lineNumber>
						<contextFuncName>arithm_pro&amp;lt;hls::kernel_scale, 480, 640, 9, ap_int&amp;lt;10&amp;gt;, 9, double, double, double&amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item class_id="11" tracking_level="0" version="0">
								<first>C:\Users\Misca\beuth_ws1920\ModellbasierterEntwurf\Versuch1_sharpen</first>
								<second class_id="12" tracking_level="0" version="0">
									<count>1</count>
									<item_version>0</item_version>
									<item class_id="13" tracking_level="0" version="0">
										<first class_id="14" tracking_level="0" version="0">
											<first>C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>arithm_pro&amp;lt;hls::kernel_scale, 480, 640, 9, ap_int&amp;lt;10&amp;gt;, 9, double, double, double&amp;gt;</second>
										</first>
										<second>411</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>53</item>
				</oprand_edges>
				<opcode>br</opcode>
			</item>
			<item class_id_reference="9" object_id="_6">
				<Value>
					<Obj>
						<type>0</type>
						<id>9</id>
						<name>p_s</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>i.V</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>9</bitwidth>
				</Value>
				<oprand_edges>
					<count>4</count>
					<item_version>0</item_version>
					<item>54</item>
					<item>55</item>
					<item>57</item>
					<item>58</item>
				</oprand_edges>
				<opcode>phi</opcode>
			</item>
			<item class_id_reference="9" object_id="_7">
				<Value>
					<Obj>
						<type>0</type>
						<id>10</id>
						<name>exitcond2</name>
						<fileName>C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/hls/hls_video_arithm.h</fileName>
						<fileDirectory>C:\Users\Misca\beuth_ws1920\ModellbasierterEntwurf\Versuch1_sharpen</fileDirectory>
						<lineNumber>411</lineNumber>
						<contextFuncName>arithm_pro&amp;lt;hls::kernel_scale, 480, 640, 9, ap_int&amp;lt;10&amp;gt;, 9, double, double, double&amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Misca\beuth_ws1920\ModellbasierterEntwurf\Versuch1_sharpen</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>arithm_pro&amp;lt;hls::kernel_scale, 480, 640, 9, ap_int&amp;lt;10&amp;gt;, 9, double, double, double&amp;gt;</second>
										</first>
										<second>411</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>1</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>59</item>
					<item>61</item>
				</oprand_edges>
				<opcode>icmp</opcode>
			</item>
			<item class_id_reference="9" object_id="_8">
				<Value>
					<Obj>
						<type>0</type>
						<id>12</id>
						<name>i_V</name>
						<fileName>C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/hls/hls_video_arithm.h</fileName>
						<fileDirectory>C:\Users\Misca\beuth_ws1920\ModellbasierterEntwurf\Versuch1_sharpen</fileDirectory>
						<lineNumber>411</lineNumber>
						<contextFuncName>arithm_pro&amp;lt;hls::kernel_scale, 480, 640, 9, ap_int&amp;lt;10&amp;gt;, 9, double, double, double&amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Misca\beuth_ws1920\ModellbasierterEntwurf\Versuch1_sharpen</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>arithm_pro&amp;lt;hls::kernel_scale, 480, 640, 9, ap_int&amp;lt;10&amp;gt;, 9, double, double, double&amp;gt;</second>
										</first>
										<second>411</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName>i.V</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>9</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>62</item>
					<item>64</item>
				</oprand_edges>
				<opcode>add</opcode>
			</item>
			<item class_id_reference="9" object_id="_9">
				<Value>
					<Obj>
						<type>0</type>
						<id>13</id>
						<name></name>
						<fileName>C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/hls/hls_video_arithm.h</fileName>
						<fileDirectory>C:\Users\Misca\beuth_ws1920\ModellbasierterEntwurf\Versuch1_sharpen</fileDirectory>
						<lineNumber>411</lineNumber>
						<contextFuncName>arithm_pro&amp;lt;hls::kernel_scale, 480, 640, 9, ap_int&amp;lt;10&amp;gt;, 9, double, double, double&amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Misca\beuth_ws1920\ModellbasierterEntwurf\Versuch1_sharpen</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>arithm_pro&amp;lt;hls::kernel_scale, 480, 640, 9, ap_int&amp;lt;10&amp;gt;, 9, double, double, double&amp;gt;</second>
										</first>
										<second>411</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>3</count>
					<item_version>0</item_version>
					<item>65</item>
					<item>66</item>
					<item>67</item>
				</oprand_edges>
				<opcode>br</opcode>
			</item>
			<item class_id_reference="9" object_id="_10">
				<Value>
					<Obj>
						<type>0</type>
						<id>17</id>
						<name></name>
						<fileName>C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/hls/hls_video_arithm.h</fileName>
						<fileDirectory>C:\Users\Misca\beuth_ws1920\ModellbasierterEntwurf\Versuch1_sharpen</fileDirectory>
						<lineNumber>412</lineNumber>
						<contextFuncName>arithm_pro&amp;lt;hls::kernel_scale, 480, 640, 9, ap_int&amp;lt;10&amp;gt;, 9, double, double, double&amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Misca\beuth_ws1920\ModellbasierterEntwurf\Versuch1_sharpen</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>arithm_pro&amp;lt;hls::kernel_scale, 480, 640, 9, ap_int&amp;lt;10&amp;gt;, 9, double, double, double&amp;gt;</second>
										</first>
										<second>412</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>68</item>
				</oprand_edges>
				<opcode>br</opcode>
			</item>
			<item class_id_reference="9" object_id="_11">
				<Value>
					<Obj>
						<type>0</type>
						<id>19</id>
						<name>p_1</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>j.V</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>10</bitwidth>
				</Value>
				<oprand_edges>
					<count>4</count>
					<item_version>0</item_version>
					<item>70</item>
					<item>71</item>
					<item>72</item>
					<item>73</item>
				</oprand_edges>
				<opcode>phi</opcode>
			</item>
			<item class_id_reference="9" object_id="_12">
				<Value>
					<Obj>
						<type>0</type>
						<id>20</id>
						<name>exitcond</name>
						<fileName>C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/hls/hls_video_arithm.h</fileName>
						<fileDirectory>C:\Users\Misca\beuth_ws1920\ModellbasierterEntwurf\Versuch1_sharpen</fileDirectory>
						<lineNumber>412</lineNumber>
						<contextFuncName>arithm_pro&amp;lt;hls::kernel_scale, 480, 640, 9, ap_int&amp;lt;10&amp;gt;, 9, double, double, double&amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Misca\beuth_ws1920\ModellbasierterEntwurf\Versuch1_sharpen</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>arithm_pro&amp;lt;hls::kernel_scale, 480, 640, 9, ap_int&amp;lt;10&amp;gt;, 9, double, double, double&amp;gt;</second>
										</first>
										<second>412</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>1</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>74</item>
					<item>76</item>
				</oprand_edges>
				<opcode>icmp</opcode>
			</item>
			<item class_id_reference="9" object_id="_13">
				<Value>
					<Obj>
						<type>0</type>
						<id>22</id>
						<name>j_V</name>
						<fileName>C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/hls/hls_video_arithm.h</fileName>
						<fileDirectory>C:\Users\Misca\beuth_ws1920\ModellbasierterEntwurf\Versuch1_sharpen</fileDirectory>
						<lineNumber>412</lineNumber>
						<contextFuncName>arithm_pro&amp;lt;hls::kernel_scale, 480, 640, 9, ap_int&amp;lt;10&amp;gt;, 9, double, double, double&amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Misca\beuth_ws1920\ModellbasierterEntwurf\Versuch1_sharpen</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>arithm_pro&amp;lt;hls::kernel_scale, 480, 640, 9, ap_int&amp;lt;10&amp;gt;, 9, double, double, double&amp;gt;</second>
										</first>
										<second>412</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName>j.V</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>10</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>77</item>
					<item>79</item>
				</oprand_edges>
				<opcode>add</opcode>
			</item>
			<item class_id_reference="9" object_id="_14">
				<Value>
					<Obj>
						<type>0</type>
						<id>23</id>
						<name></name>
						<fileName>C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/hls/hls_video_arithm.h</fileName>
						<fileDirectory>C:\Users\Misca\beuth_ws1920\ModellbasierterEntwurf\Versuch1_sharpen</fileDirectory>
						<lineNumber>412</lineNumber>
						<contextFuncName>arithm_pro&amp;lt;hls::kernel_scale, 480, 640, 9, ap_int&amp;lt;10&amp;gt;, 9, double, double, double&amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Misca\beuth_ws1920\ModellbasierterEntwurf\Versuch1_sharpen</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>arithm_pro&amp;lt;hls::kernel_scale, 480, 640, 9, ap_int&amp;lt;10&amp;gt;, 9, double, double, double&amp;gt;</second>
										</first>
										<second>412</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>3</count>
					<item_version>0</item_version>
					<item>80</item>
					<item>81</item>
					<item>82</item>
				</oprand_edges>
				<opcode>br</opcode>
			</item>
			<item class_id_reference="9" object_id="_15">
				<Value>
					<Obj>
						<type>0</type>
						<id>30</id>
						<name>tmp_V</name>
						<fileName>C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/hls/hls_video_core.h</fileName>
						<fileDirectory>C:\Users\Misca\beuth_ws1920\ModellbasierterEntwurf\Versuch1_sharpen</fileDirectory>
						<lineNumber>624</lineNumber>
						<contextFuncName>read</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Misca\beuth_ws1920\ModellbasierterEntwurf\Versuch1_sharpen</first>
								<second>
									<count>3</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>arithm_pro&amp;lt;hls::kernel_scale, 480, 640, 9, ap_int&amp;lt;10&amp;gt;, 9, double, double, double&amp;gt;</second>
										</first>
										<second>415</second>
									</item>
									<item>
										<first>
											<first>C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/hls/hls_video_core.h</first>
											<second>operator&amp;gt;&amp;gt;</second>
										</first>
										<second>656</second>
									</item>
									<item>
										<first>
											<first>C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/hls/hls_video_core.h</first>
											<second>read</second>
										</first>
										<second>624</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName>tmp.V</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>10</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>84</item>
					<item>85</item>
				</oprand_edges>
				<opcode>read</opcode>
			</item>
			<item class_id_reference="9" object_id="_16">
				<Value>
					<Obj>
						<type>0</type>
						<id>33</id>
						<name>tmp_5</name>
						<fileName>C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/hls/hls_video_arithm.h</fileName>
						<fileDirectory>C:\Users\Misca\beuth_ws1920\ModellbasierterEntwurf\Versuch1_sharpen</fileDirectory>
						<lineNumber>190</lineNumber>
						<contextFuncName>apply&amp;lt;ap_int&amp;lt;10&amp;gt;, ap_int&amp;lt;10&amp;gt;, ap_int&amp;lt;10&amp;gt;, double&amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Misca\beuth_ws1920\ModellbasierterEntwurf\Versuch1_sharpen</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>apply&amp;lt;ap_int&amp;lt;10&amp;gt;, ap_int&amp;lt;10&amp;gt;, ap_int&amp;lt;10&amp;gt;, double&amp;gt;</second>
										</first>
										<second>190</second>
									</item>
									<item>
										<first>
											<first>C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>arithm_pro&amp;lt;hls::kernel_scale, 480, 640, 9, ap_int&amp;lt;10&amp;gt;, 9, double, double, double&amp;gt;</second>
										</first>
										<second>418</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>86</item>
				</oprand_edges>
				<opcode>sext</opcode>
			</item>
			<item class_id_reference="9" object_id="_17">
				<Value>
					<Obj>
						<type>0</type>
						<id>34</id>
						<name>tmp_s</name>
						<fileName>C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/hls/hls_video_arithm.h</fileName>
						<fileDirectory>C:\Users\Misca\beuth_ws1920\ModellbasierterEntwurf\Versuch1_sharpen</fileDirectory>
						<lineNumber>190</lineNumber>
						<contextFuncName>apply&amp;lt;ap_int&amp;lt;10&amp;gt;, ap_int&amp;lt;10&amp;gt;, ap_int&amp;lt;10&amp;gt;, double&amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Misca\beuth_ws1920\ModellbasierterEntwurf\Versuch1_sharpen</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>apply&amp;lt;ap_int&amp;lt;10&amp;gt;, ap_int&amp;lt;10&amp;gt;, ap_int&amp;lt;10&amp;gt;, double&amp;gt;</second>
										</first>
										<second>190</second>
									</item>
									<item>
										<first>
											<first>C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>arithm_pro&amp;lt;hls::kernel_scale, 480, 640, 9, ap_int&amp;lt;10&amp;gt;, 9, double, double, double&amp;gt;</second>
										</first>
										<second>418</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>64</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>87</item>
				</oprand_edges>
				<opcode>sitodp</opcode>
			</item>
			<item class_id_reference="9" object_id="_18">
				<Value>
					<Obj>
						<type>0</type>
						<id>35</id>
						<name>mult_t</name>
						<fileName>C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/hls/hls_video_arithm.h</fileName>
						<fileDirectory>C:\Users\Misca\beuth_ws1920\ModellbasierterEntwurf\Versuch1_sharpen</fileDirectory>
						<lineNumber>190</lineNumber>
						<contextFuncName>apply&amp;lt;ap_int&amp;lt;10&amp;gt;, ap_int&amp;lt;10&amp;gt;, ap_int&amp;lt;10&amp;gt;, double&amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Misca\beuth_ws1920\ModellbasierterEntwurf\Versuch1_sharpen</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>apply&amp;lt;ap_int&amp;lt;10&amp;gt;, ap_int&amp;lt;10&amp;gt;, ap_int&amp;lt;10&amp;gt;, double&amp;gt;</second>
										</first>
										<second>190</second>
									</item>
									<item>
										<first>
											<first>C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>arithm_pro&amp;lt;hls::kernel_scale, 480, 640, 9, ap_int&amp;lt;10&amp;gt;, 9, double, double, double&amp;gt;</second>
										</first>
										<second>418</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName>mult_t</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>64</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>88</item>
					<item>89</item>
				</oprand_edges>
				<opcode>dmul</opcode>
			</item>
			<item class_id_reference="9" object_id="_19">
				<Value>
					<Obj>
						<type>0</type>
						<id>36</id>
						<name>sum_t</name>
						<fileName>C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/hls/hls_video_arithm.h</fileName>
						<fileDirectory>C:\Users\Misca\beuth_ws1920\ModellbasierterEntwurf\Versuch1_sharpen</fileDirectory>
						<lineNumber>191</lineNumber>
						<contextFuncName>apply&amp;lt;ap_int&amp;lt;10&amp;gt;, ap_int&amp;lt;10&amp;gt;, ap_int&amp;lt;10&amp;gt;, double&amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Misca\beuth_ws1920\ModellbasierterEntwurf\Versuch1_sharpen</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>apply&amp;lt;ap_int&amp;lt;10&amp;gt;, ap_int&amp;lt;10&amp;gt;, ap_int&amp;lt;10&amp;gt;, double&amp;gt;</second>
										</first>
										<second>191</second>
									</item>
									<item>
										<first>
											<first>C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>arithm_pro&amp;lt;hls::kernel_scale, 480, 640, 9, ap_int&amp;lt;10&amp;gt;, 9, double, double, double&amp;gt;</second>
										</first>
										<second>418</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName>sum_t</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>64</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>90</item>
					<item>92</item>
				</oprand_edges>
				<opcode>dadd</opcode>
			</item>
			<item class_id_reference="9" object_id="_20">
				<Value>
					<Obj>
						<type>0</type>
						<id>37</id>
						<name>tmp_V11</name>
						<fileName>C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/hls/hls_video_types.h</fileName>
						<fileDirectory>C:\Users\Misca\beuth_ws1920\ModellbasierterEntwurf\Versuch1_sharpen</fileDirectory>
						<lineNumber>510</lineNumber>
						<contextFuncName>sr_cast&amp;lt;ap_int&amp;lt;10&amp;gt;, double&amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Misca\beuth_ws1920\ModellbasierterEntwurf\Versuch1_sharpen</first>
								<second>
									<count>3</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>apply&amp;lt;ap_int&amp;lt;10&amp;gt;, ap_int&amp;lt;10&amp;gt;, ap_int&amp;lt;10&amp;gt;, double&amp;gt;</second>
										</first>
										<second>193</second>
									</item>
									<item>
										<first>
											<first>C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>arithm_pro&amp;lt;hls::kernel_scale, 480, 640, 9, ap_int&amp;lt;10&amp;gt;, 9, double, double, double&amp;gt;</second>
										</first>
										<second>418</second>
									</item>
									<item>
										<first>
											<first>C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/hls/hls_video_types.h</first>
											<second>sr_cast&amp;lt;ap_int&amp;lt;10&amp;gt;, double&amp;gt;</second>
										</first>
										<second>510</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName>tmp.V</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>10</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>94</item>
					<item>95</item>
				</oprand_edges>
				<opcode>call</opcode>
			</item>
			<item class_id_reference="9" object_id="_21">
				<Value>
					<Obj>
						<type>0</type>
						<id>40</id>
						<name></name>
						<fileName>C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/hls/hls_video_core.h</fileName>
						<fileDirectory>C:\Users\Misca\beuth_ws1920\ModellbasierterEntwurf\Versuch1_sharpen</fileDirectory>
						<lineNumber>648</lineNumber>
						<contextFuncName>write</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Misca\beuth_ws1920\ModellbasierterEntwurf\Versuch1_sharpen</first>
								<second>
									<count>3</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>arithm_pro&amp;lt;hls::kernel_scale, 480, 640, 9, ap_int&amp;lt;10&amp;gt;, 9, double, double, double&amp;gt;</second>
										</first>
										<second>421</second>
									</item>
									<item>
										<first>
											<first>C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/hls/hls_video_core.h</first>
											<second>operator&amp;lt;&amp;lt;</second>
										</first>
										<second>662</second>
									</item>
									<item>
										<first>
											<first>C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/hls/hls_video_core.h</first>
											<second>write</second>
										</first>
										<second>648</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>3</count>
					<item_version>0</item_version>
					<item>97</item>
					<item>98</item>
					<item>99</item>
				</oprand_edges>
				<opcode>write</opcode>
			</item>
			<item class_id_reference="9" object_id="_22">
				<Value>
					<Obj>
						<type>0</type>
						<id>43</id>
						<name></name>
						<fileName>C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/hls/hls_video_arithm.h</fileName>
						<fileDirectory>C:\Users\Misca\beuth_ws1920\ModellbasierterEntwurf\Versuch1_sharpen</fileDirectory>
						<lineNumber>412</lineNumber>
						<contextFuncName>arithm_pro&amp;lt;hls::kernel_scale, 480, 640, 9, ap_int&amp;lt;10&amp;gt;, 9, double, double, double&amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Misca\beuth_ws1920\ModellbasierterEntwurf\Versuch1_sharpen</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>arithm_pro&amp;lt;hls::kernel_scale, 480, 640, 9, ap_int&amp;lt;10&amp;gt;, 9, double, double, double&amp;gt;</second>
										</first>
										<second>412</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>100</item>
				</oprand_edges>
				<opcode>br</opcode>
			</item>
			<item class_id_reference="9" object_id="_23">
				<Value>
					<Obj>
						<type>0</type>
						<id>46</id>
						<name></name>
						<fileName>C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/hls/hls_video_arithm.h</fileName>
						<fileDirectory>C:\Users\Misca\beuth_ws1920\ModellbasierterEntwurf\Versuch1_sharpen</fileDirectory>
						<lineNumber>411</lineNumber>
						<contextFuncName>arithm_pro&amp;lt;hls::kernel_scale, 480, 640, 9, ap_int&amp;lt;10&amp;gt;, 9, double, double, double&amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Misca\beuth_ws1920\ModellbasierterEntwurf\Versuch1_sharpen</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>arithm_pro&amp;lt;hls::kernel_scale, 480, 640, 9, ap_int&amp;lt;10&amp;gt;, 9, double, double, double&amp;gt;</second>
										</first>
										<second>411</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>101</item>
				</oprand_edges>
				<opcode>br</opcode>
			</item>
			<item class_id_reference="9" object_id="_24">
				<Value>
					<Obj>
						<type>0</type>
						<id>48</id>
						<name></name>
						<fileName>C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/hls/hls_video_arithm.h</fileName>
						<fileDirectory>C:\Users\Misca\beuth_ws1920\ModellbasierterEntwurf\Versuch1_sharpen</fileDirectory>
						<lineNumber>424</lineNumber>
						<contextFuncName>arithm_pro&amp;lt;hls::kernel_scale, 480, 640, 9, ap_int&amp;lt;10&amp;gt;, 9, double, double, double&amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>C:\Users\Misca\beuth_ws1920\ModellbasierterEntwurf\Versuch1_sharpen</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>C:/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>arithm_pro&amp;lt;hls::kernel_scale, 480, 640, 9, ap_int&amp;lt;10&amp;gt;, 9, double, double, double&amp;gt;</second>
										</first>
										<second>424</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>0</count>
					<item_version>0</item_version>
				</oprand_edges>
				<opcode>ret</opcode>
			</item>
		</nodes>
		<consts class_id="15" tracking_level="0" version="0">
			<count>8</count>
			<item_version>0</item_version>
			<item class_id="16" tracking_level="1" version="0" object_id="_25">
				<Value>
					<Obj>
						<type>2</type>
						<id>56</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>9</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>0</content>
			</item>
			<item class_id_reference="16" object_id="_26">
				<Value>
					<Obj>
						<type>2</type>
						<id>60</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>9</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>480</content>
			</item>
			<item class_id_reference="16" object_id="_27">
				<Value>
					<Obj>
						<type>2</type>
						<id>63</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>9</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>1</content>
			</item>
			<item class_id_reference="16" object_id="_28">
				<Value>
					<Obj>
						<type>2</type>
						<id>69</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>10</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>0</content>
			</item>
			<item class_id_reference="16" object_id="_29">
				<Value>
					<Obj>
						<type>2</type>
						<id>75</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>10</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>640</content>
			</item>
			<item class_id_reference="16" object_id="_30">
				<Value>
					<Obj>
						<type>2</type>
						<id>78</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>10</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>1</content>
			</item>
			<item class_id_reference="16" object_id="_31">
				<Value>
					<Obj>
						<type>2</type>
						<id>91</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>64</bitwidth>
				</Value>
				<const_type>1</const_type>
				<content>0</content>
			</item>
			<item class_id_reference="16" object_id="_32">
				<Value>
					<Obj>
						<type>2</type>
						<id>93</id>
						<name>pynq_filters_operator_s</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>10</bitwidth>
				</Value>
				<const_type>6</const_type>
				<content>&lt;constant:pynq_filters_operator()&gt;</content>
			</item>
		</consts>
		<blocks class_id="17" tracking_level="0" version="0">
			<count>7</count>
			<item_version>0</item_version>
			<item class_id="18" tracking_level="1" version="0" object_id="_33">
				<Obj>
					<type>3</type>
					<id>8</id>
					<name>._crit_edge</name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<coreName></coreName>
				</Obj>
				<node_objs>
					<count>2</count>
					<item_version>0</item_version>
					<item>6</item>
					<item>7</item>
				</node_objs>
			</item>
			<item class_id_reference="18" object_id="_34">
				<Obj>
					<type>3</type>
					<id>14</id>
					<name>operator=.exit</name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<coreName></coreName>
				</Obj>
				<node_objs>
					<count>4</count>
					<item_version>0</item_version>
					<item>9</item>
					<item>10</item>
					<item>12</item>
					<item>13</item>
				</node_objs>
			</item>
			<item class_id_reference="18" object_id="_35">
				<Obj>
					<type>3</type>
					<id>18</id>
					<name></name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<coreName></coreName>
				</Obj>
				<node_objs>
					<count>1</count>
					<item_version>0</item_version>
					<item>17</item>
				</node_objs>
			</item>
			<item class_id_reference="18" object_id="_36">
				<Obj>
					<type>3</type>
					<id>24</id>
					<name></name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<coreName></coreName>
				</Obj>
				<node_objs>
					<count>4</count>
					<item_version>0</item_version>
					<item>19</item>
					<item>20</item>
					<item>22</item>
					<item>23</item>
				</node_objs>
			</item>
			<item class_id_reference="18" object_id="_37">
				<Obj>
					<type>3</type>
					<id>44</id>
					<name>.critedge</name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<coreName></coreName>
				</Obj>
				<node_objs>
					<count>8</count>
					<item_version>0</item_version>
					<item>30</item>
					<item>33</item>
					<item>34</item>
					<item>35</item>
					<item>36</item>
					<item>37</item>
					<item>40</item>
					<item>43</item>
				</node_objs>
			</item>
			<item class_id_reference="18" object_id="_38">
				<Obj>
					<type>3</type>
					<id>47</id>
					<name></name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<coreName></coreName>
				</Obj>
				<node_objs>
					<count>1</count>
					<item_version>0</item_version>
					<item>46</item>
				</node_objs>
			</item>
			<item class_id_reference="18" object_id="_39">
				<Obj>
					<type>3</type>
					<id>49</id>
					<name></name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<coreName></coreName>
				</Obj>
				<node_objs>
					<count>1</count>
					<item_version>0</item_version>
					<item>48</item>
				</node_objs>
			</item>
		</blocks>
		<edges class_id="19" tracking_level="0" version="0">
			<count>46</count>
			<item_version>0</item_version>
			<item class_id="20" tracking_level="1" version="0" object_id="_40">
				<id>52</id>
				<edge_type>1</edge_type>
				<source_obj>3</source_obj>
				<sink_obj>6</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_41">
				<id>53</id>
				<edge_type>2</edge_type>
				<source_obj>14</source_obj>
				<sink_obj>7</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_42">
				<id>54</id>
				<edge_type>1</edge_type>
				<source_obj>12</source_obj>
				<sink_obj>9</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_43">
				<id>55</id>
				<edge_type>2</edge_type>
				<source_obj>47</source_obj>
				<sink_obj>9</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_44">
				<id>57</id>
				<edge_type>1</edge_type>
				<source_obj>56</source_obj>
				<sink_obj>9</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_45">
				<id>58</id>
				<edge_type>2</edge_type>
				<source_obj>8</source_obj>
				<sink_obj>9</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_46">
				<id>59</id>
				<edge_type>1</edge_type>
				<source_obj>9</source_obj>
				<sink_obj>10</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_47">
				<id>61</id>
				<edge_type>1</edge_type>
				<source_obj>60</source_obj>
				<sink_obj>10</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_48">
				<id>62</id>
				<edge_type>1</edge_type>
				<source_obj>9</source_obj>
				<sink_obj>12</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_49">
				<id>64</id>
				<edge_type>1</edge_type>
				<source_obj>63</source_obj>
				<sink_obj>12</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_50">
				<id>65</id>
				<edge_type>1</edge_type>
				<source_obj>10</source_obj>
				<sink_obj>13</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_51">
				<id>66</id>
				<edge_type>2</edge_type>
				<source_obj>18</source_obj>
				<sink_obj>13</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_52">
				<id>67</id>
				<edge_type>2</edge_type>
				<source_obj>49</source_obj>
				<sink_obj>13</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_53">
				<id>68</id>
				<edge_type>2</edge_type>
				<source_obj>24</source_obj>
				<sink_obj>17</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_54">
				<id>70</id>
				<edge_type>1</edge_type>
				<source_obj>69</source_obj>
				<sink_obj>19</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_55">
				<id>71</id>
				<edge_type>2</edge_type>
				<source_obj>18</source_obj>
				<sink_obj>19</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_56">
				<id>72</id>
				<edge_type>1</edge_type>
				<source_obj>22</source_obj>
				<sink_obj>19</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_57">
				<id>73</id>
				<edge_type>2</edge_type>
				<source_obj>44</source_obj>
				<sink_obj>19</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_58">
				<id>74</id>
				<edge_type>1</edge_type>
				<source_obj>19</source_obj>
				<sink_obj>20</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_59">
				<id>76</id>
				<edge_type>1</edge_type>
				<source_obj>75</source_obj>
				<sink_obj>20</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_60">
				<id>77</id>
				<edge_type>1</edge_type>
				<source_obj>19</source_obj>
				<sink_obj>22</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_61">
				<id>79</id>
				<edge_type>1</edge_type>
				<source_obj>78</source_obj>
				<sink_obj>22</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_62">
				<id>80</id>
				<edge_type>1</edge_type>
				<source_obj>20</source_obj>
				<sink_obj>23</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_63">
				<id>81</id>
				<edge_type>2</edge_type>
				<source_obj>44</source_obj>
				<sink_obj>23</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_64">
				<id>82</id>
				<edge_type>2</edge_type>
				<source_obj>47</source_obj>
				<sink_obj>23</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_65">
				<id>85</id>
				<edge_type>1</edge_type>
				<source_obj>1</source_obj>
				<sink_obj>30</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_66">
				<id>86</id>
				<edge_type>1</edge_type>
				<source_obj>30</source_obj>
				<sink_obj>33</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_67">
				<id>87</id>
				<edge_type>1</edge_type>
				<source_obj>33</source_obj>
				<sink_obj>34</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_68">
				<id>88</id>
				<edge_type>1</edge_type>
				<source_obj>34</source_obj>
				<sink_obj>35</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_69">
				<id>89</id>
				<edge_type>1</edge_type>
				<source_obj>6</source_obj>
				<sink_obj>35</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_70">
				<id>90</id>
				<edge_type>1</edge_type>
				<source_obj>35</source_obj>
				<sink_obj>36</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_71">
				<id>92</id>
				<edge_type>1</edge_type>
				<source_obj>91</source_obj>
				<sink_obj>36</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_72">
				<id>94</id>
				<edge_type>1</edge_type>
				<source_obj>93</source_obj>
				<sink_obj>37</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_73">
				<id>95</id>
				<edge_type>1</edge_type>
				<source_obj>36</source_obj>
				<sink_obj>37</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_74">
				<id>98</id>
				<edge_type>1</edge_type>
				<source_obj>2</source_obj>
				<sink_obj>40</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_75">
				<id>99</id>
				<edge_type>1</edge_type>
				<source_obj>37</source_obj>
				<sink_obj>40</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_76">
				<id>100</id>
				<edge_type>2</edge_type>
				<source_obj>24</source_obj>
				<sink_obj>43</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_77">
				<id>101</id>
				<edge_type>2</edge_type>
				<source_obj>14</source_obj>
				<sink_obj>46</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_78">
				<id>199</id>
				<edge_type>2</edge_type>
				<source_obj>8</source_obj>
				<sink_obj>14</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_79">
				<id>200</id>
				<edge_type>2</edge_type>
				<source_obj>14</source_obj>
				<sink_obj>49</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_80">
				<id>201</id>
				<edge_type>2</edge_type>
				<source_obj>14</source_obj>
				<sink_obj>18</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_81">
				<id>202</id>
				<edge_type>2</edge_type>
				<source_obj>18</source_obj>
				<sink_obj>24</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_82">
				<id>203</id>
				<edge_type>2</edge_type>
				<source_obj>24</source_obj>
				<sink_obj>47</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_83">
				<id>204</id>
				<edge_type>2</edge_type>
				<source_obj>24</source_obj>
				<sink_obj>44</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_84">
				<id>205</id>
				<edge_type>2</edge_type>
				<source_obj>44</source_obj>
				<sink_obj>24</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_85">
				<id>206</id>
				<edge_type>2</edge_type>
				<source_obj>47</source_obj>
				<sink_obj>14</sink_obj>
			</item>
		</edges>
	</cdfg>
	<cdfg_regions class_id="21" tracking_level="0" version="0">
		<count>7</count>
		<item_version>0</item_version>
		<item class_id="22" tracking_level="1" version="0" object_id="_86">
			<mId>1</mId>
			<mTag>pynq_filters_arithm_pro</mTag>
			<mType>0</mType>
			<sub_regions>
				<count>3</count>
				<item_version>0</item_version>
				<item>2</item>
				<item>3</item>
				<item>7</item>
			</sub_regions>
			<basic_blocks>
				<count>0</count>
				<item_version>0</item_version>
			</basic_blocks>
			<mII>-1</mII>
			<mDepth>-1</mDepth>
			<mMinTripCount>-1</mMinTripCount>
			<mMaxTripCount>-1</mMaxTripCount>
			<mMinLatency>319201</mMinLatency>
			<mMaxLatency>-1</mMaxLatency>
			<mIsDfPipe>0</mIsDfPipe>
			<mDfPipe class_id="-1"></mDfPipe>
		</item>
		<item class_id_reference="22" object_id="_87">
			<mId>2</mId>
			<mTag>Entry</mTag>
			<mType>0</mType>
			<sub_regions>
				<count>0</count>
				<item_version>0</item_version>
			</sub_regions>
			<basic_blocks>
				<count>1</count>
				<item_version>0</item_version>
				<item>8</item>
			</basic_blocks>
			<mII>-1</mII>
			<mDepth>-1</mDepth>
			<mMinTripCount>-1</mMinTripCount>
			<mMaxTripCount>-1</mMaxTripCount>
			<mMinLatency>0</mMinLatency>
			<mMaxLatency>-1</mMaxLatency>
			<mIsDfPipe>0</mIsDfPipe>
			<mDfPipe class_id="-1"></mDfPipe>
		</item>
		<item class_id_reference="22" object_id="_88">
			<mId>3</mId>
			<mTag>loop_height</mTag>
			<mType>1</mType>
			<sub_regions>
				<count>3</count>
				<item_version>0</item_version>
				<item>4</item>
				<item>5</item>
				<item>6</item>
			</sub_regions>
			<basic_blocks>
				<count>0</count>
				<item_version>0</item_version>
			</basic_blocks>
			<mII>-1</mII>
			<mDepth>-1</mDepth>
			<mMinTripCount>480</mMinTripCount>
			<mMaxTripCount>480</mMaxTripCount>
			<mMinLatency>319200</mMinLatency>
			<mMaxLatency>-1</mMaxLatency>
			<mIsDfPipe>0</mIsDfPipe>
			<mDfPipe class_id="-1"></mDfPipe>
		</item>
		<item class_id_reference="22" object_id="_89">
			<mId>4</mId>
			<mTag>Region 1</mTag>
			<mType>0</mType>
			<sub_regions>
				<count>0</count>
				<item_version>0</item_version>
			</sub_regions>
			<basic_blocks>
				<count>2</count>
				<item_version>0</item_version>
				<item>14</item>
				<item>18</item>
			</basic_blocks>
			<mII>-1</mII>
			<mDepth>-1</mDepth>
			<mMinTripCount>-1</mMinTripCount>
			<mMaxTripCount>-1</mMaxTripCount>
			<mMinLatency>0</mMinLatency>
			<mMaxLatency>-1</mMaxLatency>
			<mIsDfPipe>0</mIsDfPipe>
			<mDfPipe class_id="-1"></mDfPipe>
		</item>
		<item class_id_reference="22" object_id="_90">
			<mId>5</mId>
			<mTag>loop_width</mTag>
			<mType>1</mType>
			<sub_regions>
				<count>0</count>
				<item_version>0</item_version>
			</sub_regions>
			<basic_blocks>
				<count>2</count>
				<item_version>0</item_version>
				<item>24</item>
				<item>44</item>
			</basic_blocks>
			<mII>1</mII>
			<mDepth>24</mDepth>
			<mMinTripCount>640</mMinTripCount>
			<mMaxTripCount>640</mMaxTripCount>
			<mMinLatency>662</mMinLatency>
			<mMaxLatency>-1</mMaxLatency>
			<mIsDfPipe>0</mIsDfPipe>
			<mDfPipe class_id="-1"></mDfPipe>
		</item>
		<item class_id_reference="22" object_id="_91">
			<mId>6</mId>
			<mTag>Region 2</mTag>
			<mType>0</mType>
			<sub_regions>
				<count>0</count>
				<item_version>0</item_version>
			</sub_regions>
			<basic_blocks>
				<count>1</count>
				<item_version>0</item_version>
				<item>47</item>
			</basic_blocks>
			<mII>-1</mII>
			<mDepth>-1</mDepth>
			<mMinTripCount>-1</mMinTripCount>
			<mMaxTripCount>-1</mMaxTripCount>
			<mMinLatency>0</mMinLatency>
			<mMaxLatency>-1</mMaxLatency>
			<mIsDfPipe>0</mIsDfPipe>
			<mDfPipe class_id="-1"></mDfPipe>
		</item>
		<item class_id_reference="22" object_id="_92">
			<mId>7</mId>
			<mTag>Return</mTag>
			<mType>0</mType>
			<sub_regions>
				<count>0</count>
				<item_version>0</item_version>
			</sub_regions>
			<basic_blocks>
				<count>1</count>
				<item_version>0</item_version>
				<item>49</item>
			</basic_blocks>
			<mII>-1</mII>
			<mDepth>-1</mDepth>
			<mMinTripCount>-1</mMinTripCount>
			<mMaxTripCount>-1</mMaxTripCount>
			<mMinLatency>0</mMinLatency>
			<mMaxLatency>-1</mMaxLatency>
			<mIsDfPipe>0</mIsDfPipe>
			<mDfPipe class_id="-1"></mDfPipe>
		</item>
	</cdfg_regions>
	<fsm class_id="-1"></fsm>
	<res class_id="-1"></res>
	<node_label_latency class_id="26" tracking_level="0" version="0">
		<count>21</count>
		<item_version>0</item_version>
		<item class_id="27" tracking_level="0" version="0">
			<first>6</first>
			<second class_id="28" tracking_level="0" version="0">
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>7</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>9</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>10</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>12</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>13</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>17</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>19</first>
			<second>
				<first>2</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>20</first>
			<second>
				<first>2</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>22</first>
			<second>
				<first>2</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>23</first>
			<second>
				<first>2</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>30</first>
			<second>
				<first>3</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>33</first>
			<second>
				<first>4</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>34</first>
			<second>
				<first>4</first>
				<second>5</second>
			</second>
		</item>
		<item>
			<first>35</first>
			<second>
				<first>10</first>
				<second>5</second>
			</second>
		</item>
		<item>
			<first>36</first>
			<second>
				<first>16</first>
				<second>4</second>
			</second>
		</item>
		<item>
			<first>37</first>
			<second>
				<first>21</first>
				<second>3</second>
			</second>
		</item>
		<item>
			<first>40</first>
			<second>
				<first>25</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>43</first>
			<second>
				<first>25</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>46</first>
			<second>
				<first>3</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>48</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
	</node_label_latency>
	<bblk_ent_exit class_id="29" tracking_level="0" version="0">
		<count>7</count>
		<item_version>0</item_version>
		<item class_id="30" tracking_level="0" version="0">
			<first>8</first>
			<second class_id="31" tracking_level="0" version="0">
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>14</first>
			<second>
				<first>1</first>
				<second>1</second>
			</second>
		</item>
		<item>
			<first>18</first>
			<second>
				<first>1</first>
				<second>1</second>
			</second>
		</item>
		<item>
			<first>24</first>
			<second>
				<first>2</first>
				<second>2</second>
			</second>
		</item>
		<item>
			<first>44</first>
			<second>
				<first>3</first>
				<second>25</second>
			</second>
		</item>
		<item>
			<first>47</first>
			<second>
				<first>3</first>
				<second>3</second>
			</second>
		</item>
		<item>
			<first>49</first>
			<second>
				<first>1</first>
				<second>1</second>
			</second>
		</item>
	</bblk_ent_exit>
	<regions class_id="32" tracking_level="0" version="0">
		<count>2</count>
		<item_version>0</item_version>
		<item class_id="33" tracking_level="1" version="0" object_id="_93">
			<region_name>hls_label_20</region_name>
			<basic_blocks>
				<count>1</count>
				<item_version>0</item_version>
				<item>44</item>
			</basic_blocks>
			<nodes>
				<count>4</count>
				<item_version>0</item_version>
				<item>38</item>
				<item>39</item>
				<item>40</item>
				<item>41</item>
			</nodes>
			<anchor_node>38</anchor_node>
			<region_type>1</region_type>
			<interval>0</interval>
			<pipe_depth>0</pipe_depth>
		</item>
		<item class_id_reference="33" object_id="_94">
			<region_name>loop_width</region_name>
			<basic_blocks>
				<count>2</count>
				<item_version>0</item_version>
				<item>24</item>
				<item>44</item>
			</basic_blocks>
			<nodes>
				<count>0</count>
				<item_version>0</item_version>
			</nodes>
			<anchor_node>-1</anchor_node>
			<region_type>8</region_type>
			<interval>1</interval>
			<pipe_depth>24</pipe_depth>
		</item>
	</regions>
	<dp_fu_nodes class_id="34" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</dp_fu_nodes>
	<dp_fu_nodes_expression class_id="35" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</dp_fu_nodes_expression>
	<dp_fu_nodes_module>
		<count>0</count>
		<item_version>0</item_version>
	</dp_fu_nodes_module>
	<dp_fu_nodes_io>
		<count>0</count>
		<item_version>0</item_version>
	</dp_fu_nodes_io>
	<return_ports>
		<count>0</count>
		<item_version>0</item_version>
	</return_ports>
	<dp_mem_port_nodes class_id="36" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</dp_mem_port_nodes>
	<dp_reg_nodes>
		<count>0</count>
		<item_version>0</item_version>
	</dp_reg_nodes>
	<dp_regname_nodes>
		<count>0</count>
		<item_version>0</item_version>
	</dp_regname_nodes>
	<dp_reg_phi>
		<count>0</count>
		<item_version>0</item_version>
	</dp_reg_phi>
	<dp_regname_phi>
		<count>0</count>
		<item_version>0</item_version>
	</dp_regname_phi>
	<dp_port_io_nodes class_id="37" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</dp_port_io_nodes>
	<port2core class_id="38" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</port2core>
	<node2core>
		<count>0</count>
		<item_version>0</item_version>
	</node2core>
</syndb>
</boost_serialization>

