// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "pynq_filters_CvtColor_1.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic pynq_filters_CvtColor_1::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic pynq_filters_CvtColor_1::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> pynq_filters_CvtColor_1::ap_ST_st1_fsm_0 = "1";
const sc_lv<4> pynq_filters_CvtColor_1::ap_ST_st2_fsm_1 = "10";
const sc_lv<4> pynq_filters_CvtColor_1::ap_ST_pp0_stg0_fsm_2 = "100";
const sc_lv<4> pynq_filters_CvtColor_1::ap_ST_st8_fsm_3 = "1000";
const sc_lv<32> pynq_filters_CvtColor_1::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> pynq_filters_CvtColor_1::ap_const_lv1_1 = "1";
const sc_lv<32> pynq_filters_CvtColor_1::ap_const_lv32_2 = "10";
const sc_lv<1> pynq_filters_CvtColor_1::ap_const_lv1_0 = "0";
const sc_lv<32> pynq_filters_CvtColor_1::ap_const_lv32_1 = "1";
const sc_lv<9> pynq_filters_CvtColor_1::ap_const_lv9_0 = "000000000";
const sc_lv<32> pynq_filters_CvtColor_1::ap_const_lv32_3 = "11";
const sc_lv<10> pynq_filters_CvtColor_1::ap_const_lv10_0 = "0000000000";
const sc_lv<9> pynq_filters_CvtColor_1::ap_const_lv9_1E0 = "111100000";
const sc_lv<9> pynq_filters_CvtColor_1::ap_const_lv9_1 = "1";
const sc_lv<10> pynq_filters_CvtColor_1::ap_const_lv10_280 = "1010000000";
const sc_lv<10> pynq_filters_CvtColor_1::ap_const_lv10_1 = "1";
const sc_lv<32> pynq_filters_CvtColor_1::ap_const_lv32_16 = "10110";
const sc_lv<32> pynq_filters_CvtColor_1::ap_const_lv32_1D = "11101";
const sc_lv<32> pynq_filters_CvtColor_1::ap_const_lv32_15 = "10101";
const sc_lv<32> pynq_filters_CvtColor_1::ap_const_lv32_7 = "111";
const sc_lv<8> pynq_filters_CvtColor_1::ap_const_lv8_FF = "11111111";
const sc_lv<28> pynq_filters_CvtColor_1::ap_const_lv28_74BC6 = "1110100101111000110";
const sc_lv<30> pynq_filters_CvtColor_1::ap_const_lv30_259168 = "1001011001000101101000";
const sc_lv<29> pynq_filters_CvtColor_1::ap_const_lv29_1322D0 = "100110010001011010000";

pynq_filters_CvtColor_1::pynq_filters_CvtColor_1(sc_module_name name) : sc_module(name), mVcdFile(0) {
    pynq_filters_mac_muladd_8ns_20ns_29ns_29_1_U31 = new pynq_filters_mac_muladd_8ns_20ns_29ns_29_1<1,1,8,20,29,29>("pynq_filters_mac_muladd_8ns_20ns_29ns_29_1_U31");
    pynq_filters_mac_muladd_8ns_20ns_29ns_29_1_U31->din0(grp_fu_233_p0);
    pynq_filters_mac_muladd_8ns_20ns_29ns_29_1_U31->din1(grp_fu_233_p1);
    pynq_filters_mac_muladd_8ns_20ns_29ns_29_1_U31->din2(r_V_i_reg_290);
    pynq_filters_mac_muladd_8ns_20ns_29ns_29_1_U31->dout(grp_fu_233_p3);
    pynq_filters_mac_muladd_8ns_23ns_29ns_30_1_U32 = new pynq_filters_mac_muladd_8ns_23ns_29ns_30_1<1,1,8,23,29,30>("pynq_filters_mac_muladd_8ns_23ns_29ns_30_1_U32");
    pynq_filters_mac_muladd_8ns_23ns_29ns_30_1_U32->din0(grp_fu_241_p0);
    pynq_filters_mac_muladd_8ns_23ns_29ns_30_1_U32->din1(grp_fu_241_p1);
    pynq_filters_mac_muladd_8ns_23ns_29ns_30_1_U32->din2(grp_fu_241_p2);
    pynq_filters_mac_muladd_8ns_23ns_29ns_30_1_U32->dout(grp_fu_241_p3);
    pynq_filters_mul_mul_8ns_22ns_29_1_U33 = new pynq_filters_mul_mul_8ns_22ns_29_1<1,1,8,22,29>("pynq_filters_mul_mul_8ns_22ns_29_1_U33");
    pynq_filters_mul_mul_8ns_22ns_29_1_U33->din0(r_V_i_fu_251_p0);
    pynq_filters_mul_mul_8ns_22ns_29_1_U33->din1(r_V_i_fu_251_p1);
    pynq_filters_mul_mul_8ns_22ns_29_1_U33->dout(r_V_i_fu_251_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( exitcond2_fu_137_p2 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( exitcond2_fu_137_p2 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_ap_sig_100);
    sensitive << ( p_dst_data_stream_V_full_n );
    sensitive << ( ap_reg_ppstg_exitcond_reg_266_pp0_iter3 );

    SC_METHOD(thread_ap_sig_150);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_sig_158);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_22);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_51);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_83);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_96);
    sensitive << ( p_src_data_stream_0_V_empty_n );
    sensitive << ( p_src_data_stream_1_V_empty_n );
    sensitive << ( p_src_data_stream_2_V_empty_n );
    sensitive << ( exitcond_reg_266 );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg0_fsm_2);
    sensitive << ( ap_sig_51 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_22 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_83 );

    SC_METHOD(thread_ap_sig_cseq_ST_st8_fsm_3);
    sensitive << ( ap_sig_158 );

    SC_METHOD(thread_exitcond2_fu_137_p2);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( i_reg_115 );

    SC_METHOD(thread_exitcond_fu_149_p2);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( j_reg_126 );
    sensitive << ( ap_sig_96 );
    sensitive << ( ap_sig_100 );

    SC_METHOD(thread_grp_fu_233_p0);
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( ap_reg_ppstg_exitcond_reg_266_pp0_iter2 );
    sensitive << ( grp_fu_233_p00 );

    SC_METHOD(thread_grp_fu_233_p00);
    sensitive << ( ap_reg_ppstg_tmp_134_reg_285_pp0_iter2 );

    SC_METHOD(thread_grp_fu_233_p1);
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( ap_reg_ppstg_exitcond_reg_266_pp0_iter2 );

    SC_METHOD(thread_grp_fu_241_p0);
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( ap_reg_ppstg_exitcond_reg_266_pp0_iter2 );
    sensitive << ( grp_fu_241_p00 );

    SC_METHOD(thread_grp_fu_241_p00);
    sensitive << ( ap_reg_ppstg_tmp_133_reg_280_pp0_iter2 );

    SC_METHOD(thread_grp_fu_241_p1);
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( ap_reg_ppstg_exitcond_reg_266_pp0_iter2 );

    SC_METHOD(thread_grp_fu_241_p2);
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( ap_reg_ppstg_exitcond_reg_266_pp0_iter2 );
    sensitive << ( grp_fu_241_p20 );

    SC_METHOD(thread_grp_fu_241_p20);
    sensitive << ( grp_fu_233_p3 );

    SC_METHOD(thread_i_1_fu_143_p2);
    sensitive << ( i_reg_115 );

    SC_METHOD(thread_j_1_fu_155_p2);
    sensitive << ( j_reg_126 );

    SC_METHOD(thread_not_carry_fu_218_p2);
    sensitive << ( tmp_130_fu_204_p3 );
    sensitive << ( p_Result_2_i_i_i_not_fu_212_p2 );

    SC_METHOD(thread_p_Result_2_i_i_i_not_fu_212_p2);
    sensitive << ( tmp_129_fu_192_p3 );

    SC_METHOD(thread_p_Val2_24_fu_199_p2);
    sensitive << ( p_Val2_23_reg_300 );
    sensitive << ( tmp_7_i_i_i_fu_189_p1 );

    SC_METHOD(thread_p_dst_data_stream_V_blk_n);
    sensitive << ( p_dst_data_stream_V_full_n );
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( ap_reg_ppstg_exitcond_reg_266_pp0_iter3 );

    SC_METHOD(thread_p_dst_data_stream_V_din);
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( ap_reg_ppstg_exitcond_reg_266_pp0_iter3 );
    sensitive << ( ap_sig_96 );
    sensitive << ( ap_sig_100 );
    sensitive << ( p_Val2_24_fu_199_p2 );
    sensitive << ( not_carry_fu_218_p2 );

    SC_METHOD(thread_p_dst_data_stream_V_write);
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( ap_reg_ppstg_exitcond_reg_266_pp0_iter3 );
    sensitive << ( ap_sig_96 );
    sensitive << ( ap_sig_100 );

    SC_METHOD(thread_p_src_data_stream_0_V_blk_n);
    sensitive << ( p_src_data_stream_0_V_empty_n );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( exitcond_reg_266 );

    SC_METHOD(thread_p_src_data_stream_0_V_read);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( exitcond_reg_266 );
    sensitive << ( ap_sig_96 );
    sensitive << ( ap_sig_100 );

    SC_METHOD(thread_p_src_data_stream_1_V_blk_n);
    sensitive << ( p_src_data_stream_1_V_empty_n );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( exitcond_reg_266 );

    SC_METHOD(thread_p_src_data_stream_1_V_read);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( exitcond_reg_266 );
    sensitive << ( ap_sig_96 );
    sensitive << ( ap_sig_100 );

    SC_METHOD(thread_p_src_data_stream_2_V_blk_n);
    sensitive << ( p_src_data_stream_2_V_empty_n );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( exitcond_reg_266 );

    SC_METHOD(thread_p_src_data_stream_2_V_read);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( exitcond_reg_266 );
    sensitive << ( ap_sig_96 );
    sensitive << ( ap_sig_100 );

    SC_METHOD(thread_r_V_i_fu_251_p0);
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( r_V_i_fu_251_p00 );

    SC_METHOD(thread_r_V_i_fu_251_p00);
    sensitive << ( tmp_132_reg_275 );

    SC_METHOD(thread_r_V_i_fu_251_p1);
    sensitive << ( ap_reg_ppiten_pp0_it2 );

    SC_METHOD(thread_tmp_129_fu_192_p3);
    sensitive << ( r_V_1_reg_295 );

    SC_METHOD(thread_tmp_130_fu_204_p3);
    sensitive << ( p_Val2_24_fu_199_p2 );

    SC_METHOD(thread_tmp_7_i_i_i_fu_189_p1);
    sensitive << ( tmp_128_reg_305 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( exitcond2_fu_137_p2 );
    sensitive << ( exitcond_fu_149_p2 );
    sensitive << ( ap_sig_96 );
    sensitive << ( ap_sig_100 );
    sensitive << ( ap_sig_150 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "0001";
    ap_reg_ppiten_pp0_it1 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it0 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it2 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it3 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it4 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "pynq_filters_CvtColor_1_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, p_src_data_stream_0_V_dout, "(port)p_src_data_stream_0_V_dout");
    sc_trace(mVcdFile, p_src_data_stream_0_V_empty_n, "(port)p_src_data_stream_0_V_empty_n");
    sc_trace(mVcdFile, p_src_data_stream_0_V_read, "(port)p_src_data_stream_0_V_read");
    sc_trace(mVcdFile, p_src_data_stream_1_V_dout, "(port)p_src_data_stream_1_V_dout");
    sc_trace(mVcdFile, p_src_data_stream_1_V_empty_n, "(port)p_src_data_stream_1_V_empty_n");
    sc_trace(mVcdFile, p_src_data_stream_1_V_read, "(port)p_src_data_stream_1_V_read");
    sc_trace(mVcdFile, p_src_data_stream_2_V_dout, "(port)p_src_data_stream_2_V_dout");
    sc_trace(mVcdFile, p_src_data_stream_2_V_empty_n, "(port)p_src_data_stream_2_V_empty_n");
    sc_trace(mVcdFile, p_src_data_stream_2_V_read, "(port)p_src_data_stream_2_V_read");
    sc_trace(mVcdFile, p_dst_data_stream_V_din, "(port)p_dst_data_stream_V_din");
    sc_trace(mVcdFile, p_dst_data_stream_V_full_n, "(port)p_dst_data_stream_V_full_n");
    sc_trace(mVcdFile, p_dst_data_stream_V_write, "(port)p_dst_data_stream_V_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_22, "ap_sig_22");
    sc_trace(mVcdFile, p_src_data_stream_0_V_blk_n, "p_src_data_stream_0_V_blk_n");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg0_fsm_2, "ap_sig_cseq_ST_pp0_stg0_fsm_2");
    sc_trace(mVcdFile, ap_sig_51, "ap_sig_51");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it1, "ap_reg_ppiten_pp0_it1");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it0, "ap_reg_ppiten_pp0_it0");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it2, "ap_reg_ppiten_pp0_it2");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it3, "ap_reg_ppiten_pp0_it3");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it4, "ap_reg_ppiten_pp0_it4");
    sc_trace(mVcdFile, exitcond_reg_266, "exitcond_reg_266");
    sc_trace(mVcdFile, p_src_data_stream_1_V_blk_n, "p_src_data_stream_1_V_blk_n");
    sc_trace(mVcdFile, p_src_data_stream_2_V_blk_n, "p_src_data_stream_2_V_blk_n");
    sc_trace(mVcdFile, p_dst_data_stream_V_blk_n, "p_dst_data_stream_V_blk_n");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_266_pp0_iter3, "ap_reg_ppstg_exitcond_reg_266_pp0_iter3");
    sc_trace(mVcdFile, j_reg_126, "j_reg_126");
    sc_trace(mVcdFile, exitcond2_fu_137_p2, "exitcond2_fu_137_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_83, "ap_sig_83");
    sc_trace(mVcdFile, i_1_fu_143_p2, "i_1_fu_143_p2");
    sc_trace(mVcdFile, i_1_reg_261, "i_1_reg_261");
    sc_trace(mVcdFile, exitcond_fu_149_p2, "exitcond_fu_149_p2");
    sc_trace(mVcdFile, ap_sig_96, "ap_sig_96");
    sc_trace(mVcdFile, ap_sig_100, "ap_sig_100");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_266_pp0_iter1, "ap_reg_ppstg_exitcond_reg_266_pp0_iter1");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_266_pp0_iter2, "ap_reg_ppstg_exitcond_reg_266_pp0_iter2");
    sc_trace(mVcdFile, j_1_fu_155_p2, "j_1_fu_155_p2");
    sc_trace(mVcdFile, tmp_132_reg_275, "tmp_132_reg_275");
    sc_trace(mVcdFile, tmp_133_reg_280, "tmp_133_reg_280");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_133_reg_280_pp0_iter2, "ap_reg_ppstg_tmp_133_reg_280_pp0_iter2");
    sc_trace(mVcdFile, tmp_134_reg_285, "tmp_134_reg_285");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_134_reg_285_pp0_iter2, "ap_reg_ppstg_tmp_134_reg_285_pp0_iter2");
    sc_trace(mVcdFile, r_V_i_fu_251_p2, "r_V_i_fu_251_p2");
    sc_trace(mVcdFile, r_V_i_reg_290, "r_V_i_reg_290");
    sc_trace(mVcdFile, grp_fu_241_p3, "grp_fu_241_p3");
    sc_trace(mVcdFile, r_V_1_reg_295, "r_V_1_reg_295");
    sc_trace(mVcdFile, p_Val2_23_reg_300, "p_Val2_23_reg_300");
    sc_trace(mVcdFile, tmp_128_reg_305, "tmp_128_reg_305");
    sc_trace(mVcdFile, i_reg_115, "i_reg_115");
    sc_trace(mVcdFile, ap_sig_150, "ap_sig_150");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st8_fsm_3, "ap_sig_cseq_ST_st8_fsm_3");
    sc_trace(mVcdFile, ap_sig_158, "ap_sig_158");
    sc_trace(mVcdFile, grp_fu_233_p3, "grp_fu_233_p3");
    sc_trace(mVcdFile, tmp_7_i_i_i_fu_189_p1, "tmp_7_i_i_i_fu_189_p1");
    sc_trace(mVcdFile, p_Val2_24_fu_199_p2, "p_Val2_24_fu_199_p2");
    sc_trace(mVcdFile, tmp_129_fu_192_p3, "tmp_129_fu_192_p3");
    sc_trace(mVcdFile, tmp_130_fu_204_p3, "tmp_130_fu_204_p3");
    sc_trace(mVcdFile, p_Result_2_i_i_i_not_fu_212_p2, "p_Result_2_i_i_i_not_fu_212_p2");
    sc_trace(mVcdFile, not_carry_fu_218_p2, "not_carry_fu_218_p2");
    sc_trace(mVcdFile, grp_fu_233_p0, "grp_fu_233_p0");
    sc_trace(mVcdFile, grp_fu_233_p1, "grp_fu_233_p1");
    sc_trace(mVcdFile, grp_fu_241_p0, "grp_fu_241_p0");
    sc_trace(mVcdFile, grp_fu_241_p1, "grp_fu_241_p1");
    sc_trace(mVcdFile, grp_fu_241_p2, "grp_fu_241_p2");
    sc_trace(mVcdFile, r_V_i_fu_251_p0, "r_V_i_fu_251_p0");
    sc_trace(mVcdFile, r_V_i_fu_251_p1, "r_V_i_fu_251_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, grp_fu_233_p00, "grp_fu_233_p00");
    sc_trace(mVcdFile, grp_fu_241_p00, "grp_fu_241_p00");
    sc_trace(mVcdFile, grp_fu_241_p20, "grp_fu_241_p20");
    sc_trace(mVcdFile, r_V_i_fu_251_p00, "r_V_i_fu_251_p00");
#endif

    }
}

pynq_filters_CvtColor_1::~pynq_filters_CvtColor_1() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete pynq_filters_mac_muladd_8ns_20ns_29ns_29_1_U31;
    delete pynq_filters_mac_muladd_8ns_23ns_29ns_30_1_U32;
    delete pynq_filters_mul_mul_8ns_22ns_29_1_U33;
}

void pynq_filters_CvtColor_1::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                    !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_137_p2.read()))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
             !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
  ap_sig_96.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) && 
  ap_sig_100.read())) && 
             !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_149_p2.read()))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_137_p2.read()))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
             !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
  ap_sig_96.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) && 
  ap_sig_100.read())) && 
             esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_149_p2.read()))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                     esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_137_p2.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
                     !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
  ap_sig_96.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) && 
  ap_sig_100.read())) && 
                     !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_149_p2.read())))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it2 = ap_const_logic_0;
    } else {
        if (!((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
  ap_sig_96.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) && 
  ap_sig_100.read()))) {
            ap_reg_ppiten_pp0_it2 = ap_reg_ppiten_pp0_it1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it3 = ap_const_logic_0;
    } else {
        if (!((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
  ap_sig_96.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) && 
  ap_sig_100.read()))) {
            ap_reg_ppiten_pp0_it3 = ap_reg_ppiten_pp0_it2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it4 = ap_const_logic_0;
    } else {
        if (!((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
  ap_sig_96.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) && 
  ap_sig_100.read()))) {
            ap_reg_ppiten_pp0_it4 = ap_reg_ppiten_pp0_it3.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_137_p2.read()))) {
            ap_reg_ppiten_pp0_it4 = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_3.read())) {
        i_reg_115 = i_1_reg_261.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !ap_sig_150.read())) {
        i_reg_115 = ap_const_lv9_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
  ap_sig_96.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) && 
  ap_sig_100.read())) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_149_p2.read()))) {
        j_reg_126 = j_1_fu_155_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_137_p2.read()))) {
        j_reg_126 = ap_const_lv10_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
  ap_sig_96.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) && 
  ap_sig_100.read())))) {
        ap_reg_ppstg_exitcond_reg_266_pp0_iter1 = exitcond_reg_266.read();
        exitcond_reg_266 = exitcond_fu_149_p2.read();
    }
    if (!((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
  ap_sig_96.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) && 
  ap_sig_100.read()))) {
        ap_reg_ppstg_exitcond_reg_266_pp0_iter2 = ap_reg_ppstg_exitcond_reg_266_pp0_iter1.read();
        ap_reg_ppstg_exitcond_reg_266_pp0_iter3 = ap_reg_ppstg_exitcond_reg_266_pp0_iter2.read();
        ap_reg_ppstg_tmp_133_reg_280_pp0_iter2 = tmp_133_reg_280.read();
        ap_reg_ppstg_tmp_134_reg_285_pp0_iter2 = tmp_134_reg_285.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        i_1_reg_261 = i_1_fu_143_p2.read();
    }
    if ((!((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
  ap_sig_96.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) && 
  ap_sig_100.read())) && esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_266_pp0_iter2.read()))) {
        p_Val2_23_reg_300 = grp_fu_241_p3.read().range(29, 22);
        tmp_128_reg_305 = grp_fu_241_p3.read().range(21, 21);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read()) && !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
  ap_sig_96.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) && 
  ap_sig_100.read())) && esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_266_pp0_iter2.read()))) {
        r_V_1_reg_295 = grp_fu_241_p3.read();
    }
    if ((!((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
  ap_sig_96.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) && 
  ap_sig_100.read())) && esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_266_pp0_iter1.read()))) {
        r_V_i_reg_290 = r_V_i_fu_251_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && esl_seteq<1,1,1>(exitcond_reg_266.read(), ap_const_lv1_0) && !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
  ap_sig_96.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) && 
  ap_sig_100.read())))) {
        tmp_132_reg_275 = p_src_data_stream_0_V_dout.read();
        tmp_133_reg_280 = p_src_data_stream_1_V_dout.read();
        tmp_134_reg_285 = p_src_data_stream_2_V_dout.read();
    }
}

void pynq_filters_CvtColor_1::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_done_reg.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_137_p2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void pynq_filters_CvtColor_1::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void pynq_filters_CvtColor_1::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_137_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void pynq_filters_CvtColor_1::thread_ap_sig_100() {
    ap_sig_100 = (esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_266_pp0_iter3.read()) && esl_seteq<1,1,1>(p_dst_data_stream_V_full_n.read(), ap_const_logic_0));
}

void pynq_filters_CvtColor_1::thread_ap_sig_150() {
    ap_sig_150 = (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void pynq_filters_CvtColor_1::thread_ap_sig_158() {
    ap_sig_158 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void pynq_filters_CvtColor_1::thread_ap_sig_22() {
    ap_sig_22 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void pynq_filters_CvtColor_1::thread_ap_sig_51() {
    ap_sig_51 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void pynq_filters_CvtColor_1::thread_ap_sig_83() {
    ap_sig_83 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void pynq_filters_CvtColor_1::thread_ap_sig_96() {
    ap_sig_96 = ((esl_seteq<1,1,1>(exitcond_reg_266.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(p_src_data_stream_0_V_empty_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_reg_266.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(p_src_data_stream_1_V_empty_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_reg_266.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(p_src_data_stream_2_V_empty_n.read(), ap_const_logic_0)));
}

void pynq_filters_CvtColor_1::thread_ap_sig_cseq_ST_pp0_stg0_fsm_2() {
    if (ap_sig_51.read()) {
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = ap_const_logic_0;
    }
}

void pynq_filters_CvtColor_1::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_22.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void pynq_filters_CvtColor_1::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_83.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void pynq_filters_CvtColor_1::thread_ap_sig_cseq_ST_st8_fsm_3() {
    if (ap_sig_158.read()) {
        ap_sig_cseq_ST_st8_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st8_fsm_3 = ap_const_logic_0;
    }
}

void pynq_filters_CvtColor_1::thread_exitcond2_fu_137_p2() {
    exitcond2_fu_137_p2 = (!i_reg_115.read().is_01() || !ap_const_lv9_1E0.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_115.read() == ap_const_lv9_1E0);
}

void pynq_filters_CvtColor_1::thread_exitcond_fu_149_p2() {
    exitcond_fu_149_p2 = (!j_reg_126.read().is_01() || !ap_const_lv10_280.is_01())? sc_lv<1>(): sc_lv<1>(j_reg_126.read() == ap_const_lv10_280);
}

void pynq_filters_CvtColor_1::thread_grp_fu_233_p0() {
    grp_fu_233_p0 =  (sc_lv<8>) (grp_fu_233_p00.read());
}

void pynq_filters_CvtColor_1::thread_grp_fu_233_p00() {
    grp_fu_233_p00 = esl_zext<28,8>(ap_reg_ppstg_tmp_134_reg_285_pp0_iter2.read());
}

void pynq_filters_CvtColor_1::thread_grp_fu_233_p1() {
    grp_fu_233_p1 =  (sc_lv<20>) (ap_const_lv28_74BC6);
}

void pynq_filters_CvtColor_1::thread_grp_fu_241_p0() {
    grp_fu_241_p0 =  (sc_lv<8>) (grp_fu_241_p00.read());
}

void pynq_filters_CvtColor_1::thread_grp_fu_241_p00() {
    grp_fu_241_p00 = esl_zext<30,8>(ap_reg_ppstg_tmp_133_reg_280_pp0_iter2.read());
}

void pynq_filters_CvtColor_1::thread_grp_fu_241_p1() {
    grp_fu_241_p1 =  (sc_lv<23>) (ap_const_lv30_259168);
}

void pynq_filters_CvtColor_1::thread_grp_fu_241_p2() {
    grp_fu_241_p2 =  (sc_lv<29>) (grp_fu_241_p20.read());
}

void pynq_filters_CvtColor_1::thread_grp_fu_241_p20() {
    grp_fu_241_p20 = esl_zext<30,29>(grp_fu_233_p3.read());
}

void pynq_filters_CvtColor_1::thread_i_1_fu_143_p2() {
    i_1_fu_143_p2 = (!i_reg_115.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(i_reg_115.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void pynq_filters_CvtColor_1::thread_j_1_fu_155_p2() {
    j_1_fu_155_p2 = (!j_reg_126.read().is_01() || !ap_const_lv10_1.is_01())? sc_lv<10>(): (sc_biguint<10>(j_reg_126.read()) + sc_biguint<10>(ap_const_lv10_1));
}

void pynq_filters_CvtColor_1::thread_not_carry_fu_218_p2() {
    not_carry_fu_218_p2 = (tmp_130_fu_204_p3.read() | p_Result_2_i_i_i_not_fu_212_p2.read());
}

void pynq_filters_CvtColor_1::thread_p_Result_2_i_i_i_not_fu_212_p2() {
    p_Result_2_i_i_i_not_fu_212_p2 = (tmp_129_fu_192_p3.read() ^ ap_const_lv1_1);
}

void pynq_filters_CvtColor_1::thread_p_Val2_24_fu_199_p2() {
    p_Val2_24_fu_199_p2 = (!p_Val2_23_reg_300.read().is_01() || !tmp_7_i_i_i_fu_189_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(p_Val2_23_reg_300.read()) + sc_biguint<8>(tmp_7_i_i_i_fu_189_p1.read()));
}

void pynq_filters_CvtColor_1::thread_p_dst_data_stream_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_266_pp0_iter3.read()))) {
        p_dst_data_stream_V_blk_n = p_dst_data_stream_V_full_n.read();
    } else {
        p_dst_data_stream_V_blk_n = ap_const_logic_1;
    }
}

void pynq_filters_CvtColor_1::thread_p_dst_data_stream_V_din() {
    p_dst_data_stream_V_din = (!not_carry_fu_218_p2.read()[0].is_01())? sc_lv<8>(): ((not_carry_fu_218_p2.read()[0].to_bool())? p_Val2_24_fu_199_p2.read(): ap_const_lv8_FF);
}

void pynq_filters_CvtColor_1::thread_p_dst_data_stream_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_266_pp0_iter3.read()) && 
         !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
  ap_sig_96.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) && 
  ap_sig_100.read())))) {
        p_dst_data_stream_V_write = ap_const_logic_1;
    } else {
        p_dst_data_stream_V_write = ap_const_logic_0;
    }
}

void pynq_filters_CvtColor_1::thread_p_src_data_stream_0_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond_reg_266.read(), ap_const_lv1_0))) {
        p_src_data_stream_0_V_blk_n = p_src_data_stream_0_V_empty_n.read();
    } else {
        p_src_data_stream_0_V_blk_n = ap_const_logic_1;
    }
}

void pynq_filters_CvtColor_1::thread_p_src_data_stream_0_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond_reg_266.read(), ap_const_lv1_0) && 
         !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
  ap_sig_96.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) && 
  ap_sig_100.read())))) {
        p_src_data_stream_0_V_read = ap_const_logic_1;
    } else {
        p_src_data_stream_0_V_read = ap_const_logic_0;
    }
}

void pynq_filters_CvtColor_1::thread_p_src_data_stream_1_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond_reg_266.read(), ap_const_lv1_0))) {
        p_src_data_stream_1_V_blk_n = p_src_data_stream_1_V_empty_n.read();
    } else {
        p_src_data_stream_1_V_blk_n = ap_const_logic_1;
    }
}

void pynq_filters_CvtColor_1::thread_p_src_data_stream_1_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond_reg_266.read(), ap_const_lv1_0) && 
         !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
  ap_sig_96.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) && 
  ap_sig_100.read())))) {
        p_src_data_stream_1_V_read = ap_const_logic_1;
    } else {
        p_src_data_stream_1_V_read = ap_const_logic_0;
    }
}

void pynq_filters_CvtColor_1::thread_p_src_data_stream_2_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond_reg_266.read(), ap_const_lv1_0))) {
        p_src_data_stream_2_V_blk_n = p_src_data_stream_2_V_empty_n.read();
    } else {
        p_src_data_stream_2_V_blk_n = ap_const_logic_1;
    }
}

void pynq_filters_CvtColor_1::thread_p_src_data_stream_2_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond_reg_266.read(), ap_const_lv1_0) && 
         !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
  ap_sig_96.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) && 
  ap_sig_100.read())))) {
        p_src_data_stream_2_V_read = ap_const_logic_1;
    } else {
        p_src_data_stream_2_V_read = ap_const_logic_0;
    }
}

void pynq_filters_CvtColor_1::thread_r_V_i_fu_251_p0() {
    r_V_i_fu_251_p0 =  (sc_lv<8>) (r_V_i_fu_251_p00.read());
}

void pynq_filters_CvtColor_1::thread_r_V_i_fu_251_p00() {
    r_V_i_fu_251_p00 = esl_zext<29,8>(tmp_132_reg_275.read());
}

void pynq_filters_CvtColor_1::thread_r_V_i_fu_251_p1() {
    r_V_i_fu_251_p1 =  (sc_lv<22>) (ap_const_lv29_1322D0);
}

void pynq_filters_CvtColor_1::thread_tmp_129_fu_192_p3() {
    tmp_129_fu_192_p3 = r_V_1_reg_295.read().range(29, 29);
}

void pynq_filters_CvtColor_1::thread_tmp_130_fu_204_p3() {
    tmp_130_fu_204_p3 = p_Val2_24_fu_199_p2.read().range(7, 7);
}

void pynq_filters_CvtColor_1::thread_tmp_7_i_i_i_fu_189_p1() {
    tmp_7_i_i_i_fu_189_p1 = esl_zext<8,1>(tmp_128_reg_305.read());
}

void pynq_filters_CvtColor_1::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!ap_sig_150.read()) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_137_p2.read())) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            }
            break;
        case 4 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) && !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
  ap_sig_96.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) && 
  ap_sig_100.read())) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read())) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
  ap_sig_96.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) && 
  ap_sig_100.read())) && !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_149_p2.read()) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) && 
  !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
  ap_sig_96.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) && 
  ap_sig_100.read())) && 
  !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
  !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
  ap_sig_96.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) && 
  ap_sig_100.read())) && 
  !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_149_p2.read()) && 
  !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
                ap_NS_fsm = ap_ST_st8_fsm_3;
            } else {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_st2_fsm_1;
            break;
        default : 
            ap_NS_fsm = "XXXX";
            break;
    }
}

}

