// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xsplit_ip.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XSplit_ip_CfgInitialize(XSplit_ip *InstancePtr, XSplit_ip_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XSplit_ip_Set_direction(XSplit_ip *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSplit_ip_WriteReg(InstancePtr->Axilites_BaseAddress, XSPLIT_IP_AXILITES_ADDR_DIRECTION_DATA, Data);
}

u32 XSplit_ip_Get_direction(XSplit_ip *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSplit_ip_ReadReg(InstancePtr->Axilites_BaseAddress, XSPLIT_IP_AXILITES_ADDR_DIRECTION_DATA);
    return Data;
}

